In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import json
import ast
import os
import csv
import math
from sklearn.utils import shuffle
from math import ceil
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm

2023-07-31 10:25:35.667191: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-31 10:25:36.556180: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
tqdm.pandas()

In [5]:

args = pd.Series({
    "root_dir":"/mnt/disks/data/",
    "dataset_path":"/mnt/disks/data/fma/fma_large",
    "embeddings":"music_style",
    "sequence_size": 1280,
    "train_id": "hierarchical_local_partial",
    'sample_size': 0.6
})

In [6]:

base_path = "/mnt/disks/data/fma/trains"


job_path = os.path.join(base_path,args.train_id)


tfrecord_path = os.path.join(job_path,"tfrecords")

# In[16]:

base_path = os.path.join(args.root_dir,"fma")

# In[17]:

models_path = os.path.join(args.root_dir,"models")


metadata_path_fma = os.path.join(base_path,"fma_metadata")

# In[18]:

metadata_path = os.path.join(job_path,"metadata.json")


categories_labels_path = os.path.join(job_path,"labels.json")

In [7]:


def __load_json__(path):
    with open(path, 'r') as f:
        tmp = json.loads(f.read())

    return tmp

In [8]:

def create_dir(path):
    # checking if the directory demo_folder2 
    # exist or not.
    if not os.path.isdir(path):

        # if the demo_folder2 directory is 
        # not present then create it.
        os.makedirs(path)
    return True

In [9]:
import shutil
shutil.rmtree(job_path)

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disks/data/fma/trains/hierarchical_local_partial'

In [50]:
create_dir(job_path)

True

## Load genres file. Contains relationships beetwen genres

In [10]:
genres_df = pd.read_csv(os.path.join(metadata_path_fma,'genres.csv'))

In [11]:
genres_df

     genre_id  #tracks  parent          title  top_level
0           1     8693      38    Avant-Garde         38
1           2     5271       0  International          2
2           3     1752       0          Blues          3
3           4     4126       0           Jazz          4
4           5     4106       0      Classical          5
..        ...      ...     ...            ...        ...
158      1032       60     102        Turkish          2
159      1060       30      46          Tango          2
160      1156       26     130           Fado          2
161      1193       72     763      Christmas         38
162      1235    14938       0   Instrumental       1235

[163 rows x 5 columns]

In [12]:
genres_df[genres_df['genre_id'] == 495]

     genre_id  #tracks  parent      title  top_level
136       495     2061      15  Downtempo         15

In [16]:
# Cria um dicionário que associa o ID de cada música aos IDs de seus gêneros musicais
tracks_df = pd.read_csv(os.path.join(metadata_path_fma,'tracks_valid.csv'))

In [17]:
tracks_df = tracks_df.sample(frac=args.sample_size)

In [18]:
tracks_df.sample(20)

,track_id,track_title,valid_genre
52294,79720,Spire,"['38', '42', '107']"
46962,70490,LURKING SOUL MARCHING TOWARDS SALVATION,"['1', '4', '38', '107', '322']"
66663,104653,a little theological advice,"['19', '85', '138']"
41208,62616,for the neonate remix (DeMo),"['32', '38']"
22473,35769,Title is too long so (corpses),"['10', '27', '66']"
91342,137220,Manifold,"['15', '1235']"
57960,87166,(stay with me in chapel hill),"['17', '32', '38']"
12602,20872,my neighbours` girlfriend,"['1', '27', '36', '76', '125', '186']"
18537,30078,100219_02,"['1', '15', '38']"
74901,115400,Mourning Advertisement,['76']
91434,137346,"Si je pleure toutes les larmes de mon corps, v...","['38', '41', '247']"
56851,85738,Text Reading,"['27', '38']"
95540,142916,Combat,"['12', '66', '1235']"
94891,142134,Live Set on WFMU's Undancing in the Dirt with ...,"['25', '32']"
44215,66414,Thaw You Out,"['10', '103']"
29867,46232,"be all you can be, with me",['6']
8330,14314,Aeronáutica II,"['15', '38', '42', '64']"
28673,44149,Dream State,"['2', '15', '224']"
94767,141945,Burden 04,"['15', '38', '47']"
15280,24918,"WFMU-Part 1 full set ""Apples/The Wet Look""","['12', '15', '66', '113']"

In [19]:
tracks_df.valid_genre.values

array(["['1', '32', '38', '41', '186', '224']", "['15', '32', '183']",
       "['22']", ..., "['25']", "['38', '53', '109']",
       "['15', '236', '495']"], dtype=object)

In [20]:
tracks_df.track_title

44278              Ring of Five Blades
42864    no audio+ (4/4)_remix by etc.
23198      The Little Hotel of Horrors
16755                       Re Ejected
84995         roof burning catastrophy
                     ...
16082                          Yagliza
18310                          Act One
7908                I Think I Love You
44028                      White Lines
36871          My Hearts In Your Hands
Name: track_title, Length: 62512, dtype: object

In [21]:
## Get complete genre structure
def get_all_structure(estrutura,df_genres):
    ## Get structure from df_genres
    def get_all_structure_from_df(estrutura,df_genres,structure=[]):
        if estrutura == 0:
            return structure
        else:
            structure.append(int(estrutura))
            get_all_structure_from_df(df_genres[df_genres["genre_id"]==int(estrutura)].parent.values[0],df_genres,structure)
            return structure
    
    return get_all_structure_from_df(estrutura,df_genres,structure=[])

In [22]:
# tracks_df['valid_genre'] = tracks_df.track_genres.apply(lambda x: x.strip('][').split(', ') if x != '[]' else None)
tracks_df['valid_genre'] = tracks_df.valid_genre.apply(lambda x: ast.literal_eval(x))

In [23]:
tracks_df['last_genre_id'] = tracks_df.valid_genre.apply(lambda x:x[-1] if x != None else None)

In [24]:
tracks_df.sample(20)

,track_id,track_title,valid_genre,last_genre_id
74433,114779,Сестра,"[27, 58, 103]",103
32626,50680,Crawling (Linkin Park Cover),"[10, 17, 66]",66
97060,144983,Reprise,"[10, 15, 359]",359
19706,31864,God Of Echoes Excerpt,"[1, 17, 38, 42]",42
12278,20310,In the Grotto wit Cat,"[15, 21, 468]",468
13425,22098,Raidin' The ccM Century,[19],19
89580,134602,Camellion Child,"[38, 42, 236]",236
51811,78254,Jumbled,"[15, 296, 542]",542
2982,4979,m3a,"[30, 65]",65
81902,124555,To Survive,"[15, 236, 695]",695
67363,105529,Escapism,"[1, 15, 27, 183]",183
19930,32203,Molotov Chaser,"[1, 32, 185]",185
83328,126579,Locke in Space,"[27, 94]",94
19301,31303,Autowriter + Muzzle + Genetic Drift,"[25, 31]",31
35312,54288,Torture Chile,"[12, 25]",25
95620,143050,Data,"[42, 184, 236]",236
12001,19956,Tiny Ass Bees,"[17, 38]",38
27050,41985,Cave Cave Cave,"[18, 27, 296]",296
77816,119217,1012 synth,[58],58
11403,18943,Op.4 No4 So ich traurig bin,"[1, 5]",5

In [25]:
tracks_df.dropna(inplace=True)

In [26]:
tracks_df

,track_id,track_title,valid_genre,last_genre_id
44278,66478,Ring of Five Blades,"[1, 32, 38, 41, 186, 224]",224
42864,64825,no audio+ (4/4)_remix by etc.,"[15, 32, 183]",183
23198,36713,The Little Hotel of Horrors,[22],22
16755,27586,Re Ejected,"[38, 45, 66, 98]",98
84995,128933,roof burning catastrophy,"[38, 74, 250]",250
...,...,...,...,...
16082,26549,Yagliza,"[15, 38, 514]",514
18310,29771,Act One,"[1, 38, 247]",247
7908,13787,I Think I Love You,[25],25
44028,66207,White Lines,"[38, 53, 109]",109
36871,56818,My Hearts In Your Hands,"[15, 236, 495]",495

In [27]:
tracks_df['full_genre_id'] = tracks_df.last_genre_id.progress_apply(lambda x: get_all_structure(x,genres_df)[::-1])

  0%|          | 0/62511 [00:00<?, ?it/s]

In [28]:
tracks_df.full_genre_id

44278        [38, 224]
42864        [15, 183]
23198         [38, 22]
16755         [12, 98]
84995        [38, 250]
             ...
16082        [38, 514]
18310        [38, 247]
7908          [12, 25]
44028    [12, 25, 109]
36871        [15, 495]
Name: full_genre_id, Length: 62511, dtype: object

In [29]:
tracks_df.columns

Index(['track_id', 'track_title', 'valid_genre', 'last_genre_id',
       'full_genre_id'],
      dtype='object')

In [30]:
tracks_df = tracks_df[['track_id','full_genre_id']]

In [31]:
tracks_df.full_genre_id.values

array([list([38, 224]), list([15, 183]), list([38, 22]), ...,
       list([12, 25]), list([12, 25, 109]), list([15, 495])], dtype=object)

In [32]:
tracks_df.full_genre_id.info

<bound method Series.info of 44278        [38, 224]
42864        [15, 183]
23198         [38, 22]
16755         [12, 98]
84995        [38, 250]
             ...
16082        [38, 514]
18310        [38, 247]
7908          [12, 25]
44028    [12, 25, 109]
36871        [15, 495]
Name: full_genre_id, Length: 62511, dtype: object>

In [33]:
labels_size = tracks_df.full_genre_id.apply(lambda x: len(x))

In [34]:
labels_size = int(labels_size.max())

In [35]:
type(labels_size)

int

### Parse of label to structure

In [36]:
### Function for parse label to sctructure of hierarhical scheme

def parse_label(label,label_size=5):
    # label = label.split('-')
    # preencher com 0 no caso de haver menos de 5 níveis
    labels = np.zeros(label_size,dtype=int)
    for i, label in enumerate(label):
        if i == 5:
            break
        # Aqui você pode fazer a conversão do label em um índice inteiro usando um dicionário ou outro método
        # Neste exemplo, estou apenas usando a posição da label na lista como índice
        labels[i] = label
    return labels

In [37]:
parsed_labels = tracks_df.full_genre_id.apply(lambda x: parse_label(x))

In [38]:
parsed_labels

44278     [38, 224, 0, 0, 0]
42864     [15, 183, 0, 0, 0]
23198      [38, 22, 0, 0, 0]
16755      [12, 98, 0, 0, 0]
84995     [38, 250, 0, 0, 0]
                ...
16082     [38, 514, 0, 0, 0]
18310     [38, 247, 0, 0, 0]
7908       [12, 25, 0, 0, 0]
44028    [12, 25, 109, 0, 0]
36871     [15, 495, 0, 0, 0]
Name: full_genre_id, Length: 62511, dtype: object

In [39]:
tracks_df['full_genre_id']

44278        [38, 224]
42864        [15, 183]
23198         [38, 22]
16755         [12, 98]
84995        [38, 250]
             ...
16082        [38, 514]
18310        [38, 247]
7908          [12, 25]
44028    [12, 25, 109]
36871        [15, 495]
Name: full_genre_id, Length: 62511, dtype: object

In [40]:
parsed_labels

44278     [38, 224, 0, 0, 0]
42864     [15, 183, 0, 0, 0]
23198      [38, 22, 0, 0, 0]
16755      [12, 98, 0, 0, 0]
84995     [38, 250, 0, 0, 0]
                ...
16082     [38, 514, 0, 0, 0]
18310     [38, 247, 0, 0, 0]
7908       [12, 25, 0, 0, 0]
44028    [12, 25, 109, 0, 0]
36871     [15, 495, 0, 0, 0]
Name: full_genre_id, Length: 62511, dtype: object

In [41]:
def convert_label_to_string(x,level=2,string=False):
    
    if string:
        return '-'.join([str(value) for value in x[:level+1]])
    
    return x[level]

In [42]:
tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0,string=True))
tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1,string=True))
tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2,string=True))
tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3,string=True))
tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4,string=True))

  0%|          | 0/62511 [00:00<?, ?it/s]

/tmp/ipykernel_2342026/4201371094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0,string=True))

  0%|          | 0/62511 [00:00<?, ?it/s]

/tmp/ipykernel_2342026/4201371094.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1,string=True))

  0%|          | 0/62511 [00:00<?, ?it/s]

  0%|          | 0/62511 [00:00<?, ?it/s]

  0%|          | 0/62511 [00:00<?, ?it/s]

In [43]:
# tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0))
# tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1))
# tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2))
# tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3))
# tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4))

In [44]:
tracks_df = tracks_df[tracks_df['labels_1'].isin(["38","1235"])]

In [45]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
44278,66478,"[38, 224]",38,38-224,38-224-0,38-224-0-0,38-224-0-0-0
23198,36713,"[38, 22]",38,38-22,38-22-0,38-22-0-0,38-22-0-0-0
84995,128933,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
19674,31832,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
33898,52339,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
...,...,...,...,...,...,...,...
58091,87345,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
32886,51101,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
11947,19883,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
16082,26549,"[38, 514]",38,38-514,38-514-0,38-514-0-0,38-514-0-0-0
18310,29771,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0

In [46]:
tracks_df['labels_4'].value_counts()

labels_4
38-0-0-0         3870
1235-0-0-0       3643
1235-107-0-0     2377
38-250-0-0       2032
38-247-0-0       1683
38-41-0-0        1216
38-224-0-0        847
38-32-0-0         703
38-456-0-0        507
38-47-0-0         502
38-125-0-0        430
1235-18-0-0       384
38-514-0-0        383
38-186-0-0        255
1235-18-538-0     207
38-1-0-0          178
38-6-16-763       170
38-30-0-0         155
38-22-0-0         141
38-6-360-0        124
1235-267-0-0      119
38-6-0-0           42
Name: count, dtype: int64

In [47]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0          3870
1235-0-0-0-0        3643
1235-107-0-0-0      2377
38-250-0-0-0        2032
38-247-0-0-0        1683
38-41-0-0-0         1216
38-224-0-0-0         847
38-32-0-0-0          703
38-456-0-0-0         507
38-47-0-0-0          502
38-125-0-0-0         430
1235-18-0-0-0        384
38-514-0-0-0         383
38-186-0-0-0         255
1235-18-538-0-0      207
38-1-0-0-0           178
38-30-0-0-0          155
38-22-0-0-0          141
38-6-16-763-0        126
38-6-360-0-0         124
1235-267-0-0-0       119
38-6-16-763-1193      44
38-6-0-0-0            42
Name: count, dtype: int64

In [51]:
tracks_df.to_csv(os.path.join(job_path, "tracks.csv"), index=False)

In [52]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(['3','14'])]

In [53]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
44278,66478,"[38, 224]",38,38-224,38-224-0,38-224-0-0,38-224-0-0-0
23198,36713,"[38, 22]",38,38-22,38-22-0,38-22-0-0,38-22-0-0-0
84995,128933,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
19674,31832,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
33898,52339,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
...,...,...,...,...,...,...,...
58091,87345,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
32886,51101,"[38, 250]",38,38-250,38-250-0,38-250-0-0,38-250-0-0-0
11947,19883,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
16082,26549,"[38, 514]",38,38-514,38-514-0,38-514-0-0,38-514-0-0-0
18310,29771,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0

In [54]:
categories_df = pd.DataFrame({'level1':tracks_df.labels_1.unique()})

In [55]:
categories_df = tracks_df[['labels_1','labels_2','labels_3','labels_4','labels_5']].drop_duplicates()

In [56]:
categories_df

       labels_1  labels_2     labels_3       labels_4          labels_5
44278        38    38-224     38-224-0     38-224-0-0      38-224-0-0-0
23198        38     38-22      38-22-0      38-22-0-0       38-22-0-0-0
84995        38    38-250     38-250-0     38-250-0-0      38-250-0-0-0
21905        38      38-0       38-0-0       38-0-0-0        38-0-0-0-0
34946        38    38-456     38-456-0     38-456-0-0      38-456-0-0-0
62439        38    38-125     38-125-0     38-125-0-0      38-125-0-0-0
101766     1235  1235-107   1235-107-0   1235-107-0-0    1235-107-0-0-0
74587      1235    1235-0     1235-0-0     1235-0-0-0      1235-0-0-0-0
95987        38     38-41      38-41-0      38-41-0-0       38-41-0-0-0
28975        38      38-6     38-6-360     38-6-360-0      38-6-360-0-0
88539        38    38-247     38-247-0     38-247-0-0      38-247-0-0-0
21102        38    38-186     38-186-0     38-186-0-0      38-186-0-0-0
87678        38    38-514     38-514-0     38-514-0-0      38-514-0-0-0
99544        38      38-1       38-1-0       38-1-0-0        38-1-0-0-0
23721        38     38-30      38-30-0      38-30-0-0       38-30-0-0-0
94359        38     38-32      38-32-0      38-32-0-0       38-32-0-0-0
73852      1235   1235-18    1235-18-0    1235-18-0-0     1235-18-0-0-0
59462      1235  1235-267   1235-267-0   1235-267-0-0    1235-267-0-0-0
24462        38     38-47      38-47-0      38-47-0-0       38-47-0-0-0
27140        38      38-6       38-6-0       38-6-0-0        38-6-0-0-0
26152        38      38-6      38-6-16    38-6-16-763     38-6-16-763-0
21932      1235   1235-18  1235-18-538  1235-18-538-0   1235-18-538-0-0
37685        38      38-6      38-6-16    38-6-16-763  38-6-16-763-1193

In [57]:
# categories_df['level1'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:1]))
# categories_df['level2'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:2]))
# categories_df['level3'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:3]))
# categories_df['level4'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:4]))

In [58]:
categories_df

       labels_1  labels_2     labels_3       labels_4          labels_5
44278        38    38-224     38-224-0     38-224-0-0      38-224-0-0-0
23198        38     38-22      38-22-0      38-22-0-0       38-22-0-0-0
84995        38    38-250     38-250-0     38-250-0-0      38-250-0-0-0
21905        38      38-0       38-0-0       38-0-0-0        38-0-0-0-0
34946        38    38-456     38-456-0     38-456-0-0      38-456-0-0-0
62439        38    38-125     38-125-0     38-125-0-0      38-125-0-0-0
101766     1235  1235-107   1235-107-0   1235-107-0-0    1235-107-0-0-0
74587      1235    1235-0     1235-0-0     1235-0-0-0      1235-0-0-0-0
95987        38     38-41      38-41-0      38-41-0-0       38-41-0-0-0
28975        38      38-6     38-6-360     38-6-360-0      38-6-360-0-0
88539        38    38-247     38-247-0     38-247-0-0      38-247-0-0-0
21102        38    38-186     38-186-0     38-186-0-0      38-186-0-0-0
87678        38    38-514     38-514-0     38-514-0-0      38-514-0-0-0
99544        38      38-1       38-1-0       38-1-0-0        38-1-0-0-0
23721        38     38-30      38-30-0      38-30-0-0       38-30-0-0-0
94359        38     38-32      38-32-0      38-32-0-0       38-32-0-0-0
73852      1235   1235-18    1235-18-0    1235-18-0-0     1235-18-0-0-0
59462      1235  1235-267   1235-267-0   1235-267-0-0    1235-267-0-0-0
24462        38     38-47      38-47-0      38-47-0-0       38-47-0-0-0
27140        38      38-6       38-6-0       38-6-0-0        38-6-0-0-0
26152        38      38-6      38-6-16    38-6-16-763     38-6-16-763-0
21932      1235   1235-18  1235-18-538  1235-18-538-0   1235-18-538-0-0
37685        38      38-6      38-6-16    38-6-16-763  38-6-16-763-1193

In [59]:
def get_labels_name(x,genres_df):
    levels = 5
    full_name = []
    last_level = 0
    genre_root = ""
    for genre in x.split('-'):
        genre_df = genres_df[genres_df['genre_id'] == int(genre)]
        if genre_df.empty:
            genre_name = genre_root 
        else:
            genre_name = genre_df.title.values.tolist()[0]
            genre_root = genre_name
        
        full_name.append(genre_name)
    full_name = '>'.join(full_name)
        
    return full_name
    # return genres_df[genres_df['genre_id'] == int(x)].title.values.tolist()[0]

In [60]:
categories_df['level5_name'] = categories_df.labels_5.apply(lambda x: get_labels_name(x,genres_df))

In [61]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name
44278,38,38-224,38-224-0,38-224-0-0,38-224-0-0-0,Experimental>Sound Collage>Sound Collage>Sound...
23198,38,38-22,38-22-0,38-22-0-0,38-22-0-0-0,Experimental>Audio Collage>Audio Collage>Audio...
84995,38,38-250,38-250-0,38-250-0-0,38-250-0-0-0,Experimental>Improv>Improv>Improv>Improv
21905,38,38-0,38-0-0,38-0-0-0,38-0-0-0-0,Experimental>Experimental>Experimental>Experim...
34946,38,38-456,38-456-0,38-456-0-0,38-456-0-0-0,Experimental>Minimalism>Minimalism>Minimalism>...
62439,38,38-125,38-125-0,38-125-0-0,38-125-0-0-0,Experimental>Unclassifiable>Unclassifiable>Unc...
101766,1235,1235-107,1235-107-0,1235-107-0-0,1235-107-0-0-0,Instrumental>Ambient>Ambient>Ambient>Ambient
74587,1235,1235-0,1235-0-0,1235-0-0-0,1235-0-0-0-0,Instrumental>Instrumental>Instrumental>Instrum...
95987,38,38-41,38-41-0,38-41-0-0,38-41-0-0-0,Experimental>Electroacoustic>Electroacoustic>E...
28975,38,38-6,38-6-360,38-6-360-0,38-6-360-0-0,Experimental>Novelty>Kid-Friendly>Kid-Friendly...
88539,38,38-247,38-247-0,38-247-0-0,38-247-0-0-0,Experimental>Musique Concrete>Musique Concrete...
21102,38,38-186,38-186-0,38-186-0-0,38-186-0-0-0,Experimental>Sound Poetry>Sound Poetry>Sound P...
87678,38,38-514,38-514-0,38-514-0-0,38-514-0-0-0,Experimental>Sound Art>Sound Art>Sound Art>Sou...
99544,38,38-1,38-1-0,38-1-0-0,38-1-0-0-0,Experimental>Avant-Garde>Avant-Garde>Avant-Gar...
23721,38,38-30,38-30-0,38-30-0-0,38-30-0-0-0,Experimental>Field Recordings>Field Recordings...
94359,38,38-32,38-32-0,38-32-0-0,38-32-0-0-0,Experimental>Noise>Noise>Noise>Noise
73852,1235,1235-18,1235-18-0,1235-18-0-0,1235-18-0-0-0,Instrumental>Soundtrack>Soundtrack>Soundtrack>...
59462,1235,1235-267,1235-267-0,1235-267-0-0,1235-267-0-0-0,Instrumental>New Age>New Age>New Age>New Age
24462,38,38-47,38-47-0,38-47-0-0,38-47-0-0-0,Experimental>Drone>Drone>Drone>Drone
27140,38,38-6,38-6-0,38-6-0-0,38-6-0-0-0,Experimental>Novelty>Novelty>Novelty>Novelty
26152,38,38-6,38-6-16,38-6-16-763,38-6-16-763-0,Experimental>Novelty>Sound Effects>Holiday>Hol...
21932,1235,1235-18,1235-18-538,1235-18-538-0,1235-18-538-0-0,Instrumental>Soundtrack>Compilation>Compilatio...
37685,38,38-6,38-6-16,38-6-16-763,38-6-16-763-1193,Experimental>Novelty>Sound Effects>Holiday>Chr...

In [62]:
def __create_labels__(categories_df):
    data = {
        "label1": {},
        "label2": {},
        "label3": {},
        "label4": {},
        "label5": {},
        "label1_inverse": [],
        "label2_inverse": [],
        "label3_inverse": [],
        "label4_inverse": [],
        "label5_inverse": [],
        "label1_name": {},
        "label2_name": {},
        "label3_name": {},
        "label4_name": {},
        "label5_name": {},
    }

    idx = 0
    
    for id_x, cat in enumerate(set(categories_df.labels_1.values.tolist())):
        data['label1'][cat] = idx
        data['label1_inverse'].append(cat)
        data['label1_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_2.values.tolist())):
        data['label2'][cat] = idx
        data['label2_inverse'].append(cat)
        data['label2_count'] = idx + 1
        idx+=1
        
    for id_x, cat in enumerate(set(categories_df.labels_3.values.tolist())):
        data['label3'][cat] = idx
        data['label3_inverse'].append(cat)
        data['label3_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_4.values.tolist())):
        data['label4'][cat] = idx
        data['label4_inverse'].append(cat)
        data['label4_count'] = idx + 1
        idx+=1
        
    for idx, cat in enumerate(set(categories_df.labels_5.values.tolist())):
        data['label5'][cat] = idx
        data['label5_inverse'].append(cat)
        data['label5_count'] = idx + 1
        idx+=1
        
    for cat5,cat1,cat2,cat3,cat4,name5 in categories_df.values:
        
        name1 = '>'.join(name5.split('>')[:1])
        name2 = '>'.join(name5.split('>')[:2])
        name3 = '>'.join(name5.split('>')[:3])
        name4 = '>'.join(name5.split('>')[:4])
        
        
        data['label1_name'][cat1] = name1
        data['label2_name'][cat2] = name2
        data['label3_name'][cat3] = name3
        data['label4_name'][cat4] = name4
        data['label5_name'][cat5] = name5
        
    return data

In [63]:
with open(categories_labels_path, 'w+') as f:
    f.write(json.dumps(__create_labels__(categories_df)))

In [64]:
labels  = __create_labels__(categories_df)

In [65]:
labels

{'label1': {'1235': 0, '38': 1},
 'label2': {'38-224': 2,
  '38-125': 3,
  '38-22': 4,
  '38-47': 5,
  '1235-267': 6,
  '38-250': 7,
  '1235-0': 8,
  '38-1': 9,
  '1235-18': 10,
  '38-0': 11,
  '38-456': 12,
  '38-30': 13,
  '38-186': 14,
  '38-514': 15,
  '38-41': 16,
  '1235-107': 17,
  '38-6': 18,
  '38-32': 19,
  '38-247': 20},
 'label3': {'1235-107-0': 21,
  '38-6-0': 22,
  '38-6-360': 23,
  '38-247-0': 24,
  '38-32-0': 25,
  '38-22-0': 26,
  '38-456-0': 27,
  '38-224-0': 28,
  '1235-18-0': 29,
  '38-186-0': 30,
  '38-47-0': 31,
  '38-41-0': 32,
  '38-30-0': 33,
  '38-514-0': 34,
  '1235-18-538': 35,
  '38-0-0': 36,
  '1235-0-0': 37,
  '38-125-0': 38,
  '1235-267-0': 39,
  '38-250-0': 40,
  '38-6-16': 41,
  '38-1-0': 42},
 'label4': {'38-41-0-0': 43,
  '38-250-0-0': 44,
  '38-247-0-0': 45,
  '1235-267-0-0': 46,
  '38-514-0-0': 47,
  '38-32-0-0': 48,
  '1235-18-538-0': 49,
  '38-186-0-0': 50,
  '38-30-0-0': 51,
  '1235-0-0-0': 52,
  '38-224-0-0': 53,
  '38-6-16-763': 54,
  '38-1-0-0': 55,
  '38-6-360-0': 56,
  '1235-107-0-0': 57,
  '38-6-0-0': 58,
  '1235-18-0-0': 59,
  '38-47-0-0': 60,
  '38-125-0-0': 61,
  '38-22-0-0': 62,
  '38-456-0-0': 63,
  '38-0-0-0': 64},
 'label5': {'38-22-0-0-0': 0,
  '38-1-0-0-0': 1,
  '38-0-0-0-0': 2,
  '1235-18-0-0-0': 3,
  '1235-0-0-0-0': 4,
  '38-6-0-0-0': 5,
  '38-6-16-763-1193': 6,
  '38-32-0-0-0': 7,
  '38-125-0-0-0': 8,
  '38-6-360-0-0': 9,
  '1235-18-538-0-0': 10,
  '38-47-0-0-0': 11,
  '1235-107-0-0-0': 12,
  '1235-267-0-0-0': 13,
  '38-247-0-0-0': 14,
  '38-186-0-0-0': 15,
  '38-224-0-0-0': 16,
  '38-30-0-0-0': 17,
  '38-514-0-0-0': 18,
  '38-250-0-0-0': 19,
  '38-41-0-0-0': 20,
  '38-6-16-763-0': 21,
  '38-456-0-0-0': 22},
 'label1_inverse': ['1235', '38'],
 'label2_inverse': ['38-224',
  '38-125',
  '38-22',
  '38-47',
  '1235-267',
  '38-250',
  '1235-0',
  '38-1',
  '1235-18',
  '38-0',
  '38-456',
  '38-30',
  '38-186',
  '38-514',
  '38-41',
  '1235-107',
  '38-6',
  '38-32',
  '38-247'],
 'label3_inverse': ['1235-107-0',
  '38-6-0',
  '38-6-360',
  '38-247-0',
  '38-32-0',
  '38-22-0',
  '38-456-0',
  '38-224-0',
  '1235-18-0',
  '38-186-0',
  '38-47-0',
  '38-41-0',
  '38-30-0',
  '38-514-0',
  '1235-18-538',
  '38-0-0',
  '1235-0-0',
  '38-125-0',
  '1235-267-0',
  '38-250-0',
  '38-6-16',
  '38-1-0'],
 'label4_inverse': ['38-41-0-0',
  '38-250-0-0',
  '38-247-0-0',
  '1235-267-0-0',
  '38-514-0-0',
  '38-32-0-0',
  '1235-18-538-0',
  '38-186-0-0',
  '38-30-0-0',
  '1235-0-0-0',
  '38-224-0-0',
  '38-6-16-763',
  '38-1-0-0',
  '38-6-360-0',
  '1235-107-0-0',
  '38-6-0-0',
  '1235-18-0-0',
  '38-47-0-0',
  '38-125-0-0',
  '38-22-0-0',
  '38-456-0-0',
  '38-0-0-0'],
 'label5_inverse': ['38-22-0-0-0',
  '38-1-0-0-0',
  '38-0-0-0-0',
  '1235-18-0-0-0',
  '1235-0-0-0-0',
  '38-6-0-0-0',
  '38-6-16-763-1193',
  '38-32-0-0-0',
  '38-125-0-0-0',
  '38-6-360-0-0',
  '1235-18-538-0-0',
  '38-47-0-0-0',
  '1235-107-0-0-0',
  '1235-267-0-0-0',
  '38-247-0-0-0',
  '38-186-0-0-0',
  '38-224-0-0-0',
  '38-30-0-0-0',
  '38-514-0-0-0',
  '38-250-0-0-0',
  '38-41-0-0-0',
  '38-6-16-763-0',
  '38-456-0-0-0'],
 'label1_name': {'38-224': 'Experimental',
  '38-22': 'Experimental',
  '38-250': 'Experimental',
  '38-0': 'Experimental',
  '38-456': 'Experimental',
  '38-125': 'Experimental',
  '1235-107': 'Instrumental',
  '1235-0': 'Instrumental',
  '38-41': 'Experimental',
  '38-6': 'Experimental',
  '38-247': 'Experimental',
  '38-186': 'Experimental',
  '38-514': 'Experimental',
  '38-1': 'Experimental',
  '38-30': 'Experimental',
  '38-32': 'Experimental',
  '1235-18': 'Instrumental',
  '1235-267': 'Instrumental',
  '38-47': 'Experimental'},
 'label2_name': {'38-224-0': 'Experimental>Sound Collage',
  '38-22-0': 'Experimental>Audio Collage',
  '38-250-0': 'Experimental>Improv',
  '38-0-0': 'Experimental>Experimental',
  '38-456-0': 'Experimental>Minimalism',
  '38-125-0': 'Experimental>Unclassifiable',
  '1235-107-0': 'Instrumental>Ambient',
  '1235-0-0': 'Instrumental>Instrumental',
  '38-41-0': 'Experimental>Electroacoustic',
  '38-6-360': 'Experimental>Novelty',
  '38-247-0': 'Experimental>Musique Concrete',
  '38-186-0': 'Experimental>Sound Poetry',
  '38-514-0': 'Experimental>Sound Art',
  '38-1-0': 'Experimental>Avant-Garde',
  '38-30-0': 'Experimental>Field Recordings',
  '38-32-0': 'Experimental>Noise',
  '1235-18-0': 'Instrumental>Soundtrack',
  '1235-267-0': 'Instrumental>New Age',
  '38-47-0': 'Experimental>Drone',
  '38-6-0': 'Experimental>Novelty',
  '38-6-16': 'Experimental>Novelty',
  '1235-18-538': 'Instrumental>Soundtrack'},
 'label3_name': {'38-224-0-0': 'Experimental>Sound Collage>Sound Collage',
  '38-22-0-0': 'Experimental>Audio Collage>Audio Collage',
  '38-250-0-0': 'Experimental>Improv>Improv',
  '38-0-0-0': 'Experimental>Experimental>Experimental',
  '38-456-0-0': 'Experimental>Minimalism>Minimalism',
  '38-125-0-0': 'Experimental>Unclassifiable>Unclassifiable',
  '1235-107-0-0': 'Instrumental>Ambient>Ambient',
  '1235-0-0-0': 'Instrumental>Instrumental>Instrumental',
  '38-41-0-0': 'Experimental>Electroacoustic>Electroacoustic',
  '38-6-360-0': 'Experimental>Novelty>Kid-Friendly',
  '38-247-0-0': 'Experimental>Musique Concrete>Musique Concrete',
  '38-186-0-0': 'Experimental>Sound Poetry>Sound Poetry',
  '38-514-0-0': 'Experimental>Sound Art>Sound Art',
  '38-1-0-0': 'Experimental>Avant-Garde>Avant-Garde',
  '38-30-0-0': 'Experimental>Field Recordings>Field Recordings',
  '38-32-0-0': 'Experimental>Noise>Noise',
  '1235-18-0-0': 'Instrumental>Soundtrack>Soundtrack',
  '1235-267-0-0': 'Instrumental>New Age>New Age',
  '38-47-0-0': 'Experimental>Drone>Drone',
  '38-6-0-0': 'Experimental>Novelty>Novelty',
  '38-6-16-763': 'Experimental>Novelty>Sound Effects',
  '1235-18-538-0': 'Instrumental>Soundtrack>Compilation'},
 'label4_name': {'38-224-0-0-0': 'Experimental>Sound Collage>Sound Collage>Sound Collage',
  '38-22-0-0-0': 'Experimental>Audio Collage>Audio Collage>Audio Collage',
  '38-250-0-0-0': 'Experimental>Improv>Improv>Improv',
  '38-0-0-0-0': 'Experimental>Experimental>Experimental>Experimental',
  '38-456-0-0-0': 'Experimental>Minimalism>Minimalism>Minimalism',
  '38-125-0-0-0': 'Experimental>Unclassifiable>Unclassifiable>Unclassifiable',
  '1235-107-0-0-0': 'Instrumental>Ambient>Ambient>Ambient',
  '1235-0-0-0-0': 'Instrumental>Instrumental>Instrumental>Instrumental',
  '38-41-0-0-0': 'Experimental>Electroacoustic>Electroacoustic>Electroacoustic',
  '38-6-360-0-0': 'Experimental>Novelty>Kid-Friendly>Kid-Friendly',
  '38-247-0-0-0': 'Experimental>Musique Concrete>Musique Concrete>Musique Concrete',
  '38-186-0-0-0': 'Experimental>Sound Poetry>Sound Poetry>Sound Poetry',
  '38-514-0-0-0': 'Experimental>Sound Art>Sound Art>Sound Art',
  '38-1-0-0-0': 'Experimental>Avant-Garde>Avant-Garde>Avant-Garde',
  '38-30-0-0-0': 'Experimental>Field Recordings>Field Recordings>Field Recordings',
  '38-32-0-0-0': 'Experimental>Noise>Noise>Noise',
  '1235-18-0-0-0': 'Instrumental>Soundtrack>Soundtrack>Soundtrack',
  '1235-267-0-0-0': 'Instrumental>New Age>New Age>New Age',
  '38-47-0-0-0': 'Experimental>Drone>Drone>Drone',
  '38-6-0-0-0': 'Experimental>Novelty>Novelty>Novelty',
  '38-6-16-763-0': 'Experimental>Novelty>Sound Effects>Holiday',
  '1235-18-538-0-0': 'Instrumental>Soundtrack>Compilation>Compilation',
  '38-6-16-763-1193': 'Experimental>Novelty>Sound Effects>Holiday'},
 'label5_name': {'38': 'Experimental>Novelty>Sound Effects>Holiday>Christmas',
  '1235': 'Instrumental>Soundtrack>Compilation>Compilation>Compilation'},
 'label1_count': 2,
 'label2_count': 21,
 'label3_count': 43,
 'label4_count': 65,
 'label5_count': 23}

In [66]:
categories_df['labels_1_'] = categories_df.labels_1.apply(lambda x: labels['label1'].get(x))
categories_df['labels_2_'] = categories_df.labels_2.apply(lambda x: labels['label2'].get(x))
categories_df['labels_3_'] = categories_df.labels_3.apply(lambda x: labels['label3'].get(x))
categories_df['labels_4_'] = categories_df.labels_4.apply(lambda x: labels['label4'].get(x))
categories_df['labels_5_'] = categories_df.labels_5.apply(lambda x: labels['label5'].get(x))

In [67]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name,labels_1_,labels_2_,labels_3_,labels_4_,labels_5_
44278,38,38-224,38-224-0,38-224-0-0,38-224-0-0-0,Experimental>Sound Collage>Sound Collage>Sound...,1,2,28,53,16
23198,38,38-22,38-22-0,38-22-0-0,38-22-0-0-0,Experimental>Audio Collage>Audio Collage>Audio...,1,4,26,62,0
84995,38,38-250,38-250-0,38-250-0-0,38-250-0-0-0,Experimental>Improv>Improv>Improv>Improv,1,7,40,44,19
21905,38,38-0,38-0-0,38-0-0-0,38-0-0-0-0,Experimental>Experimental>Experimental>Experim...,1,11,36,64,2
34946,38,38-456,38-456-0,38-456-0-0,38-456-0-0-0,Experimental>Minimalism>Minimalism>Minimalism>...,1,12,27,63,22
62439,38,38-125,38-125-0,38-125-0-0,38-125-0-0-0,Experimental>Unclassifiable>Unclassifiable>Unc...,1,3,38,61,8
101766,1235,1235-107,1235-107-0,1235-107-0-0,1235-107-0-0-0,Instrumental>Ambient>Ambient>Ambient>Ambient,0,17,21,57,12
74587,1235,1235-0,1235-0-0,1235-0-0-0,1235-0-0-0-0,Instrumental>Instrumental>Instrumental>Instrum...,0,8,37,52,4
95987,38,38-41,38-41-0,38-41-0-0,38-41-0-0-0,Experimental>Electroacoustic>Electroacoustic>E...,1,16,32,43,20
28975,38,38-6,38-6-360,38-6-360-0,38-6-360-0-0,Experimental>Novelty>Kid-Friendly>Kid-Friendly...,1,18,23,56,9
88539,38,38-247,38-247-0,38-247-0-0,38-247-0-0-0,Experimental>Musique Concrete>Musique Concrete...,1,20,24,45,14
21102,38,38-186,38-186-0,38-186-0-0,38-186-0-0-0,Experimental>Sound Poetry>Sound Poetry>Sound P...,1,14,30,50,15
87678,38,38-514,38-514-0,38-514-0-0,38-514-0-0-0,Experimental>Sound Art>Sound Art>Sound Art>Sou...,1,15,34,47,18
99544,38,38-1,38-1-0,38-1-0-0,38-1-0-0-0,Experimental>Avant-Garde>Avant-Garde>Avant-Gar...,1,9,42,55,1
23721,38,38-30,38-30-0,38-30-0-0,38-30-0-0-0,Experimental>Field Recordings>Field Recordings...,1,13,33,51,17
94359,38,38-32,38-32-0,38-32-0-0,38-32-0-0-0,Experimental>Noise>Noise>Noise>Noise,1,19,25,48,7
73852,1235,1235-18,1235-18-0,1235-18-0-0,1235-18-0-0-0,Instrumental>Soundtrack>Soundtrack>Soundtrack>...,0,10,29,59,3
59462,1235,1235-267,1235-267-0,1235-267-0-0,1235-267-0-0-0,Instrumental>New Age>New Age>New Age>New Age,0,6,39,46,13
24462,38,38-47,38-47-0,38-47-0-0,38-47-0-0-0,Experimental>Drone>Drone>Drone>Drone,1,5,31,60,11
27140,38,38-6,38-6-0,38-6-0-0,38-6-0-0-0,Experimental>Novelty>Novelty>Novelty>Novelty,1,18,22,58,5
26152,38,38-6,38-6-16,38-6-16-763,38-6-16-763-0,Experimental>Novelty>Sound Effects>Holiday>Hol...,1,18,41,54,21
21932,1235,1235-18,1235-18-538,1235-18-538-0,1235-18-538-0-0,Instrumental>Soundtrack>Compilation>Compilatio...,0,10,35,49,10
37685,38,38-6,38-6-16,38-6-16-763,38-6-16-763-1193,Experimental>Novelty>Sound Effects>Holiday>Chr...,1,18,41,54,6

In [68]:
unique_labels_1 = categories_df['labels_1_'].unique().tolist()
unique_labels_2 = categories_df['labels_2_'].unique().tolist()
unique_labels_3 = categories_df['labels_3_'].unique().tolist()
unique_labels_4 = categories_df['labels_4_'].unique().tolist()
unique_labels_5 = categories_df['labels_5_'].unique().tolist()

In [69]:
unique_labels_1

[1, 0]

In [70]:
num_nodes_per_level = [len(unique_labels_1), len(unique_labels_2), len(unique_labels_3), len(unique_labels_4), len(unique_labels_5)]

In [71]:

# num_classes_per_node = [
#     [5, 4, 6],  # Nível 1: 3 nós com 5, 4 e 6 classes
#     [3, 2, 4, 5],  # Nível 2: 4 nós com 3, 2, 4 e 5 classes
#     [4, 3, 5, 2, 6],  # Nível 3: 5 nós com 4, 3, 5, 2 e 6 classes
#     [2, 3, 4, 5, 3, 2],  # Nível 4: 6 nós com 2, 3, 4, 5, 3 e 2 classes
#     [5, 6, 3, 4, 2, 3, 4],  # Nível 5: 7 nós com 5, 6, 3, 4, 2, 3 e 4 classes
#

In [72]:
# num_classes_per_node.append(unique_labels_1)  # Nível 1

In [73]:
# Cálculo de num_classes_per_node

In [74]:
level_1 = categories_df[['labels_1_','labels_2_']].groupby('labels_1_').count()['labels_2_'].values.tolist()

In [75]:
level_2 = categories_df[['labels_2_','labels_3_']].groupby('labels_2_').count()['labels_3_'].values.tolist()

In [76]:
level_3 = categories_df[['labels_3_','labels_4_']].groupby('labels_3_').count()['labels_4_'].values.tolist()

In [77]:
level_4 = categories_df[['labels_4_','labels_5_']].groupby('labels_4_').count()['labels_5_'].values.tolist()

In [78]:
level_5 = unique_labels_5

In [79]:
len(unique_labels_5)

23

In [80]:
num_classes_per_node = [level_1,level_2,level_3,level_4,level_5]

In [81]:
print("num_nodes_per_level:", num_nodes_per_level[0])

num_nodes_per_level: 2

In [82]:
labels['label5']

{'38-22-0-0-0': 0,
 '38-1-0-0-0': 1,
 '38-0-0-0-0': 2,
 '1235-18-0-0-0': 3,
 '1235-0-0-0-0': 4,
 '38-6-0-0-0': 5,
 '38-6-16-763-1193': 6,
 '38-32-0-0-0': 7,
 '38-125-0-0-0': 8,
 '38-6-360-0-0': 9,
 '1235-18-538-0-0': 10,
 '38-47-0-0-0': 11,
 '1235-107-0-0-0': 12,
 '1235-267-0-0-0': 13,
 '38-247-0-0-0': 14,
 '38-186-0-0-0': 15,
 '38-224-0-0-0': 16,
 '38-30-0-0-0': 17,
 '38-514-0-0-0': 18,
 '38-250-0-0-0': 19,
 '38-41-0-0-0': 20,
 '38-6-16-763-0': 21,
 '38-456-0-0-0': 22}

In [83]:
labels['label1_count']

2

In [84]:


def parse_tfr_element(element):
    #use the same structure as above; it's kinda an outline of the structure we now want to create
    data = {
        'emb' : tf.io.FixedLenFeature([], tf.string),
        'track_id' : tf.io.FixedLenFeature([], tf.int64),
    }
    
    content = tf.io.parse_single_example(element, data)

    track_id = content['track_id']
    emb = content['emb']
    

    #get our 'feature'-- our image -- and reshape it appropriately
    feature = tf.io.parse_tensor(emb, out_type=tf.float32)
    return (feature, track_id)


def get_dataset(filename):
    #create the dataset
    dataset = tf.data.TFRecordDataset(filename)

    #pass every single feature through our mapping function
    dataset = dataset.map(
        parse_tfr_element
    )

    return dataset

In [85]:
import numpy as np


def load_dataset(path,dataset=args.embeddings):
    tfrecords_path = os.path.join(path,'tfrecords',dataset)
    
    
    tfrecords_path = [os.path.join(tfrecords_path,path) for path in os.listdir(tfrecords_path)]
    dataset = get_dataset(tfrecords_path)
    
    df = pd.DataFrame(
        dataset.as_numpy_iterator(),
        columns=['feature', 'track_id']
    )
        
    df.dropna(inplace=True)
    
    
    try:
        df.feature = df.feature.apply(lambda x: x[0] if x.shape[0] != 0 else None)
    except:
        print(x)
    
    return df

In [86]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0          3870
1235-0-0-0-0        3643
1235-107-0-0-0      2377
38-250-0-0-0        2032
38-247-0-0-0        1683
38-41-0-0-0         1216
38-224-0-0-0         847
38-32-0-0-0          703
38-456-0-0-0         507
38-47-0-0-0          502
38-125-0-0-0         430
1235-18-0-0-0        384
38-514-0-0-0         383
38-186-0-0-0         255
1235-18-538-0-0      207
38-1-0-0-0           178
38-30-0-0-0          155
38-22-0-0-0          141
38-6-16-763-0        126
38-6-360-0-0         124
1235-267-0-0-0       119
38-6-16-763-1193      44
38-6-0-0-0            42
Name: count, dtype: int64

In [87]:
def __split_data__(group, percentage=0.1):
    if len(group) == 1:
        return group, group

    shuffled = shuffle(group.values)
    finish_test = int(ceil(len(group) * percentage))

    first = pd.DataFrame(shuffled[:finish_test], columns=group.columns)
    second = pd.DataFrame(shuffled[finish_test:], columns=group.columns)

    return first, second

In [88]:
def select_dataset(tracks_df):
    
#     dataset_testset_path = os.path.join(tfrecord_path,'test')
#     dataset_validationset_path = os.path.join(tfrecord_path,'val')
#     dataset_trainset_path = os.path.join(tfrecord_path,'train')
    
    df = load_dataset(args.dataset_path,dataset=args.embeddings)
    
    df.dropna(inplace=True)
    
    tracks_df = tracks_df.merge(df, on='track_id')
    
    tracks_df.loc[:,'labels_1'] = tracks_df.labels_1.astype(str).progress_apply(lambda x: labels['label1'][x])
    tracks_df.loc[:,'labels_2'] = tracks_df.labels_2.astype(str).progress_apply(lambda x: labels['label2'][x])
    tracks_df.loc[:,'labels_3'] = tracks_df.labels_3.astype(str).progress_apply(lambda x: labels['label3'][x])
    tracks_df.loc[:,'labels_4'] = tracks_df.labels_4.astype(str).progress_apply(lambda x: labels['label4'][x])
    tracks_df.loc[:,'labels_5'] = tracks_df.labels_5.astype(str).progress_apply(lambda x: labels['label5'][x])
    
    tests = []
    trains = []
    validations = []
    groups = tracks_df.groupby("labels_5")
    
    
    count = 0
    items_count = 0
    total = len(groups)
    total_items = len(tracks_df)
    oversampling_size = 30  # int(group_sizes.mean() + group_sizes.std() * 2)
    print(f"oversampling_size: {oversampling_size}")

    for code, group in groups:
        test, train_to_split = __split_data__(group, 0.01)  # 10%
        train_to_split = train_to_split
        validation, train = __split_data__(train_to_split, 0.01)  # %1

        tests.append(test)
        validations.append(validation)

        ## this increase the numner of samples when classes has low quantity
        count_train = len(train)
        if count_train < oversampling_size:
            train = train.sample(oversampling_size, replace=True)

        trains.append(train)

        count += 1
        items_count += count_train
        
        
    df_test = pd.concat(tests, sort=False).sample(frac=1).reset_index(drop=True)
    # .to_csv(dataset_testset_path, index=False,quoting=csv.QUOTE_ALL)
    df_val = pd.concat(validations, sort=False).sample(frac=1).reset_index(drop=True)
    df_train = pd.concat(trains, sort=False).sample(frac=1).reset_index(drop=True)

    return df_train,df_test,df_val

In [89]:
df_train,df_test,df_val = select_dataset(tracks_df)

2023-07-31 10:30:00.793865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7940 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5
2023-07-31 10:30:01.445018: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [11]
	 [[{{node Placeholder/_0}}]]

  0%|          | 0/19967 [00:00<?, ?it/s]

  0%|          | 0/19967 [00:00<?, ?it/s]

  0%|          | 0/19967 [00:00<?, ?it/s]

  0%|          | 0/19967 [00:00<?, ?it/s]

  0%|          | 0/19967 [00:00<?, ?it/s]

oversampling_size: 30

In [90]:
df_val

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5,feature
0,114795,[1235],0,8,37,52,4,"[0.016593704, 0.015862823, 0.0044886866, 0.030..."
1,39726,"[38, 186]",1,14,30,50,15,"[0.039444953, -0.043653715, -0.062364798, -0.0..."
2,97648,"[38, 250]",1,7,40,44,19,"[-0.047725707, 0.0043878355, -0.03596167, -0.0..."
3,144846,[1235],0,8,37,52,4,"[0.12847733, -0.0060103633, -0.0140334265, -0...."
4,148474,[1235],0,8,37,52,4,"[-0.020786962, -0.00889197, 0.016376913, -0.02..."
...,...,...,...,...,...,...,...,...
206,7757,[38],1,11,36,64,2,"[0.1901205, 0.14213206, 0.1833603, 0.07032164,..."
207,146206,[1235],0,8,37,52,4,"[0.033531774, -0.013014853, 0.083888225, -0.07..."
208,132645,[38],1,11,36,64,2,"[-0.01420936, -0.03755947, 0.0057360926, -0.01..."
209,132016,"[38, 250]",1,7,40,44,19,"[0.06576564, 0.027689973, -0.0141931875, 0.083..."
210,138260,"[38, 224]",1,2,28,53,16,"[0.0047569773, 0.046529543, 0.019599756, -0.00..."

In [91]:
df_train

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5,feature
0,149442,[1235],0,8,37,52,4,"[-0.016682109, 0.052489776, -0.024545709, 0.00..."
1,145078,[1235],0,8,37,52,4,"[0.042950165, -0.027086437, -0.06165093, 0.010..."
2,2020,"[38, 1]",1,9,42,55,1,"[0.21460687, -0.027293384, -0.0021596253, 0.05..."
3,114552,"[38, 250]",1,7,40,44,19,"[0.03263877, 0.0066171885, 0.0021464825, -0.02..."
4,17122,[38],1,11,36,64,2,"[-0.03254533, -0.10326264, 0.019267598, -0.101..."
...,...,...,...,...,...,...,...,...
19538,118984,"[38, 224]",1,2,28,53,16,"[-0.016241243, -0.0091634095, -0.042106967, 0...."
19539,58351,"[1235, 107]",0,17,21,57,12,"[0.011396567, 0.014954507, 0.025803288, 0.0451..."
19540,35169,"[38, 250]",1,7,40,44,19,"[0.057587992, 0.00639081, -0.03639846, 0.12843..."
19541,39867,"[38, 224]",1,2,28,53,16,"[0.08586556, -0.0125486255, -0.0041458807, 0.0..."
19542,155048,[38],1,11,36,64,2,"[0.00013902783, -0.009935538, 0.09224484, -0.0..."


### labels locais por cada nível

local_labels_node5:
   index | local_labels
   0     | [20, 22, 25]  # Nós locais para o nó 1 no nível 5 no primeiro exemplo
   1     | [21, 23, 24, 26]  # Nós locais para o nó 1 no nível 5 no segundo exemplo
   ...   | ...
   n     | [23, 25, 27]  # Nós locais para o nó 1 no nível 5 no n-ésimo exemplo

In [92]:
def _bytes_feature(value):
  ### Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))): # if value ist tensor
        value = value.numpy() # get value of tensor
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def _float_feature(value):
  ### Returns a floast_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64List_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def _int64_feature(value):
  ###  Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def serialize_array(array):
    array = tf.io.serialize_tensor(array)
    return array

In [93]:
def parse_single_music(data,labels):
    track_id, _, cat1, cat2, cat3, cat4, cat5, music = data
    
    
    label1 = np.array([cat1, labels['label1_count']], np.int64)
    label2 = np.array([cat2, labels['label2_count']], np.int64)
    label3 = np.array([cat3, labels['label3_count']], np.int64)
    label4 = np.array([cat4, labels['label4_count']], np.int64)
    label5 = np.array([cat5, labels['label5_count']], np.int64)
    
    
    
    #define the dictionary -- the structure -- of our single example
    data = {
        'label1': _int64List_feature(label1),
        'label2': _int64List_feature(label2),
        'label3': _int64List_feature(label3),
        'label4': _int64List_feature(label4),
        'label5': _int64List_feature(label5),
        # 'features' : _bytes_feature(serialize_array(music)),
        'features' : _float_feature(music),
        'track_id' : _int64_feature(track_id)
    }
    #create an Example, wrapping the single features
    out = tf.train.Example(features=tf.train.Features(feature=data))

    return out

In [94]:
def generate_tf_record(df,tf_path='val'):
    create_dir(tf_path)
    
    
    batch_size = 1024 * 50 # 50k records from each file batch
    count = 0
    total = math.ceil(len(df) / batch_size)

    for i in range(0, len(df), batch_size):
        batch_df = df[i:i+batch_size]
        
        tfrecords = [parse_single_music(data, labels) for data in batch_df.values]
        
        path = f"{tf_path}/{str(count).zfill(10)}.tfrecord"
        
        #with tf.python_io.TFRecordWriter(path) as writer:
        with tf.io.TFRecordWriter(path) as writer:
            for tfrecord in tfrecords:
                writer.write(tfrecord.SerializeToString())

        print(f"{count} {len(tfrecords)} {path}")
        count += 1
        print(f"{count}/{total} batchs / {count * batch_size} processed")

    print(f"{count}/{total} batchs / {len(df)} processed")
    
    return tf_path

In [95]:
tfrecord_path

'/mnt/disks/data/fma/trains/hierarchical_local_partial/tfrecords'

In [96]:
val_path = generate_tf_record(df_val,tf_path=os.path.join(tfrecord_path,'val'))

0 211 /mnt/disks/data/fma/trains/hierarchical_local_partial/tfrecords/val/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 211 processed

In [97]:
test_path = generate_tf_record(df_test,tf_path=os.path.join(tfrecord_path,'test'))

0 213 /mnt/disks/data/fma/trains/hierarchical_local_partial/tfrecords/test/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 213 processed

In [98]:
train_path = generate_tf_record(df_train,tf_path=os.path.join(tfrecord_path,'train'))

0 19543 /mnt/disks/data/fma/trains/hierarchical_local_partial/tfrecords/train/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 19543 processed

In [99]:
def create_metadata(metadata_path):

    with open(metadata_path, 'w+') as f:
        f.write(json.dumps({
            'sequence_size': args.sequence_size,
            'n_levels': labels_size,
            'num_nodes_per_level':num_nodes_per_level,
            'num_classes_per_node':num_classes_per_node,
            'labels_size': [labels['label1_count'],labels['label2_count'],
                           labels['label3_count'],labels['label4_count'],
                           labels['label5_count']],
            'val_path': val_path,
            'train_path': train_path,
            'test_path': test_path,
            'trainset_count': len(df_train),
            'validationset_count': len(df_val),
            'testset_count': len(df_test)
        }))

In [100]:
num_nodes_per_level

[2, 19, 22, 22, 23]

In [101]:
create_metadata(metadata_path)

In [102]:
job_path

'/mnt/disks/data/fma/trains/hierarchical_local_partial'

In [103]:
tracks_df.to_csv(os.path.join(job_path,"tracks.csv"),index=False)

In [104]:
with open(categories_labels_path, 'r') as f:
    labels = json.loads(f.read())

In [105]:
with open(metadata_path, 'r') as f:
    metadata = json.loads(f.read())

In [106]:
levels_size = {'level1_size': labels['label1_count']-1,
        'level2_size': labels['label2_count']-1,
        'level3_size': labels['label3_count']-1,
        'level4_size': labels['label4_count']-1,
        'level5_size': labels['label5_count']-1}

In [107]:
levels_size['level1_size']

1

In [108]:
len(metadata['num_nodes_per_level'])

5

In [109]:
len(metadata['num_classes_per_node'])

5