In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import json
import ast
import os
import csv
import math
from sklearn.utils import shuffle
from math import ceil
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm

2023-06-30 14:47:05.727180: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-30 14:47:06.258975: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
tqdm.pandas()

In [3]:

args = pd.Series({
    "root_dir":"/mnt/disks/data/",
    "dataset_path":"/mnt/disks/data/fma/fma_large",
    "embeddings":"music_style",
    "sequence_size": 1280,
    "train_id": "hierarchical_local_sample",
    'sample_size': 0.1
})

In [4]:

base_path = "/mnt/disks/data/fma/trains"


job_path = os.path.join(base_path,args.train_id)


tfrecord_path = os.path.join(job_path,"tfrecords")

# In[16]:

base_path = os.path.join(args.root_dir,"fma")

# In[17]:

models_path = os.path.join(args.root_dir,"models")


metadata_path_fma = os.path.join(base_path,"fma_metadata")

# In[18]:

metadata_path = os.path.join(job_path,"metadata.json")


categories_labels_path = os.path.join(job_path,"labels.json")

In [5]:


def __load_json__(path):
    with open(path, 'r') as f:
        tmp = json.loads(f.read())

    return tmp

In [6]:

def create_dir(path):
    # checking if the directory demo_folder2 
    # exist or not.
    if not os.path.isdir(path):

        # if the demo_folder2 directory is 
        # not present then create it.
        os.makedirs(path)
    return True

In [7]:
import shutil
shutil.rmtree(job_path)

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disks/data/fma/trains/hierarchical_local_sample'

In [9]:
create_dir(job_path)

True

## Load genres file. Contains relationships beetwen genres

In [10]:
genres_df = pd.read_csv(os.path.join(metadata_path_fma,'genres.csv'))

In [11]:
genres_df

     genre_id  #tracks  parent          title  top_level
0           1     8693      38    Avant-Garde         38
1           2     5271       0  International          2
2           3     1752       0          Blues          3
3           4     4126       0           Jazz          4
4           5     4106       0      Classical          5
..        ...      ...     ...            ...        ...
158      1032       60     102        Turkish          2
159      1060       30      46          Tango          2
160      1156       26     130           Fado          2
161      1193       72     763      Christmas         38
162      1235    14938       0   Instrumental       1235

[163 rows x 5 columns]

In [12]:
genres_df[genres_df['genre_id'] == 495]

     genre_id  #tracks  parent      title  top_level
136       495     2061      15  Downtempo         15

In [36]:
# Cria um dicionário que associa o ID de cada música aos IDs de seus gêneros musicais
tracks_df = pd.read_csv(os.path.join(metadata_path_fma,'tracks_valid.csv'))

In [37]:
tracks_df = tracks_df.sample(frac=args.sample_size)

In [38]:
tracks_df.sample(20)

,track_id,track_title,valid_genre
89212,134108,Lost Memories,"['15', '811', '1235']"
47387,71130,Passing Time With Burst Of Erraticness,"['1', '4', '38']"
7611,13419,Outdoor art class,"['27', '66', '71', '250']"
13500,22204,Let It Slide,"['10', '27']"
97799,145929,Industrialence #11,"['38', '107']"
104014,155084,All Your Faustian Bargains,"['15', '76', '1235']"
16257,26752,Acrylic on Cardboard 2,['76']
54064,82117,Interlude vol.1,"['240', '542']"
5420,10375,Torturing Mantra,"['32', '38', '224']"
48755,72869,Scorpio Weather Cult / Who Walked All Night......,"['15', '224']"
32653,50748,Insane We're Not Lovers,"['88', '314']"
23935,37788,collectif aposcaphe 2008,['38']
60361,92194,Already There (No Vocals),"['12', '17', '103']"
78538,120076,Somewhere In Space,"['12', '15']"
29058,44898,Smoking On An Empty Stomach,"['10', '27', '103']"
95189,142514,Voices: Part II,['65']
78917,120545,I Smell A Rat,"['25', '85']"
63316,97132,[Petroglyph170] Klopenn (The Cure Of Folly) - ...,"['38', '42']"
20831,33344,104_Tibeef_phonqué,"['15', '21', '468']"
51912,78968,Gangstarr feat Nice & Smooth-Dwyck,['21']

In [39]:
tracks_df.valid_genre.values

array(["['21']", "['15', '32', '47', '107', '247']",
       "['15', '236', '495']", ..., "['17']", "['15']",
       "['15', '21', '100']"], dtype=object)

In [40]:
tracks_df.track_title

9572                                Thought You Knew
44227                  Field recording from Thailand
74375                                Go Cannibalism!
26960                                    09-TooEarly
6929                                     PhantomLimb
                            ...
84444                                             15
71800                      You Doubt it, You're Dead
317      I Don't Need Water Sprinklers In The Desert
83371                                 Human Behavior
32452                                    Escapewheel
Name: track_title, Length: 10419, dtype: object

In [41]:
## Get complete genre structure
def get_all_structure(estrutura,df_genres):
    ## Get structure from df_genres
    def get_all_structure_from_df(estrutura,df_genres,structure=[]):
        if estrutura == 0:
            return structure
        else:
            structure.append(int(estrutura))
            get_all_structure_from_df(df_genres[df_genres["genre_id"]==int(estrutura)].parent.values[0],df_genres,structure)
            return structure
    
    return get_all_structure_from_df(estrutura,df_genres,structure=[])

In [42]:
# tracks_df['valid_genre'] = tracks_df.track_genres.apply(lambda x: x.strip('][').split(', ') if x != '[]' else None)
tracks_df['valid_genre'] = tracks_df.valid_genre.apply(lambda x: ast.literal_eval(x))

In [43]:
tracks_df['last_genre_id'] = tracks_df.valid_genre.apply(lambda x:x[-1] if x != None else None)

In [44]:
tracks_df.sample(20)

,track_id,track_title,valid_genre,last_genre_id
68953,107634,Bags of Water (Instrumental Version),"[10, 17, 103]",103
40348,61443,Girl Called Trouble (Retrigger Remix),[185],185
19354,31379,Everybody Stopped Calling Me (Just Plain Ant R...,"[15, 66]",66
38706,59203,07 Heures,"[32, 77]",77
29479,45471,Saturday Night Movie,"[1, 15, 32, 38, 41, 47, 107, 125, 184]",184
32609,50652,Desperato,"[45, 58]",58
96414,144007,12 Drive By Fires,"[15, 17, 41]",41
99857,148588,L'amour & ...,[10],10
2815,4785,I Know How It Feels...Bad,[12],12
19261,31231,Inscrição,"[1, 2, 17, 41, 103, 171, 186]",186
63309,97125,[zen097] Kamil Kowalczyk (Magma) - 04.Untitled IV,"[38, 42]",42
82990,126102,Conscience Down,[10],10
63939,97968,ORG_ose,[15],15
4271,8581,Basie/Wisdom,[4],4
90991,136790,Life Of The Tribe,"[15, 400, 1235]",1235
52416,79884,BugaBlue,"[3, 4, 179]",179
82071,124781,No Sax For Joey,"[286, 337, 542]",542
83010,126124,NewYorican,"[12, 38, 1235]",1235
15608,25649,Inner City Drug Use,"[7, 83]",83
82429,125217,The Corner Man,"[3, 12]",12

In [45]:
tracks_df.dropna(inplace=True)

In [46]:
tracks_df

,track_id,track_title,valid_genre,last_genre_id
9572,16164,Thought You Knew,[21],21
44227,66426,Field recording from Thailand,"[15, 32, 47, 107, 247]",247
74375,114659,Go Cannibalism!,"[15, 236, 495]",495
26960,41881,09-TooEarly,"[27, 101]",101
6929,12427,PhantomLimb,"[15, 32, 38, 42, 107, 184]",184
...,...,...,...,...
84444,128042,15,"[17, 30, 92]",92
71800,111464,"You Doubt it, You're Dead","[1, 30, 38, 41, 247]",247
317,537,I Don't Need Water Sprinklers In The Desert,[17],17
83371,126623,Human Behavior,[15],15
32452,50436,Escapewheel,"[15, 21, 100]",100

In [47]:
tracks_df['full_genre_id'] = tracks_df.last_genre_id.progress_apply(lambda x: get_all_structure(x,genres_df)[::-1])

  0%|          | 0/10419 [00:00<?, ?it/s]

In [48]:
tracks_df.full_genre_id

9572              [21]
44227        [38, 247]
74375        [15, 495]
26960    [12, 31, 101]
6929         [15, 184]
             ...
84444          [2, 92]
71800        [38, 247]
317               [17]
83371             [15]
32452        [21, 100]
Name: full_genre_id, Length: 10419, dtype: object

In [49]:
tracks_df.columns

Index(['track_id', 'track_title', 'valid_genre', 'last_genre_id',
       'full_genre_id'],
      dtype='object')

In [50]:
tracks_df = tracks_df[['track_id','full_genre_id']]

In [51]:
tracks_df.full_genre_id.values

array([list([21]), list([38, 247]), list([15, 495]), ..., list([17]),
       list([15]), list([21, 100])], dtype=object)

In [52]:
tracks_df.full_genre_id.info

<bound method Series.info of 9572              [21]
44227        [38, 247]
74375        [15, 495]
26960    [12, 31, 101]
6929         [15, 184]
             ...
84444          [2, 92]
71800        [38, 247]
317               [17]
83371             [15]
32452        [21, 100]
Name: full_genre_id, Length: 10419, dtype: object>

In [53]:
labels_size = tracks_df.full_genre_id.apply(lambda x: len(x))

In [54]:
labels_size = int(labels_size.max())

In [55]:
type(labels_size)

int

### Parse of label to structure

In [56]:
### Function for parse label to sctructure of hierarhical scheme

def parse_label(label,label_size=5):
    # label = label.split('-')
    # preencher com 0 no caso de haver menos de 5 níveis
    labels = np.zeros(label_size,dtype=int)
    for i, label in enumerate(label):
        if i == 5:
            break
        # Aqui você pode fazer a conversão do label em um índice inteiro usando um dicionário ou outro método
        # Neste exemplo, estou apenas usando a posição da label na lista como índice
        labels[i] = label
    return labels

In [57]:
parsed_labels = tracks_df.full_genre_id.apply(lambda x: parse_label(x))

In [58]:
parsed_labels

9572        [21, 0, 0, 0, 0]
44227     [38, 247, 0, 0, 0]
74375     [15, 495, 0, 0, 0]
26960    [12, 31, 101, 0, 0]
6929      [15, 184, 0, 0, 0]
                ...
84444       [2, 92, 0, 0, 0]
71800     [38, 247, 0, 0, 0]
317         [17, 0, 0, 0, 0]
83371       [15, 0, 0, 0, 0]
32452     [21, 100, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [59]:
tracks_df['full_genre_id']

9572              [21]
44227        [38, 247]
74375        [15, 495]
26960    [12, 31, 101]
6929         [15, 184]
             ...
84444          [2, 92]
71800        [38, 247]
317               [17]
83371             [15]
32452        [21, 100]
Name: full_genre_id, Length: 10419, dtype: object

In [60]:
parsed_labels

9572        [21, 0, 0, 0, 0]
44227     [38, 247, 0, 0, 0]
74375     [15, 495, 0, 0, 0]
26960    [12, 31, 101, 0, 0]
6929      [15, 184, 0, 0, 0]
                ...
84444       [2, 92, 0, 0, 0]
71800     [38, 247, 0, 0, 0]
317         [17, 0, 0, 0, 0]
83371       [15, 0, 0, 0, 0]
32452     [21, 100, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [101]:
def convert_label_to_string(x,level=2,string=False):
    
    if string:
        return '-'.join([str(value) for value in x[:level+1]])
    
    return x[level]

In [102]:
tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0,string=True))
tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1,string=True))
tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2,string=True))
tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3,string=True))
tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4,string=True))

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

In [82]:
tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0))
tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1))
tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2))
tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3))
tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4))

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

In [83]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(["38","1235"])]

In [103]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
9572,16164,[21],21,21-0,21-0-0,21-0-0-0,21-0-0-0-0
44227,66426,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
74375,114659,"[15, 495]",15,15-495,15-495-0,15-495-0-0,15-495-0-0-0
26960,41881,"[12, 31, 101]",12,12-31,12-31-101,12-31-101-0,12-31-101-0-0
6929,12427,"[15, 184]",15,15-184,15-184-0,15-184-0-0,15-184-0-0-0
...,...,...,...,...,...,...,...
84444,128042,"[2, 92]",2,2-92,2-92-0,2-92-0-0,2-92-0-0-0
71800,111464,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
317,537,[17],17,17-0,17-0-0,17-0-0-0,17-0-0-0-0
83371,126623,[15],15,15-0,15-0-0,15-0-0-0,15-0-0-0-0
32452,50436,"[21, 100]",21,21-100,21-100-0,21-100-0-0,21-100-0-0-0

In [104]:
tracks_df['labels_4'].value_counts()

labels_4
1235-0-0-0      618
38-0-0-0        586
10-76-0-0       441
1235-107-0-0    375
15-0-0-0        358
               ...
9-651-493-0       1
2-232-0-0         1
2-86-173-0        1
2-176-0-0         1
20-465-0-0        1
Name: count, Length: 151, dtype: int64

In [105]:
tracks_df['labels_5'].value_counts()

labels_5
1235-0-0-0-0      618
38-0-0-0-0        586
10-76-0-0-0       441
1235-107-0-0-0    375
15-0-0-0-0        358
                 ...
9-651-493-0-0       1
2-46-808-0-0        1
2-86-173-0-0        1
2-176-0-0-0         1
20-465-0-0-0        1
Name: count, Length: 152, dtype: int64

In [106]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(['3','14'])]

In [107]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
9572,16164,[21],21,21-0,21-0-0,21-0-0-0,21-0-0-0-0
44227,66426,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
74375,114659,"[15, 495]",15,15-495,15-495-0,15-495-0-0,15-495-0-0-0
26960,41881,"[12, 31, 101]",12,12-31,12-31-101,12-31-101-0,12-31-101-0-0
6929,12427,"[15, 184]",15,15-184,15-184-0,15-184-0-0,15-184-0-0-0
...,...,...,...,...,...,...,...
84444,128042,"[2, 92]",2,2-92,2-92-0,2-92-0-0,2-92-0-0-0
71800,111464,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
317,537,[17],17,17-0,17-0-0,17-0-0-0,17-0-0-0-0
83371,126623,[15],15,15-0,15-0-0,15-0-0-0,15-0-0-0-0
32452,50436,"[21, 100]",21,21-100,21-100-0,21-100-0-0,21-100-0-0-0

In [108]:
categories_df = pd.DataFrame({'level1':tracks_df.labels_1.unique()})

In [110]:
categories_df = tracks_df[['labels_1','labels_2','labels_3','labels_4','labels_5']].drop_duplicates()

In [111]:
categories_df

      labels_1 labels_2   labels_3     labels_4       labels_5
9572        21     21-0     21-0-0     21-0-0-0     21-0-0-0-0
44227       38   38-247   38-247-0   38-247-0-0   38-247-0-0-0
74375       15   15-495   15-495-0   15-495-0-0   15-495-0-0-0
26960       12    12-31  12-31-101  12-31-101-0  12-31-101-0-0
6929        15   15-184   15-184-0   15-184-0-0   15-184-0-0-0
...        ...      ...        ...          ...            ...
81324        4     4-37     4-37-0     4-37-0-0     4-37-0-0-0
8075        20     20-0     20-0-0     20-0-0-0     20-0-0-0-0
60778        2     2-86   2-86-173   2-86-173-0   2-86-173-0-0
35562        2    2-176    2-176-0    2-176-0-0    2-176-0-0-0
18631       20   20-465   20-465-0   20-465-0-0   20-465-0-0-0

[152 rows x 5 columns]

In [112]:
# categories_df['level1'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:1]))
# categories_df['level2'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:2]))
# categories_df['level3'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:3]))
# categories_df['level4'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:4]))

In [114]:
categories_df

      labels_1 labels_2   labels_3     labels_4       labels_5
9572        21     21-0     21-0-0     21-0-0-0     21-0-0-0-0
44227       38   38-247   38-247-0   38-247-0-0   38-247-0-0-0
74375       15   15-495   15-495-0   15-495-0-0   15-495-0-0-0
26960       12    12-31  12-31-101  12-31-101-0  12-31-101-0-0
6929        15   15-184   15-184-0   15-184-0-0   15-184-0-0-0
...        ...      ...        ...          ...            ...
81324        4     4-37     4-37-0     4-37-0-0     4-37-0-0-0
8075        20     20-0     20-0-0     20-0-0-0     20-0-0-0-0
60778        2     2-86   2-86-173   2-86-173-0   2-86-173-0-0
35562        2    2-176    2-176-0    2-176-0-0    2-176-0-0-0
18631       20   20-465   20-465-0   20-465-0-0   20-465-0-0-0

[152 rows x 5 columns]

In [117]:
def get_labels_name(x,genres_df):
    levels = 5
    full_name = []
    last_level = 0
    genre_root = ""
    for genre in x.split('-'):
        genre_df = genres_df[genres_df['genre_id'] == int(genre)]
        if genre_df.empty:
            genre_name = genre_root 
        else:
            genre_name = genre_df.title.values.tolist()[0]
            genre_root = genre_name
        
        full_name.append(genre_name)
    full_name = '>'.join(full_name)
        
    return full_name
    # return genres_df[genres_df['genre_id'] == int(x)].title.values.tolist()[0]

In [119]:
categories_df['level5_name'] = categories_df.labels_5.apply(lambda x: get_labels_name(x,genres_df))

In [120]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name
9572,21,21-0,21-0-0,21-0-0-0,21-0-0-0-0,Hip-Hop>Hip-Hop>Hip-Hop>Hip-Hop>Hip-Hop
44227,38,38-247,38-247-0,38-247-0-0,38-247-0-0-0,Experimental>Musique Concrete>Musique Concrete...
74375,15,15-495,15-495-0,15-495-0-0,15-495-0-0-0,Electronic>Downtempo>Downtempo>Downtempo>Downt...
26960,12,12-31,12-31-101,12-31-101-0,12-31-101-0-0,Rock>Metal>Death-Metal>Death-Metal>Death-Metal
6929,15,15-184,15-184-0,15-184-0-0,15-184-0-0-0,Electronic>Minimal Electronic>Minimal Electron...
...,...,...,...,...,...,...
81324,4,4-37,4-37-0,4-37-0-0,4-37-0-0-0,Jazz>Jazz: Vocal>Jazz: Vocal>Jazz: Vocal>Jazz:...
8075,20,20-0,20-0-0,20-0-0-0,20-0-0-0-0,Spoken>Spoken>Spoken>Spoken>Spoken
60778,2,2-86,2-86-173,2-86-173-0,2-86-173-0-0,International>Indian>N. Indian Traditional>N. ...
35562,2,2-176,2-176-0,2-176-0-0,2-176-0-0-0,International>Pacific>Pacific>Pacific>Pacific
18631,20,20-465,20-465-0,20-465-0-0,20-465-0-0-0,Spoken>Musical Theater>Musical Theater>Musical...

In [123]:
def __create_labels__(categories_df):
    data = {
        "label1": {},
        "label2": {},
        "label3": {},
        "label4": {},
        "label5": {},
        "label1_inverse": [],
        "label2_inverse": [],
        "label3_inverse": [],
        "label4_inverse": [],
        "label5_inverse": [],
        "label1_name": {},
        "label2_name": {},
        "label3_name": {},
        "label4_name": {},
        "label5_name": {},
    }

    idx = 0
    
    for id_x, cat in enumerate(set(categories_df.labels_1.values.tolist())):
        data['label1'][cat] = idx
        data['label1_inverse'].append(cat)
        data['label1_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_2.values.tolist())):
        data['label2'][cat] = idx
        data['label2_inverse'].append(cat)
        data['label2_count'] = idx + 1
        idx+=1
        
    for id_x, cat in enumerate(set(categories_df.labels_3.values.tolist())):
        data['label3'][cat] = idx
        data['label3_inverse'].append(cat)
        data['label3_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_4.values.tolist())):
        data['label4'][cat] = idx
        data['label4_inverse'].append(cat)
        data['label4_count'] = idx + 1
        idx+=1
        
    for idx, cat in enumerate(set(categories_df.labels_5.values.tolist())):
        data['label5'][cat] = idx
        data['label5_inverse'].append(cat)
        data['label5_count'] = idx + 1
        idx+=1
        
    for cat5,cat1,cat2,cat3,cat4,name5 in categories_df.values:
        
        name1 = '>'.join(name5.split('>')[:1])
        name2 = '>'.join(name5.split('>')[:2])
        name3 = '>'.join(name5.split('>')[:3])
        name4 = '>'.join(name5.split('>')[:4])
        
        
        data['label1_name'][cat1] = name1
        data['label2_name'][cat2] = name2
        data['label3_name'][cat3] = name3
        data['label4_name'][cat4] = name4
        data['label5_name'][cat5] = name5
        
    return data

In [124]:
# with open(categories_labels_path, 'w+') as f:
#     f.write(json.dumps(__create_labels__(categories_df)))

In [125]:
labels  = __create_labels__(categories_df)

In [177]:
labels

{'label1': {'9': 0,
  '14': 1,
  '12': 2,
  '20': 3,
  '13': 4,
  '8': 5,
  '21': 6,
  '15': 7,
  '2': 8,
  '5': 9,
  '1235': 10,
  '3': 11,
  '38': 12,
  '4': 13,
  '10': 14,
  '17': 15},
 'label2': {'38-224': 16,
  '12-36': 17,
  '38-41': 18,
  '38-125': 19,
  '20-378': 20,
  '4-906': 21,
  '12-31': 22,
  '3-567': 23,
  '8-0': 24,
  '2-176': 25,
  '5-322': 26,
  '9-63': 27,
  '38-22': 28,
  '2-171': 29,
  '17-0': 30,
  '38-250': 31,
  '17-94': 32,
  '1235-0': 33,
  '38-514': 34,
  '21-0': 35,
  '14-0': 36,
  '5-444': 37,
  '20-65': 38,
  '12-70': 39,
  '12-0': 40,
  '5-442': 41,
  '15-337': 42,
  '38-0': 43,
  '20-188': 44,
  '38-247': 45,
  '2-92': 46,
  '5-443': 47,
  '13-810': 48,
  '38-6': 49,
  '12-98': 50,
  '15-182': 51,
  '12-66': 52,
  '15-0': 53,
  '12-359': 54,
  '20-0': 55,
  '38-32': 56,
  '1235-107': 57,
  '9-137': 58,
  '12-440': 59,
  '4-179': 60,
  '10-362': 61,
  '15-42': 62,
  '5-0': 63,
  '15-297': 64,
  '12-26': 65,
  '20-465': 66,
  '12-85': 67,
  '15-236': 68,
  '17-103': 69,
  '15-184': 70,
  '38-456': 71,
  '4-0': 72,
  '2-77': 73,
  '14-19': 74,
  '2-102': 75,
  '14-11': 76,
  '12-27': 77,
  '38-186': 78,
  '5-441': 79,
  '9-169': 80,
  '17-180': 81,
  '15-185': 82,
  '12-58': 83,
  '20-138': 84,
  '4-37': 85,
  '4-97': 86,
  '9-0': 87,
  '21-83': 88,
  '2-118': 89,
  '15-468': 90,
  '15-286': 91,
  '21-693': 92,
  '12-314': 93,
  '10-0': 94,
  '21-580': 95,
  '15-695': 96,
  '38-47': 97,
  '21-811': 98,
  '5-659': 99,
  '21-100': 100,
  '13-311': 101,
  '2-177': 102,
  '15-296': 103,
  '17-33': 104,
  '2-0': 105,
  '2-130': 106,
  '1235-267': 107,
  '38-30': 108,
  '1235-18': 109,
  '4-74': 110,
  '2-86': 111,
  '20-428': 112,
  '21-542': 113,
  '12-45': 114,
  '2-232': 115,
  '2-504': 116,
  '3-0': 117,
  '17-49': 118,
  '2-46': 119,
  '15-181': 120,
  '38-1': 121,
  '2-172': 122,
  '15-495': 123,
  '12-25': 124,
  '12-88': 125,
  '5-187': 126,
  '21-539': 127,
  '15-183': 128,
  '2-79': 129,
  '9-651': 130,
  '10-76': 131},
 'label3': {'12-58-0': 132,
  '20-0-0': 133,
  '5-441-0': 134,
  '2-130-619': 135,
  '4-179-0': 136,
  '1235-18-0': 137,
  '21-539-0': 138,
  '17-49-0': 139,
  '38-32-0': 140,
  '4-74-0': 141,
  '20-188-0': 142,
  '38-250-0': 143,
  '15-297-0': 144,
  '17-103-0': 145,
  '12-26-0': 146,
  '12-440-0': 147,
  '38-247-0': 148,
  '15-0-0': 149,
  '13-810-0': 150,
  '20-138-0': 151,
  '2-86-173': 152,
  '20-65-166': 153,
  '38-1-0': 154,
  '5-443-0': 155,
  '15-468-491': 156,
  '15-286-0': 157,
  '38-125-0': 158,
  '12-36-0': 159,
  '10-362-0': 160,
  '2-46-502': 161,
  '15-184-0': 162,
  '12-85-404': 163,
  '3-567-0': 164,
  '21-100-0': 165,
  '21-811-0': 166,
  '2-176-0': 167,
  '15-181-0': 168,
  '15-695-0': 169,
  '38-224-0': 170,
  '38-6-16': 171,
  '2-130-0': 172,
  '9-169-0': 173,
  '15-183-0': 174,
  '12-66-0': 175,
  '38-30-0': 176,
  '17-180-0': 177,
  '12-70-0': 178,
  '12-31-101': 179,
  '21-693-0': 180,
  '14-0-0': 181,
  '12-31-439': 182,
  '4-97-0': 183,
  '15-337-0': 184,
  '13-311-0': 185,
  '38-456-0': 186,
  '8-0-0': 187,
  '12-25-64': 188,
  '2-102-0': 189,
  '12-45-53': 190,
  '21-0-0': 191,
  '2-46-0': 192,
  '20-65-43': 193,
  '12-25-0': 194,
  '38-186-0': 195,
  '5-322-0': 196,
  '2-77-0': 197,
  '2-504-0': 198,
  '4-37-0': 199,
  '20-428-0': 200,
  '20-378-0': 201,
  '38-0-0': 202,
  '1235-107-0': 203,
  '12-31-167': 204,
  '2-92-81': 205,
  '15-236-0': 206,
  '38-6-360': 207,
  '2-79-0': 208,
  '38-514-0': 209,
  '15-42-0': 210,
  '12-0-0': 211,
  '9-63-0': 212,
  '1235-0-0': 213,
  '15-468-0': 214,
  '21-580-0': 215,
  '15-296-0': 216,
  '2-171-0': 217,
  '2-118-0': 218,
  '2-92-0': 219,
  '2-177-0': 220,
  '2-232-0': 221,
  '12-26-113': 222,
  '4-0-0': 223,
  '2-130-1156': 224,
  '10-76-0': 225,
  '2-46-1060': 226,
  '17-0-0': 227,
  '1235-267-0': 228,
  '2-92-214': 229,
  '12-27-0': 230,
  '5-442-0': 231,
  '20-65-0': 232,
  '2-172-0': 233,
  '2-102-1032': 234,
  '15-182-400': 235,
  '15-181-401': 236,
  '12-45-0': 237,
  '2-130-741': 238,
  '12-25-71': 239,
  '5-659-0': 240,
  '15-297-240': 241,
  '12-25-109': 242,
  '3-0-0': 243,
  '20-465-0': 244,
  '9-0-0': 245,
  '12-88-0': 246,
  '2-0-0': 247,
  '12-98-0': 248,
  '38-6-0': 249,
  '21-83-0': 250,
  '12-359-0': 251,
  '15-495-0': 252,
  '15-182-0': 253,
  '10-0-0': 254,
  '12-314-0': 255,
  '38-41-0': 256,
  '15-185-0': 257,
  '9-651-0': 258,
  '14-19-0': 259,
  '38-47-0': 260,
  '9-137-0': 261,
  '9-651-493': 262,
  '14-11-0': 263,
  '4-906-0': 264,
  '12-25-89': 265,
  '21-542-0': 266,
  '1235-18-538': 267,
  '5-187-0': 268,
  '17-94-0': 269,
  '2-130-524': 270,
  '5-444-0': 271,
  '17-33-0': 272,
  '12-25-111': 273,
  '5-0-0': 274,
  '38-22-0': 275,
  '12-31-0': 276,
  '2-46-808': 277,
  '2-79-602': 278,
  '12-85-0': 279,
  '2-86-0': 280},
 'label4': {'12-85-0-0': 281,
  '1235-18-538-0': 282,
  '5-443-0-0': 283,
  '12-85-404-0': 284,
  '2-79-602-0': 285,
  '21-580-0-0': 286,
  '15-236-0-0': 287,
  '21-0-0-0': 288,
  '20-0-0-0': 289,
  '38-30-0-0': 290,
  '15-185-0-0': 291,
  '4-906-0-0': 292,
  '12-45-0-0': 293,
  '2-102-1032-0': 294,
  '21-100-0-0': 295,
  '4-0-0-0': 296,
  '17-49-0-0': 297,
  '12-25-109-361': 298,
  '2-86-173-0': 299,
  '15-184-0-0': 300,
  '12-58-0-0': 301,
  '2-46-502-0': 302,
  '12-314-0-0': 303,
  '12-25-71-0': 304,
  '4-74-0-0': 305,
  '38-514-0-0': 306,
  '2-0-0-0': 307,
  '12-31-0-0': 308,
  '2-172-0-0': 309,
  '12-31-439-0': 310,
  '20-65-166-0': 311,
  '15-468-0-0': 312,
  '15-183-0-0': 313,
  '2-118-0-0': 314,
  '1235-0-0-0': 315,
  '38-186-0-0': 316,
  '2-130-1156-0': 317,
  '12-25-111-0': 318,
  '2-46-1060-0': 319,
  '4-179-0-0': 320,
  '17-180-0-0': 321,
  '12-25-64-0': 322,
  '2-130-524-0': 323,
  '21-83-0-0': 324,
  '20-188-0-0': 325,
  '15-182-0-0': 326,
  '2-130-741-0': 327,
  '2-171-0-0': 328,
  '12-359-0-0': 329,
  '12-25-109-0': 330,
  '1235-18-0-0': 331,
  '15-468-491-0': 332,
  '2-176-0-0': 333,
  '14-11-0-0': 334,
  '15-297-0-0': 335,
  '21-539-0-0': 336,
  '5-444-0-0': 337,
  '2-92-214-0': 338,
  '38-6-16-763': 339,
  '12-36-0-0': 340,
  '15-42-0-0': 341,
  '13-810-0-0': 342,
  '38-22-0-0': 343,
  '5-659-0-0': 344,
  '12-45-53-90': 345,
  '12-0-0-0': 346,
  '9-651-493-0': 347,
  '15-297-240-0': 348,
  '2-102-0-0': 349,
  '12-70-0-0': 350,
  '12-31-101-0': 351,
  '2-130-619-0': 352,
  '15-182-400-0': 353,
  '20-378-0-0': 354,
  '2-232-0-0': 355,
  '20-465-0-0': 356,
  '10-0-0-0': 357,
  '15-495-0-0': 358,
  '2-177-0-0': 359,
  '1235-267-0-0': 360,
  '10-362-0-0': 361,
  '9-651-0-0': 362,
  '38-32-0-0': 363,
  '21-693-0-0': 364,
  '17-33-0-0': 365,
  '2-92-81-0': 366,
  '4-37-0-0': 367,
  '38-456-0-0': 368,
  '12-27-0-0': 369,
  '12-26-0-0': 370,
  '17-94-0-0': 371,
  '8-0-0-0': 372,
  '9-137-0-0': 373,
  '3-0-0-0': 374,
  '9-169-0-0': 375,
  '12-98-0-0': 376,
  '38-125-0-0': 377,
  '21-811-0-0': 378,
  '14-19-0-0': 379,
  '38-224-0-0': 380,
  '2-46-0-0': 381,
  '9-0-0-0': 382,
  '38-0-0-0': 383,
  '20-65-43-0': 384,
  '17-103-0-0': 385,
  '2-92-0-0': 386,
  '15-695-0-0': 387,
  '5-322-0-0': 388,
  '12-31-167-0': 389,
  '38-247-0-0': 390,
  '38-250-0-0': 391,
  '12-440-0-0': 392,
  '38-1-0-0': 393,
  '38-6-0-0': 394,
  '4-97-0-0': 395,
  '12-25-89-0': 396,
  '20-138-0-0': 397,
  '12-88-0-0': 398,
  '5-187-0-0': 399,
  '2-77-0-0': 400,
  '15-181-0-0': 401,
  '21-542-0-0': 402,
  '5-0-0-0': 403,
  '5-441-0-0': 404,
  '20-65-0-0': 405,
  '14-0-0-0': 406,
  '2-504-0-0': 407,
  '13-311-0-0': 408,
  '1235-107-0-0': 409,
  '15-286-0-0': 410,
  '5-442-0-0': 411,
  '17-0-0-0': 412,
  '3-567-0-0': 413,
  '10-76-0-0': 414,
  '15-296-0-0': 415,
  '38-41-0-0': 416,
  '15-337-0-0': 417,
  '38-6-360-0': 418,
  '15-181-401-0': 419,
  '20-428-0-0': 420,
  '15-0-0-0': 421,
  '9-63-0-0': 422,
  '2-86-0-0': 423,
  '2-79-0-0': 424,
  '12-66-0-0': 425,
  '2-130-0-0': 426,
  '12-45-53-0': 427,
  '12-26-113-0': 428,
  '2-46-808-0': 429,
  '12-25-0-0': 430,
  '38-47-0-0': 431},
 'label5': {'12-31-101-0-0': 0,
  '9-651-0-0-0': 1,
  '12-25-64-0-0': 2,
  '12-25-109-361-0': 3,
  '21-83-0-0-0': 4,
  '5-0-0-0-0': 5,
  '3-567-0-0-0': 6,
  '5-443-0-0-0': 7,
  '15-297-0-0-0': 8,
  '13-311-0-0-0': 9,
  '38-514-0-0-0': 10,
  '8-0-0-0-0': 11,
  '38-247-0-0-0': 12,
  '38-6-16-763-0': 13,
  '12-25-0-0-0': 14,
  '12-45-0-0-0': 15,
  '2-130-524-0-0': 16,
  '2-130-619-0-0': 17,
  '15-695-0-0-0': 18,
  '17-180-0-0-0': 19,
  '5-322-0-0-0': 20,
  '1235-18-0-0-0': 21,
  '38-6-360-0-0': 22,
  '3-0-0-0-0': 23,
  '20-0-0-0-0': 24,
  '9-137-0-0-0': 25,
  '38-41-0-0-0': 26,
  '15-297-240-0-0': 27,
  '15-181-401-0-0': 28,
  '12-36-0-0-0': 29,
  '2-79-0-0-0': 30,
  '15-181-0-0-0': 31,
  '2-79-602-0-0': 32,
  '1235-267-0-0-0': 33,
  '4-37-0-0-0': 34,
  '2-232-0-0-0': 35,
  '4-0-0-0-0': 36,
  '2-171-0-0-0': 37,
  '15-236-0-0-0': 38,
  '12-88-0-0-0': 39,
  '4-906-0-0-0': 40,
  '2-46-502-0-0': 41,
  '38-224-0-0-0': 42,
  '15-183-0-0-0': 43,
  '20-428-0-0-0': 44,
  '21-542-0-0-0': 45,
  '5-442-0-0-0': 46,
  '2-46-808-0-0': 47,
  '21-100-0-0-0': 48,
  '9-63-0-0-0': 49,
  '12-45-53-90-0': 50,
  '2-504-0-0-0': 51,
  '21-0-0-0-0': 52,
  '20-465-0-0-0': 53,
  '21-539-0-0-0': 54,
  '38-0-0-0-0': 55,
  '5-187-0-0-0': 56,
  '2-130-1156-0-0': 57,
  '12-440-0-0-0': 58,
  '12-45-53-0-0': 59,
  '38-456-0-0-0': 60,
  '17-33-0-0-0': 61,
  '38-125-0-0-0': 62,
  '13-810-0-0-0': 63,
  '12-25-109-0-0': 64,
  '14-11-0-0-0': 65,
  '38-32-0-0-0': 66,
  '2-172-0-0-0': 67,
  '20-65-0-0-0': 68,
  '14-0-0-0-0': 69,
  '12-359-0-0-0': 70,
  '12-31-0-0-0': 71,
  '21-693-0-0-0': 72,
  '9-0-0-0-0': 73,
  '4-179-0-0-0': 74,
  '20-138-0-0-0': 75,
  '2-102-0-0-0': 76,
  '5-659-0-0-0': 77,
  '12-25-71-0-0': 78,
  '12-25-89-0-0': 79,
  '12-70-0-0-0': 80,
  '15-296-0-0-0': 81,
  '2-77-0-0-0': 82,
  '12-85-404-0-0': 83,
  '21-811-0-0-0': 84,
  '12-25-111-0-0': 85,
  '38-30-0-0-0': 86,
  '15-185-0-0-0': 87,
  '12-58-0-0-0': 88,
  '5-441-0-0-0': 89,
  '15-286-0-0-0': 90,
  '15-468-0-0-0': 91,
  '12-26-113-0-0': 92,
  '2-177-0-0-0': 93,
  '10-362-0-0-0': 94,
  '15-0-0-0-0': 95,
  '15-42-0-0-0': 96,
  '10-76-0-0-0': 97,
  '12-85-0-0-0': 98,
  '38-186-0-0-0': 99,
  '38-22-0-0-0': 100,
  '4-74-0-0-0': 101,
  '2-102-1032-0-0': 102,
  '15-182-400-0-0': 103,
  '2-176-0-0-0': 104,
  '15-468-491-0-0': 105,
  '12-66-0-0-0': 106,
  '20-65-166-0-0': 107,
  '10-0-0-0-0': 108,
  '2-92-214-0-0': 109,
  '4-97-0-0-0': 110,
  '21-580-0-0-0': 111,
  '12-27-0-0-0': 112,
  '2-86-173-0-0': 113,
  '12-0-0-0-0': 114,
  '20-378-0-0-0': 115,
  '2-130-0-0-0': 116,
  '38-1-0-0-0': 117,
  '38-6-16-763-1193': 118,
  '2-86-0-0-0': 119,
  '2-46-1060-0-0': 120,
  '12-31-439-0-0': 121,
  '2-92-0-0-0': 122,
  '15-495-0-0-0': 123,
  '17-94-0-0-0': 124,
  '2-130-741-0-0': 125,
  '17-49-0-0-0': 126,
  '9-651-493-0-0': 127,
  '1235-0-0-0-0': 128,
  '2-46-0-0-0': 129,
  '2-92-81-0-0': 130,
  '1235-18-538-0-0': 131,
  '2-0-0-0-0': 132,
  '12-26-0-0-0': 133,
  '14-19-0-0-0': 134,
  '12-314-0-0-0': 135,
  '17-103-0-0-0': 136,
  '9-169-0-0-0': 137,
  '38-6-0-0-0': 138,
  '38-47-0-0-0': 139,
  '12-31-167-0-0': 140,
  '15-184-0-0-0': 141,
  '17-0-0-0-0': 142,
  '1235-107-0-0-0': 143,
  '38-250-0-0-0': 144,
  '5-444-0-0-0': 145,
  '20-188-0-0-0': 146,
  '2-118-0-0-0': 147,
  '15-337-0-0-0': 148,
  '12-98-0-0-0': 149,
  '20-65-43-0-0': 150,
  '15-182-0-0-0': 151},
 'label1_inverse': ['9',
  '14',
  '12',
  '20',
  '13',
  '8',
  '21',
  '15',
  '2',
  '5',
  '1235',
  '3',
  '38',
  '4',
  '10',
  '17'],
 'label2_inverse': ['38-224',
  '12-36',
  '38-41',
  '38-125',
  '20-378',
  '4-906',
  '12-31',
  '3-567',
  '8-0',
  '2-176',
  '5-322',
  '9-63',
  '38-22',
  '2-171',
  '17-0',
  '38-250',
  '17-94',
  '1235-0',
  '38-514',
  '21-0',
  '14-0',
  '5-444',
  '20-65',
  '12-70',
  '12-0',
  '5-442',
  '15-337',
  '38-0',
  '20-188',
  '38-247',
  '2-92',
  '5-443',
  '13-810',
  '38-6',
  '12-98',
  '15-182',
  '12-66',
  '15-0',
  '12-359',
  '20-0',
  '38-32',
  '1235-107',
  '9-137',
  '12-440',
  '4-179',
  '10-362',
  '15-42',
  '5-0',
  '15-297',
  '12-26',
  '20-465',
  '12-85',
  '15-236',
  '17-103',
  '15-184',
  '38-456',
  '4-0',
  '2-77',
  '14-19',
  '2-102',
  '14-11',
  '12-27',
  '38-186',
  '5-441',
  '9-169',
  '17-180',
  '15-185',
  '12-58',
  '20-138',
  '4-37',
  '4-97',
  '9-0',
  '21-83',
  '2-118',
  '15-468',
  '15-286',
  '21-693',
  '12-314',
  '10-0',
  '21-580',
  '15-695',
  '38-47',
  '21-811',
  '5-659',
  '21-100',
  '13-311',
  '2-177',
  '15-296',
  '17-33',
  '2-0',
  '2-130',
  '1235-267',
  '38-30',
  '1235-18',
  '4-74',
  '2-86',
  '20-428',
  '21-542',
  '12-45',
  '2-232',
  '2-504',
  '3-0',
  '17-49',
  '2-46',
  '15-181',
  '38-1',
  '2-172',
  '15-495',
  '12-25',
  '12-88',
  '5-187',
  '21-539',
  '15-183',
  '2-79',
  '9-651',
  '10-76'],
 'label3_inverse': ['12-58-0',
  '20-0-0',
  '5-441-0',
  '2-130-619',
  '4-179-0',
  '1235-18-0',
  '21-539-0',
  '17-49-0',
  '38-32-0',
  '4-74-0',
  '20-188-0',
  '38-250-0',
  '15-297-0',
  '17-103-0',
  '12-26-0',
  '12-440-0',
  '38-247-0',
  '15-0-0',
  '13-810-0',
  '20-138-0',
  '2-86-173',
  '20-65-166',
  '38-1-0',
  '5-443-0',
  '15-468-491',
  '15-286-0',
  '38-125-0',
  '12-36-0',
  '10-362-0',
  '2-46-502',
  '15-184-0',
  '12-85-404',
  '3-567-0',
  '21-100-0',
  '21-811-0',
  '2-176-0',
  '15-181-0',
  '15-695-0',
  '38-224-0',
  '38-6-16',
  '2-130-0',
  '9-169-0',
  '15-183-0',
  '12-66-0',
  '38-30-0',
  '17-180-0',
  '12-70-0',
  '12-31-101',
  '21-693-0',
  '14-0-0',
  '12-31-439',
  '4-97-0',
  '15-337-0',
  '13-311-0',
  '38-456-0',
  '8-0-0',
  '12-25-64',
  '2-102-0',
  '12-45-53',
  '21-0-0',
  '2-46-0',
  '20-65-43',
  '12-25-0',
  '38-186-0',
  '5-322-0',
  '2-77-0',
  '2-504-0',
  '4-37-0',
  '20-428-0',
  '20-378-0',
  '38-0-0',
  '1235-107-0',
  '12-31-167',
  '2-92-81',
  '15-236-0',
  '38-6-360',
  '2-79-0',
  '38-514-0',
  '15-42-0',
  '12-0-0',
  '9-63-0',
  '1235-0-0',
  '15-468-0',
  '21-580-0',
  '15-296-0',
  '2-171-0',
  '2-118-0',
  '2-92-0',
  '2-177-0',
  '2-232-0',
  '12-26-113',
  '4-0-0',
  '2-130-1156',
  '10-76-0',
  '2-46-1060',
  '17-0-0',
  '1235-267-0',
  '2-92-214',
  '12-27-0',
  '5-442-0',
  '20-65-0',
  '2-172-0',
  '2-102-1032',
  '15-182-400',
  '15-181-401',
  '12-45-0',
  '2-130-741',
  '12-25-71',
  '5-659-0',
  '15-297-240',
  '12-25-109',
  '3-0-0',
  '20-465-0',
  '9-0-0',
  '12-88-0',
  '2-0-0',
  '12-98-0',
  '38-6-0',
  '21-83-0',
  '12-359-0',
  '15-495-0',
  '15-182-0',
  '10-0-0',
  '12-314-0',
  '38-41-0',
  '15-185-0',
  '9-651-0',
  '14-19-0',
  '38-47-0',
  '9-137-0',
  '9-651-493',
  '14-11-0',
  '4-906-0',
  '12-25-89',
  '21-542-0',
  '1235-18-538',
  '5-187-0',
  '17-94-0',
  '2-130-524',
  '5-444-0',
  '17-33-0',
  '12-25-111',
  '5-0-0',
  '38-22-0',
  '12-31-0',
  '2-46-808',
  '2-79-602',
  '12-85-0',
  '2-86-0'],
 'label4_inverse': ['12-85-0-0',
  '1235-18-538-0',
  '5-443-0-0',
  '12-85-404-0',
  '2-79-602-0',
  '21-580-0-0',
  '15-236-0-0',
  '21-0-0-0',
  '20-0-0-0',
  '38-30-0-0',
  '15-185-0-0',
  '4-906-0-0',
  '12-45-0-0',
  '2-102-1032-0',
  '21-100-0-0',
  '4-0-0-0',
  '17-49-0-0',
  '12-25-109-361',
  '2-86-173-0',
  '15-184-0-0',
  '12-58-0-0',
  '2-46-502-0',
  '12-314-0-0',
  '12-25-71-0',
  '4-74-0-0',
  '38-514-0-0',
  '2-0-0-0',
  '12-31-0-0',
  '2-172-0-0',
  '12-31-439-0',
  '20-65-166-0',
  '15-468-0-0',
  '15-183-0-0',
  '2-118-0-0',
  '1235-0-0-0',
  '38-186-0-0',
  '2-130-1156-0',
  '12-25-111-0',
  '2-46-1060-0',
  '4-179-0-0',
  '17-180-0-0',
  '12-25-64-0',
  '2-130-524-0',
  '21-83-0-0',
  '20-188-0-0',
  '15-182-0-0',
  '2-130-741-0',
  '2-171-0-0',
  '12-359-0-0',
  '12-25-109-0',
  '1235-18-0-0',
  '15-468-491-0',
  '2-176-0-0',
  '14-11-0-0',
  '15-297-0-0',
  '21-539-0-0',
  '5-444-0-0',
  '2-92-214-0',
  '38-6-16-763',
  '12-36-0-0',
  '15-42-0-0',
  '13-810-0-0',
  '38-22-0-0',
  '5-659-0-0',
  '12-45-53-90',
  '12-0-0-0',
  '9-651-493-0',
  '15-297-240-0',
  '2-102-0-0',
  '12-70-0-0',
  '12-31-101-0',
  '2-130-619-0',
  '15-182-400-0',
  '20-378-0-0',
  '2-232-0-0',
  '20-465-0-0',
  '10-0-0-0',
  '15-495-0-0',
  '2-177-0-0',
  '1235-267-0-0',
  '10-362-0-0',
  '9-651-0-0',
  '38-32-0-0',
  '21-693-0-0',
  '17-33-0-0',
  '2-92-81-0',
  '4-37-0-0',
  '38-456-0-0',
  '12-27-0-0',
  '12-26-0-0',
  '17-94-0-0',
  '8-0-0-0',
  '9-137-0-0',
  '3-0-0-0',
  '9-169-0-0',
  '12-98-0-0',
  '38-125-0-0',
  '21-811-0-0',
  '14-19-0-0',
  '38-224-0-0',
  '2-46-0-0',
  '9-0-0-0',
  '38-0-0-0',
  '20-65-43-0',
  '17-103-0-0',
  '2-92-0-0',
  '15-695-0-0',
  '5-322-0-0',
  '12-31-167-0',
  '38-247-0-0',
  '38-250-0-0',
  '12-440-0-0',
  '38-1-0-0',
  '38-6-0-0',
  '4-97-0-0',
  '12-25-89-0',
  '20-138-0-0',
  '12-88-0-0',
  '5-187-0-0',
  '2-77-0-0',
  '15-181-0-0',
  '21-542-0-0',
  '5-0-0-0',
  '5-441-0-0',
  '20-65-0-0',
  '14-0-0-0',
  '2-504-0-0',
  '13-311-0-0',
  '1235-107-0-0',
  '15-286-0-0',
  '5-442-0-0',
  '17-0-0-0',
  '3-567-0-0',
  '10-76-0-0',
  '15-296-0-0',
  '38-41-0-0',
  '15-337-0-0',
  '38-6-360-0',
  '15-181-401-0',
  '20-428-0-0',
  '15-0-0-0',
  '9-63-0-0',
  '2-86-0-0',
  '2-79-0-0',
  '12-66-0-0',
  '2-130-0-0',
  '12-45-53-0',
  '12-26-113-0',
  '2-46-808-0',
  '12-25-0-0',
  '38-47-0-0'],
 'label5_inverse': ['12-31-101-0-0',
  '9-651-0-0-0',
  '12-25-64-0-0',
  '12-25-109-361-0',
  '21-83-0-0-0',
  '5-0-0-0-0',
  '3-567-0-0-0',
  '5-443-0-0-0',
  '15-297-0-0-0',
  '13-311-0-0-0',
  '38-514-0-0-0',
  '8-0-0-0-0',
  '38-247-0-0-0',
  '38-6-16-763-0',
  '12-25-0-0-0',
  '12-45-0-0-0',
  '2-130-524-0-0',
  '2-130-619-0-0',
  '15-695-0-0-0',
  '17-180-0-0-0',
  '5-322-0-0-0',
  '1235-18-0-0-0',
  '38-6-360-0-0',
  '3-0-0-0-0',
  '20-0-0-0-0',
  '9-137-0-0-0',
  '38-41-0-0-0',
  '15-297-240-0-0',
  '15-181-401-0-0',
  '12-36-0-0-0',
  '2-79-0-0-0',
  '15-181-0-0-0',
  '2-79-602-0-0',
  '1235-267-0-0-0',
  '4-37-0-0-0',
  '2-232-0-0-0',
  '4-0-0-0-0',
  '2-171-0-0-0',
  '15-236-0-0-0',
  '12-88-0-0-0',
  '4-906-0-0-0',
  '2-46-502-0-0',
  '38-224-0-0-0',
  '15-183-0-0-0',
  '20-428-0-0-0',
  '21-542-0-0-0',
  '5-442-0-0-0',
  '2-46-808-0-0',
  '21-100-0-0-0',
  '9-63-0-0-0',
  '12-45-53-90-0',
  '2-504-0-0-0',
  '21-0-0-0-0',
  '20-465-0-0-0',
  '21-539-0-0-0',
  '38-0-0-0-0',
  '5-187-0-0-0',
  '2-130-1156-0-0',
  '12-440-0-0-0',
  '12-45-53-0-0',
  '38-456-0-0-0',
  '17-33-0-0-0',
  '38-125-0-0-0',
  '13-810-0-0-0',
  '12-25-109-0-0',
  '14-11-0-0-0',
  '38-32-0-0-0',
  '2-172-0-0-0',
  '20-65-0-0-0',
  '14-0-0-0-0',
  '12-359-0-0-0',
  '12-31-0-0-0',
  '21-693-0-0-0',
  '9-0-0-0-0',
  '4-179-0-0-0',
  '20-138-0-0-0',
  '2-102-0-0-0',
  '5-659-0-0-0',
  '12-25-71-0-0',
  '12-25-89-0-0',
  '12-70-0-0-0',
  '15-296-0-0-0',
  '2-77-0-0-0',
  '12-85-404-0-0',
  '21-811-0-0-0',
  '12-25-111-0-0',
  '38-30-0-0-0',
  '15-185-0-0-0',
  '12-58-0-0-0',
  '5-441-0-0-0',
  '15-286-0-0-0',
  '15-468-0-0-0',
  '12-26-113-0-0',
  '2-177-0-0-0',
  '10-362-0-0-0',
  '15-0-0-0-0',
  '15-42-0-0-0',
  '10-76-0-0-0',
  '12-85-0-0-0',
  '38-186-0-0-0',
  '38-22-0-0-0',
  '4-74-0-0-0',
  '2-102-1032-0-0',
  '15-182-400-0-0',
  '2-176-0-0-0',
  '15-468-491-0-0',
  '12-66-0-0-0',
  '20-65-166-0-0',
  '10-0-0-0-0',
  '2-92-214-0-0',
  '4-97-0-0-0',
  '21-580-0-0-0',
  '12-27-0-0-0',
  '2-86-173-0-0',
  '12-0-0-0-0',
  '20-378-0-0-0',
  '2-130-0-0-0',
  '38-1-0-0-0',
  '38-6-16-763-1193',
  '2-86-0-0-0',
  '2-46-1060-0-0',
  '12-31-439-0-0',
  '2-92-0-0-0',
  '15-495-0-0-0',
  '17-94-0-0-0',
  '2-130-741-0-0',
  '17-49-0-0-0',
  '9-651-493-0-0',
  '1235-0-0-0-0',
  '2-46-0-0-0',
  '2-92-81-0-0',
  '1235-18-538-0-0',
  '2-0-0-0-0',
  '12-26-0-0-0',
  '14-19-0-0-0',
  '12-314-0-0-0',
  '17-103-0-0-0',
  '9-169-0-0-0',
  '38-6-0-0-0',
  '38-47-0-0-0',
  '12-31-167-0-0',
  '15-184-0-0-0',
  '17-0-0-0-0',
  '1235-107-0-0-0',
  '38-250-0-0-0',
  '5-444-0-0-0',
  '20-188-0-0-0',
  '2-118-0-0-0',
  '15-337-0-0-0',
  '12-98-0-0-0',
  '20-65-43-0-0',
  '15-182-0-0-0'],
 'label1_name': {'21-0': 'Hip-Hop',
  '38-247': 'Experimental',
  '15-495': 'Electronic',
  '12-31': 'Rock',
  '15-184': 'Electronic',
  '17-94': 'Folk',
  '38-0': 'Experimental',
  '12-359': 'Rock',
  '10-76': 'Pop',
  '15-0': 'Electronic',

In [180]:
categories_df['labels_1_'] = categories_df.labels_1.apply(lambda x: labels['label1'].get(x))
categories_df['labels_2_'] = categories_df.labels_2.apply(lambda x: labels['label2'].get(x))
categories_df['labels_3_'] = categories_df.labels_3.apply(lambda x: labels['label3'].get(x))
categories_df['labels_4_'] = categories_df.labels_4.apply(lambda x: labels['label4'].get(x))
categories_df['labels_5_'] = categories_df.labels_5.apply(lambda x: labels['label5'].get(x))

In [181]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name,labels_1_,labels_2_,labels_3_,labels_4_,labels_5_
9572,21,21-0,21-0-0,21-0-0-0,21-0-0-0-0,Hip-Hop>Hip-Hop>Hip-Hop>Hip-Hop>Hip-Hop,6,35,191,288,52
44227,38,38-247,38-247-0,38-247-0-0,38-247-0-0-0,Experimental>Musique Concrete>Musique Concrete...,12,45,148,390,12
74375,15,15-495,15-495-0,15-495-0-0,15-495-0-0-0,Electronic>Downtempo>Downtempo>Downtempo>Downt...,7,123,252,358,123
26960,12,12-31,12-31-101,12-31-101-0,12-31-101-0-0,Rock>Metal>Death-Metal>Death-Metal>Death-Metal,2,22,179,351,0
6929,15,15-184,15-184-0,15-184-0-0,15-184-0-0-0,Electronic>Minimal Electronic>Minimal Electron...,7,70,162,300,141
...,...,...,...,...,...,...,...,...,...,...,...
81324,4,4-37,4-37-0,4-37-0-0,4-37-0-0-0,Jazz>Jazz: Vocal>Jazz: Vocal>Jazz: Vocal>Jazz:...,13,85,199,367,34
8075,20,20-0,20-0-0,20-0-0-0,20-0-0-0-0,Spoken>Spoken>Spoken>Spoken>Spoken,3,55,133,289,24
60778,2,2-86,2-86-173,2-86-173-0,2-86-173-0-0,International>Indian>N. Indian Traditional>N. ...,8,111,152,299,113
35562,2,2-176,2-176-0,2-176-0-0,2-176-0-0-0,International>Pacific>Pacific>Pacific>Pacific,8,25,167,333,104
18631,20,20-465,20-465-0,20-465-0-0,20-465-0-0-0,Spoken>Musical Theater>Musical Theater>Musical...,3,66,244,356,53

In [202]:
unique_labels_1 = categories_df['labels_1_'].unique().tolist()
unique_labels_2 = categories_df['labels_2_'].unique().tolist()
unique_labels_3 = categories_df['labels_3_'].unique().tolist()
unique_labels_4 = categories_df['labels_4_'].unique().tolist()
unique_labels_5 = categories_df['labels_5_'].unique().tolist()

In [203]:
unique_labels_1

[6, 12, 7, 2, 15, 14, 10, 8, 0, 5, 9, 4, 13, 3, 1, 11]

In [204]:
num_nodes_per_level = [unique_labels_1, unique_labels_2, unique_labels_3, unique_labels_4, unique_labels_5]

In [205]:
# Cálculo de num_classes_per_node
num_classes_per_node = []
num_classes_per_node.append(unique_labels_1)  # Nível 1

unique_lavel2_per_level1 = categories_df.groupby('labels_1_')['labels_2_'].nunique()
num_classes_per_node.append(unique_lavel2_per_level1.tolist())  # Nível 2

In [206]:
unique_lavel3_per_level2 = categories_df.groupby(['labels_1_', 'labels_2_'])['labels_3_'].nunique()
num_classes_per_node.append(unique_lavel3_per_level2.tolist())  # Nível 3

In [207]:
unique_lavel4_per_level3 = categories_df.groupby(['labels_1_', 'labels_2_', 'labels_3_'])['labels_4_'].nunique()
num_classes_per_node.append(unique_lavel4_per_level3.tolist())  # Nível 4

In [208]:

unique_lavel5_per_level4 = categories_df.groupby(['labels_1_', 'labels_2_', 'labels_3_', 'labels_4_'])['labels_5_'].nunique()
num_classes_per_node.append(unique_lavel5_per_level4.tolist())  # Nível 5

In [209]:

print("num_nodes_per_level:", num_classes_per_node[0])

num_nodes_per_level: [6, 12, 7, 2, 15, 14, 10, 8, 0, 5, 9, 4, 13, 3, 1, 11]

In [210]:
labels['label5']

{'12-31-101-0-0': 0,
 '9-651-0-0-0': 1,
 '12-25-64-0-0': 2,
 '12-25-109-361-0': 3,
 '21-83-0-0-0': 4,
 '5-0-0-0-0': 5,
 '3-567-0-0-0': 6,
 '5-443-0-0-0': 7,
 '15-297-0-0-0': 8,
 '13-311-0-0-0': 9,
 '38-514-0-0-0': 10,
 '8-0-0-0-0': 11,
 '38-247-0-0-0': 12,
 '38-6-16-763-0': 13,
 '12-25-0-0-0': 14,
 '12-45-0-0-0': 15,
 '2-130-524-0-0': 16,
 '2-130-619-0-0': 17,
 '15-695-0-0-0': 18,
 '17-180-0-0-0': 19,
 '5-322-0-0-0': 20,
 '1235-18-0-0-0': 21,
 '38-6-360-0-0': 22,
 '3-0-0-0-0': 23,
 '20-0-0-0-0': 24,
 '9-137-0-0-0': 25,
 '38-41-0-0-0': 26,
 '15-297-240-0-0': 27,
 '15-181-401-0-0': 28,
 '12-36-0-0-0': 29,
 '2-79-0-0-0': 30,
 '15-181-0-0-0': 31,
 '2-79-602-0-0': 32,
 '1235-267-0-0-0': 33,
 '4-37-0-0-0': 34,
 '2-232-0-0-0': 35,
 '4-0-0-0-0': 36,
 '2-171-0-0-0': 37,
 '15-236-0-0-0': 38,
 '12-88-0-0-0': 39,
 '4-906-0-0-0': 40,
 '2-46-502-0-0': 41,
 '38-224-0-0-0': 42,
 '15-183-0-0-0': 43,
 '20-428-0-0-0': 44,
 '21-542-0-0-0': 45,
 '5-442-0-0-0': 46,
 '2-46-808-0-0': 47,
 '21-100-0-0-0': 48,
 '9-63-0-0-0': 49,
 '12-45-53-90-0': 50,
 '2-504-0-0-0': 51,
 '21-0-0-0-0': 52,
 '20-465-0-0-0': 53,
 '21-539-0-0-0': 54,
 '38-0-0-0-0': 55,
 '5-187-0-0-0': 56,
 '2-130-1156-0-0': 57,
 '12-440-0-0-0': 58,
 '12-45-53-0-0': 59,
 '38-456-0-0-0': 60,
 '17-33-0-0-0': 61,
 '38-125-0-0-0': 62,
 '13-810-0-0-0': 63,
 '12-25-109-0-0': 64,
 '14-11-0-0-0': 65,
 '38-32-0-0-0': 66,
 '2-172-0-0-0': 67,
 '20-65-0-0-0': 68,
 '14-0-0-0-0': 69,
 '12-359-0-0-0': 70,
 '12-31-0-0-0': 71,
 '21-693-0-0-0': 72,
 '9-0-0-0-0': 73,
 '4-179-0-0-0': 74,
 '20-138-0-0-0': 75,
 '2-102-0-0-0': 76,
 '5-659-0-0-0': 77,
 '12-25-71-0-0': 78,
 '12-25-89-0-0': 79,
 '12-70-0-0-0': 80,
 '15-296-0-0-0': 81,
 '2-77-0-0-0': 82,
 '12-85-404-0-0': 83,
 '21-811-0-0-0': 84,
 '12-25-111-0-0': 85,
 '38-30-0-0-0': 86,
 '15-185-0-0-0': 87,
 '12-58-0-0-0': 88,
 '5-441-0-0-0': 89,
 '15-286-0-0-0': 90,
 '15-468-0-0-0': 91,
 '12-26-113-0-0': 92,
 '2-177-0-0-0': 93,
 '10-362-0-0-0': 94,
 '15-0-0-0-0': 95,
 '15-42-0-0-0': 96,
 '10-76-0-0-0': 97,
 '12-85-0-0-0': 98,
 '38-186-0-0-0': 99,
 '38-22-0-0-0': 100,
 '4-74-0-0-0': 101,
 '2-102-1032-0-0': 102,
 '15-182-400-0-0': 103,
 '2-176-0-0-0': 104,
 '15-468-491-0-0': 105,
 '12-66-0-0-0': 106,
 '20-65-166-0-0': 107,
 '10-0-0-0-0': 108,
 '2-92-214-0-0': 109,
 '4-97-0-0-0': 110,
 '21-580-0-0-0': 111,
 '12-27-0-0-0': 112,
 '2-86-173-0-0': 113,
 '12-0-0-0-0': 114,
 '20-378-0-0-0': 115,
 '2-130-0-0-0': 116,
 '38-1-0-0-0': 117,
 '38-6-16-763-1193': 118,
 '2-86-0-0-0': 119,
 '2-46-1060-0-0': 120,
 '12-31-439-0-0': 121,
 '2-92-0-0-0': 122,
 '15-495-0-0-0': 123,
 '17-94-0-0-0': 124,
 '2-130-741-0-0': 125,
 '17-49-0-0-0': 126,
 '9-651-493-0-0': 127,
 '1235-0-0-0-0': 128,
 '2-46-0-0-0': 129,
 '2-92-81-0-0': 130,
 '1235-18-538-0-0': 131,
 '2-0-0-0-0': 132,
 '12-26-0-0-0': 133,
 '14-19-0-0-0': 134,
 '12-314-0-0-0': 135,
 '17-103-0-0-0': 136,
 '9-169-0-0-0': 137,
 '38-6-0-0-0': 138,
 '38-47-0-0-0': 139,
 '12-31-167-0-0': 140,
 '15-184-0-0-0': 141,
 '17-0-0-0-0': 142,
 '1235-107-0-0-0': 143,
 '38-250-0-0-0': 144,
 '5-444-0-0-0': 145,
 '20-188-0-0-0': 146,
 '2-118-0-0-0': 147,
 '15-337-0-0-0': 148,
 '12-98-0-0-0': 149,
 '20-65-43-0-0': 150,
 '15-182-0-0-0': 151}

In [211]:
labels['label1_count']

16

In [212]:


def parse_tfr_element(element):
    #use the same structure as above; it's kinda an outline of the structure we now want to create
    data = {
        'emb' : tf.io.FixedLenFeature([], tf.string),
        'track_id' : tf.io.FixedLenFeature([], tf.int64),
    }
    
    content = tf.io.parse_single_example(element, data)

    track_id = content['track_id']
    emb = content['emb']
    

    #get our 'feature'-- our image -- and reshape it appropriately
    feature = tf.io.parse_tensor(emb, out_type=tf.float32)
    return (feature, track_id)


def get_dataset(filename):
    #create the dataset
    dataset = tf.data.TFRecordDataset(filename)

    #pass every single feature through our mapping function
    dataset = dataset.map(
        parse_tfr_element
    )

    return dataset

In [213]:
import numpy as np


def load_dataset(path,dataset=args.embeddings):
    tfrecords_path = os.path.join(path,'tfrecords',dataset)
    
    
    tfrecords_path = [os.path.join(tfrecords_path,path) for path in os.listdir(tfrecords_path)]
    dataset = get_dataset(tfrecords_path)
    
    df = pd.DataFrame(
        dataset.as_numpy_iterator(),
        columns=['feature', 'track_id']
    )
        
    df.dropna(inplace=True)
    
    
    try:
        df.feature = df.feature.apply(lambda x: x[0] if x.shape[0] != 0 else None)
    except:
        print(x)
    
    return df

In [214]:
tracks_df['labels_5'].value_counts()

labels_5
1235-0-0-0-0      618
38-0-0-0-0        586
10-76-0-0-0       441
1235-107-0-0-0    375
15-0-0-0-0        358
                 ...
9-651-493-0-0       1
2-46-808-0-0        1
2-86-173-0-0        1
2-176-0-0-0         1
20-465-0-0-0        1
Name: count, Length: 152, dtype: int64

In [215]:
def __split_data__(group, percentage=0.1):
    if len(group) == 1:
        return group, group

    shuffled = shuffle(group.values)
    finish_test = int(ceil(len(group) * percentage))

    first = pd.DataFrame(shuffled[:finish_test], columns=group.columns)
    second = pd.DataFrame(shuffled[finish_test:], columns=group.columns)

    return first, second

In [216]:
def select_dataset(tracks_df):
    
#     dataset_testset_path = os.path.join(tfrecord_path,'test')
#     dataset_validationset_path = os.path.join(tfrecord_path,'val')
#     dataset_trainset_path = os.path.join(tfrecord_path,'train')
    
    df = load_dataset(args.dataset_path,dataset=args.embeddings)
    
    df.dropna(inplace=True)
    
    tracks_df = tracks_df.merge(df, on='track_id')
    
    tracks_df.loc[:,'labels_1'] = tracks_df.labels_1.astype(str).progress_apply(lambda x: labels['label1'][x])
    tracks_df.loc[:,'labels_2'] = tracks_df.labels_2.astype(str).progress_apply(lambda x: labels['label2'][x])
    tracks_df.loc[:,'labels_3'] = tracks_df.labels_3.astype(str).progress_apply(lambda x: labels['label3'][x])
    tracks_df.loc[:,'labels_4'] = tracks_df.labels_4.astype(str).progress_apply(lambda x: labels['label4'][x])
    tracks_df.loc[:,'labels_5'] = tracks_df.labels_5.astype(str).progress_apply(lambda x: labels['label5'][x])
    
    tests = []
    trains = []
    validations = []
    groups = tracks_df.groupby("labels_5")
    
    
    count = 0
    items_count = 0
    total = len(groups)
    total_items = len(tracks_df)
    oversampling_size = 30  # int(group_sizes.mean() + group_sizes.std() * 2)
    print(f"oversampling_size: {oversampling_size}")

    for code, group in groups:
        test, train_to_split = __split_data__(group, 0.01)  # 10%
        train_to_split = train_to_split
        validation, train = __split_data__(train_to_split, 0.01)  # %1

        tests.append(test)
        validations.append(validation)

        ## this increase the numner of samples when classes has low quantity
        count_train = len(train)
        if count_train < oversampling_size:
            train = train.sample(oversampling_size, replace=True)

        trains.append(train)

        count += 1
        items_count += count_train
        
        
    df_test = pd.concat(tests, sort=False).sample(frac=1).reset_index(drop=True)
    # .to_csv(dataset_testset_path, index=False,quoting=csv.QUOTE_ALL)
    df_val = pd.concat(validations, sort=False).sample(frac=1).reset_index(drop=True)
    df_train = pd.concat(trains, sort=False).sample(frac=1).reset_index(drop=True)

    return df_train,df_test,df_val

In [217]:
df_train,df_test,df_val = select_dataset(tracks_df)

2023-06-30 16:09:05.521997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9574 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5
2023-06-30 16:09:05.720582: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [11]
	 [[{{node Placeholder/_0}}]]

  0%|          | 0/10417 [00:00<?, ?it/s]

  0%|          | 0/10417 [00:00<?, ?it/s]

  0%|          | 0/10417 [00:00<?, ?it/s]

  0%|          | 0/10417 [00:00<?, ?it/s]

  0%|          | 0/10417 [00:00<?, ?it/s]

oversampling_size: 30

In [218]:
df_train

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5,feature
0,22819,[38],12,43,202,383,55,"[0.004490634, 0.013361434, 0.12729214, -0.0138..."
1,94704,"[21, 811]",6,98,166,378,84,"[-0.039904136, 0.049545426, -0.07147303, -0.04..."
2,109693,[38],12,43,202,383,55,"[0.072292924, 0.025438845, 0.012072344, -0.048..."
3,29717,"[10, 76]",14,131,225,414,97,"[-0.012395273, -0.051690966, -0.029622316, 0.0..."
4,62467,[38],12,43,202,383,55,"[0.014572322, 0.034484398, 0.06025661, -0.0166..."
...,...,...,...,...,...,...,...,...
11625,113632,"[12, 25, 89]",2,124,265,396,79,"[-0.035040677, -0.029024461, 0.1216804, -0.101..."
11626,84693,"[15, 183]",7,128,174,313,43,"[0.14998199, -0.018046498, 0.02862523, -0.0312..."
11627,119176,[15],7,53,149,421,95,"[0.027305255, 0.03161931, -0.041388016, -0.049..."
11628,106357,"[38, 250]",12,31,143,391,144,"[0.053939093, 0.00019001961, 0.023060521, 0.04..."
11629,134648,"[12, 25, 71]",2,124,239,304,78,"[0.1670642, -0.019455642, 0.09562749, 0.054682..."

In [219]:
def _bytes_feature(value):
  ### Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))): # if value ist tensor
        value = value.numpy() # get value of tensor
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def _float_feature(value):
  ### Returns a floast_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64List_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def _int64_feature(value):
  ###  Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def serialize_array(array):
    array = tf.io.serialize_tensor(array)
    return array

In [220]:
def parse_single_music(data,labels):
    track_id, _, cat1, cat2, cat3, cat4, cat5, music = data
    
    
    label1 = np.array([cat1, labels['label1_count']], np.int64)
    label2 = np.array([cat2, labels['label2_count']], np.int64)
    label3 = np.array([cat3, labels['label3_count']], np.int64)
    label4 = np.array([cat4, labels['label4_count']], np.int64)
    label5 = np.array([cat5, labels['label5_count']], np.int64)
    
    
    
    #define the dictionary -- the structure -- of our single example
    data = {
        'label1': _int64List_feature(label1),
        'label2': _int64List_feature(label2),
        'label3': _int64List_feature(label3),
        'label4': _int64List_feature(label4),
        'label5': _int64List_feature(label5),
        # 'features' : _bytes_feature(serialize_array(music)),
        'features' : _float_feature(music),
        'track_id' : _int64_feature(track_id)
    }
    #create an Example, wrapping the single features
    out = tf.train.Example(features=tf.train.Features(feature=data))

    return out

In [221]:
def generate_tf_record(df,tf_path='val'):
    create_dir(tf_path)
    
    
    batch_size = 1024 * 50 # 50k records from each file batch
    count = 0
    total = math.ceil(len(df) / batch_size)

    for i in range(0, len(df), batch_size):
        batch_df = df[i:i+batch_size]
        
        tfrecords = [parse_single_music(data, labels) for data in batch_df.values]
        
        path = f"{tf_path}/{str(count).zfill(10)}.tfrecord"
        
        #with tf.python_io.TFRecordWriter(path) as writer:
        with tf.io.TFRecordWriter(path) as writer:
            for tfrecord in tfrecords:
                writer.write(tfrecord.SerializeToString())

        print(f"{count} {len(tfrecords)} {path}")
        count += 1
        print(f"{count}/{total} batchs / {count * batch_size} processed")

    print(f"{count}/{total} batchs / {len(df)} processed")
    
    return tf_path

In [222]:
tfrecord_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords'

In [223]:
val_path = generate_tf_record(df_val,tf_path=os.path.join(tfrecord_path,'val'))

0 208 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/val/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 208 processed

In [224]:
test_path = generate_tf_record(df_test,tf_path=os.path.join(tfrecord_path,'test'))

0 209 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/test/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 209 processed

In [225]:
train_path = generate_tf_record(df_train,tf_path=os.path.join(tfrecord_path,'train'))

0 11630 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/train/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 11630 processed

In [226]:
def create_metadata(metadata_path):

    with open(metadata_path, 'w+') as f:
        f.write(json.dumps({
            'sequence_size': args.sequence_size,
            'n_levels': labels_size,
            'num_nodes_per_level':num_nodes_per_level,
            'num_classes_per_node':num_classes_per_node,
            'labels_size': [labels['label1_count'],labels['label2_count'],
                           labels['label3_count'],labels['label4_count'],
                           labels['label5_count']],
            'val_path': val_path,
            'train_path': train_path,
            'test_path': test_path,
            'trainset_count': len(df_train),
            'validationset_count': len(df_val),
            'testset_count': len(df_test)
        }))

In [227]:
create_metadata(metadata_path)

In [228]:
job_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample'

In [229]:
tracks_df.to_csv(os.path.join(job_path,"tracks.csv"),index=False)

In [230]:
with open(categories_labels_path, 'r') as f:
    labels = json.loads(f.read())

In [231]:
levels_size = {'level1_size': labels['label1_count']-1,
        'level2_size': labels['label2_count']-1,
        'level3_size': labels['label3_count']-1,
        'level4_size': labels['label4_count']-1,
        'level5_size': labels['label5_count']-1}

In [232]:
levels_size['level1_size']

15