In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
import json
import ast
import os
import csv
import math
from sklearn.utils import shuffle
from math import ceil
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm

2023-07-10 17:22:41.973067: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-10 17:22:43.567322: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [3]:
tqdm.pandas()

In [4]:

args = pd.Series({
    "root_dir":"/mnt/disks/data/",
    "dataset_path":"/mnt/disks/data/fma/fma_large",
    "embeddings":"music_style",
    "sequence_size": 1280,
    "train_id": "hierarchical_local_sample",
    'sample_size': 0.1
})

In [5]:

base_path = "/mnt/disks/data/fma/trains"


job_path = os.path.join(base_path,args.train_id)


tfrecord_path = os.path.join(job_path,"tfrecords")

# In[16]:

base_path = os.path.join(args.root_dir,"fma")

# In[17]:

models_path = os.path.join(args.root_dir,"models")


metadata_path_fma = os.path.join(base_path,"fma_metadata")

# In[18]:

metadata_path = os.path.join(job_path,"metadata.json")


categories_labels_path = os.path.join(job_path,"labels.json")

In [6]:


def __load_json__(path):
    with open(path, 'r') as f:
        tmp = json.loads(f.read())

    return tmp

In [7]:

def create_dir(path):
    # checking if the directory demo_folder2 
    # exist or not.
    if not os.path.isdir(path):

        # if the demo_folder2 directory is 
        # not present then create it.
        os.makedirs(path)
    return True

In [8]:
import shutil
shutil.rmtree(job_path)

In [9]:
create_dir(job_path)

True

## Load genres file. Contains relationships beetwen genres

In [10]:
genres_df = pd.read_csv(os.path.join(metadata_path_fma,'genres.csv'))

In [11]:
genres_df

     genre_id  #tracks  parent          title  top_level
0           1     8693      38    Avant-Garde         38
1           2     5271       0  International          2
2           3     1752       0          Blues          3
3           4     4126       0           Jazz          4
4           5     4106       0      Classical          5
..        ...      ...     ...            ...        ...
158      1032       60     102        Turkish          2
159      1060       30      46          Tango          2
160      1156       26     130           Fado          2
161      1193       72     763      Christmas         38
162      1235    14938       0   Instrumental       1235

[163 rows x 5 columns]

In [12]:
genres_df[genres_df['genre_id'] == 495]

     genre_id  #tracks  parent      title  top_level
136       495     2061      15  Downtempo         15

In [13]:
# Cria um dicionário que associa o ID de cada música aos IDs de seus gêneros musicais
tracks_df = pd.read_csv(os.path.join(metadata_path_fma,'tracks_valid.csv'))

In [14]:
tracks_df = tracks_df.sample(frac=args.sample_size)

In [15]:
tracks_df.sample(20)

,track_id,track_title,valid_genre
58117,87376,Motif Five,['42']
81825,124473,QUANTUM ENIGMA,['43']
68059,106516,The Crime,"['15', '76', '314']"
25833,40498,Le Sacre du Printemps (Le Sacrifice),"['5', '31', '38']"
7699,13511,Sanity Claus,"['15', '32', '71', '763']"
85226,129183,Just A Blip,"['26', '66', '1235']"
60565,92528,All Tomorrow's Promises,"['12', '66', '76']"
68877,107547,HHH - Kosta T & Ghofra Z,"['1', '18', '38', '107', '250', '514', '1235']"
90330,135886,Zinc Honey and Lemon,"['4', '107', '1235']"
88621,133391,She Don't,['12']
11949,19885,All Of This PAIN - Smallean's Lament,['247']
43669,65785,Four Sides,['5']
4512,9042,"Into Infinity ""ear"" loop",['42']
13995,22959,Did you read in the seabooks of the old fashio...,"['10', '17', '103']"
73780,113914,140 blood suspition,"['15', '811']"
53867,81898,Nobody has had any dinner between Dartington a...,"['30', '514']"
89804,134886,A nice short intermission,"['15', '107', '495']"
14124,23146,Ciao,"['5', '187']"
8103,14041,I'm Getting Some,"['27', '76']"
99094,147645,"One Day, We Will Awake 153 Light Years Away","['38', '107']"

In [16]:
tracks_df.valid_genre.values

array(["['15']", "['109']", "['13', '15', '42']", ..., "['42']", "['25']",
       "['46']"], dtype=object)

In [17]:
tracks_df.track_title

93290                     Orb-O
72512                    Osario
62379              Here And Now
90791    Unanonymous Alcoholics
90787                 The Gorge
                  ...
60899       Field and track lll
74667                   Nosgoth
42699                      exit
350       When My Ship Comes In
35515                   saquito
Name: track_title, Length: 10419, dtype: object

In [18]:
## Get complete genre structure
def get_all_structure(estrutura,df_genres):
    ## Get structure from df_genres
    def get_all_structure_from_df(estrutura,df_genres,structure=[]):
        if estrutura == 0:
            return structure
        else:
            structure.append(int(estrutura))
            get_all_structure_from_df(df_genres[df_genres["genre_id"]==int(estrutura)].parent.values[0],df_genres,structure)
            return structure
    
    return get_all_structure_from_df(estrutura,df_genres,structure=[])

In [19]:
# tracks_df['valid_genre'] = tracks_df.track_genres.apply(lambda x: x.strip('][').split(', ') if x != '[]' else None)
tracks_df['valid_genre'] = tracks_df.valid_genre.apply(lambda x: ast.literal_eval(x))

In [20]:
tracks_df['last_genre_id'] = tracks_df.valid_genre.apply(lambda x:x[-1] if x != None else None)

In [21]:
tracks_df.sample(20)

,track_id,track_title,valid_genre,last_genre_id
84154,127639,Fish Attack !!!!,"[12, 32]",32
52838,80582,If Only She Knew,"[12, 27, 103]",103
18424,29948,Land-O-Lakes,[21],21
5507,10497,Made Of Stone,"[17, 27, 33]",33
91569,137521,Mystic Road of Saptari,"[18, 38, 42]",42
89534,134542,Iron Animals,"[38, 47, 107]",107
47950,71778,Zavel,[15],15
101080,150249,Salubri,"[70, 107]",107
78158,119643,"Side B, Track 1 (Mea Deserets)","[1, 17]",17
26612,41469,Carsten has to go back,"[15, 42, 107, 286]",286
57367,86285,HYPNAGOGIC,"[15, 38, 236]",236
93621,140017,Welcome Aboard,"[107, 183, 236, 495]",495
49914,74658,Poseidon's Choir,"[27, 76, 125]",125
93050,139200,When Johnny Comes Marching Home (USA). Johnny ...,"[17, 441]",441
93752,140210,In Theory,"[15, 76, 1235]",1235
54371,82454,Accession,"[15, 183, 236]",236
88669,133439,Horse ride 4,"[18, 1235]",1235
20884,33448,Live@Laptopradio_7_28_2010,[41],41
1490,1870,Esoteric Focus,[15],15
92822,138944,The Only Thing,"[103, 137]",137

In [22]:
tracks_df.dropna(inplace=True)

In [23]:
tracks_df

       track_id             track_title     valid_genre last_genre_id
93290    139589                   Orb-O            [15]            15
72512    112343                  Osario           [109]           109
62379     95666            Here And Now    [13, 15, 42]            42
90791    136545  Unanonymous Alcoholics   [25, 45, 109]           109
90787    136541               The Gorge  [26, 47, 1235]          1235
...         ...                     ...             ...           ...
60899     93110     Field and track lll        [30, 38]            38
74667    115115                 Nosgoth            [76]            76
42699     64586                    exit            [42]            42
350         573   When My Ship Comes In            [25]            25
35515     54581                 saquito            [46]            46

[10419 rows x 4 columns]

In [24]:
tracks_df['full_genre_id'] = tracks_df.last_genre_id.progress_apply(lambda x: get_all_structure(x,genres_df)[::-1])

  0%|          | 0/10419 [00:00<?, ?it/s]

In [25]:
tracks_df.full_genre_id

93290             [15]
72512    [12, 25, 109]
62379         [15, 42]
90791    [12, 25, 109]
90787           [1235]
             ...
60899             [38]
74667         [10, 76]
42699         [15, 42]
350           [12, 25]
35515          [2, 46]
Name: full_genre_id, Length: 10419, dtype: object

In [26]:
tracks_df.columns

Index(['track_id', 'track_title', 'valid_genre', 'last_genre_id',
       'full_genre_id'],
      dtype='object')

In [27]:
tracks_df = tracks_df[['track_id','full_genre_id']]

In [28]:
tracks_df.full_genre_id.values

array([list([15]), list([12, 25, 109]), list([15, 42]), ...,
       list([15, 42]), list([12, 25]), list([2, 46])], dtype=object)

In [29]:
tracks_df.full_genre_id.info

<bound method Series.info of 93290             [15]
72512    [12, 25, 109]
62379         [15, 42]
90791    [12, 25, 109]
90787           [1235]
             ...
60899             [38]
74667         [10, 76]
42699         [15, 42]
350           [12, 25]
35515          [2, 46]
Name: full_genre_id, Length: 10419, dtype: object>

In [30]:
labels_size = tracks_df.full_genre_id.apply(lambda x: len(x))

In [31]:
labels_size = int(labels_size.max())

In [32]:
type(labels_size)

int

### Parse of label to structure

In [33]:
### Function for parse label to sctructure of hierarhical scheme

def parse_label(label,label_size=5):
    # label = label.split('-')
    # preencher com 0 no caso de haver menos de 5 níveis
    labels = np.zeros(label_size,dtype=int)
    for i, label in enumerate(label):
        if i == 5:
            break
        # Aqui você pode fazer a conversão do label em um índice inteiro usando um dicionário ou outro método
        # Neste exemplo, estou apenas usando a posição da label na lista como índice
        labels[i] = label
    return labels

In [34]:
parsed_labels = tracks_df.full_genre_id.apply(lambda x: parse_label(x))

In [35]:
parsed_labels

93290       [15, 0, 0, 0, 0]
72512    [12, 25, 109, 0, 0]
62379      [15, 42, 0, 0, 0]
90791    [12, 25, 109, 0, 0]
90787     [1235, 0, 0, 0, 0]
                ...
60899       [38, 0, 0, 0, 0]
74667      [10, 76, 0, 0, 0]
42699      [15, 42, 0, 0, 0]
350        [12, 25, 0, 0, 0]
35515       [2, 46, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [36]:
tracks_df['full_genre_id']

93290             [15]
72512    [12, 25, 109]
62379         [15, 42]
90791    [12, 25, 109]
90787           [1235]
             ...
60899             [38]
74667         [10, 76]
42699         [15, 42]
350           [12, 25]
35515          [2, 46]
Name: full_genre_id, Length: 10419, dtype: object

In [37]:
parsed_labels

93290       [15, 0, 0, 0, 0]
72512    [12, 25, 109, 0, 0]
62379      [15, 42, 0, 0, 0]
90791    [12, 25, 109, 0, 0]
90787     [1235, 0, 0, 0, 0]
                ...
60899       [38, 0, 0, 0, 0]
74667      [10, 76, 0, 0, 0]
42699      [15, 42, 0, 0, 0]
350        [12, 25, 0, 0, 0]
35515       [2, 46, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [63]:
def convert_label_to_string(x,level=2,string=False):
    
    if string:
        return '-'.join([str(value) for value in x[:level+1]])
    
    return x[level]

In [64]:
tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0,string=True))
tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1,string=True))
tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2,string=True))
tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3,string=True))
tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4,string=True))

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

In [65]:
# tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0))
# tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1))
# tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2))
# tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3))
# tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4))

In [66]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(["38","1235"])]

In [67]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
93290,139589,[15],15,15-0,15-0-0,15-0-0-0,15-0-0-0-0
72512,112343,"[12, 25, 109]",12,12-25,12-25-109,12-25-109-0,12-25-109-0-0
62379,95666,"[15, 42]",15,15-42,15-42-0,15-42-0-0,15-42-0-0-0
90791,136545,"[12, 25, 109]",12,12-25,12-25-109,12-25-109-0,12-25-109-0-0
90787,136541,[1235],1235,1235-0,1235-0-0,1235-0-0-0,1235-0-0-0-0
...,...,...,...,...,...,...,...
60899,93110,[38],38,38-0,38-0-0,38-0-0-0,38-0-0-0-0
74667,115115,"[10, 76]",10,10-76,10-76-0,10-76-0-0,10-76-0-0-0
42699,64586,"[15, 42]",15,15-42,15-42-0,15-42-0-0,15-42-0-0-0
350,573,"[12, 25]",12,12-25,12-25-0,12-25-0-0,12-25-0-0-0
35515,54581,"[2, 46]",2,2-46,2-46-0,2-46-0-0,2-46-0-0-0

In [68]:
tracks_df['labels_4'].value_counts()

labels_4
38-0-0-0        633
1235-0-0-0      620
1235-107-0-0    408
10-76-0-0       401
21-0-0-0        362
               ...
2-46-1060-0       2
2-86-173-0        1
20-65-189-0       1
20-465-0-0        1
2-176-0-0         1
Name: count, Length: 150, dtype: int64

In [69]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0        633
1235-0-0-0-0      620
1235-107-0-0-0    408
10-76-0-0-0       401
21-0-0-0-0        362
                 ...
20-374-0-0-0        2
2-86-173-0-0        1
20-65-189-0-0       1
20-465-0-0-0        1
2-176-0-0-0         1
Name: count, Length: 151, dtype: int64

In [70]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(['3','14'])]

In [71]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
93290,139589,[15],15,15-0,15-0-0,15-0-0-0,15-0-0-0-0
72512,112343,"[12, 25, 109]",12,12-25,12-25-109,12-25-109-0,12-25-109-0-0
62379,95666,"[15, 42]",15,15-42,15-42-0,15-42-0-0,15-42-0-0-0
90791,136545,"[12, 25, 109]",12,12-25,12-25-109,12-25-109-0,12-25-109-0-0
90787,136541,[1235],1235,1235-0,1235-0-0,1235-0-0-0,1235-0-0-0-0
...,...,...,...,...,...,...,...
60899,93110,[38],38,38-0,38-0-0,38-0-0-0,38-0-0-0-0
74667,115115,"[10, 76]",10,10-76,10-76-0,10-76-0-0,10-76-0-0-0
42699,64586,"[15, 42]",15,15-42,15-42-0,15-42-0-0,15-42-0-0-0
350,573,"[12, 25]",12,12-25,12-25-0,12-25-0-0,12-25-0-0-0
35515,54581,"[2, 46]",2,2-46,2-46-0,2-46-0-0,2-46-0-0-0

In [72]:
categories_df = pd.DataFrame({'level1':tracks_df.labels_1.unique()})

In [73]:
categories_df = tracks_df[['labels_1','labels_2','labels_3','labels_4','labels_5']].drop_duplicates()

In [74]:
categories_df

      labels_1 labels_2   labels_3     labels_4       labels_5
93290       15     15-0     15-0-0     15-0-0-0     15-0-0-0-0
72512       12    12-25  12-25-109  12-25-109-0  12-25-109-0-0
62379       15    15-42    15-42-0    15-42-0-0    15-42-0-0-0
90787     1235   1235-0   1235-0-0   1235-0-0-0   1235-0-0-0-0
94901       12    12-25    12-25-0    12-25-0-0    12-25-0-0-0
...        ...      ...        ...          ...            ...
83676        9      9-0      9-0-0      9-0-0-0      9-0-0-0-0
98180        2     2-86   2-86-173   2-86-173-0   2-86-173-0-0
30887       20    20-65  20-65-189  20-65-189-0  20-65-189-0-0
11886       20   20-465   20-465-0   20-465-0-0   20-465-0-0-0
12872        2    2-176    2-176-0    2-176-0-0    2-176-0-0-0

[151 rows x 5 columns]

In [75]:
# categories_df['level1'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:1]))
# categories_df['level2'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:2]))
# categories_df['level3'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:3]))
# categories_df['level4'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:4]))

In [76]:
categories_df

      labels_1 labels_2   labels_3     labels_4       labels_5
93290       15     15-0     15-0-0     15-0-0-0     15-0-0-0-0
72512       12    12-25  12-25-109  12-25-109-0  12-25-109-0-0
62379       15    15-42    15-42-0    15-42-0-0    15-42-0-0-0
90787     1235   1235-0   1235-0-0   1235-0-0-0   1235-0-0-0-0
94901       12    12-25    12-25-0    12-25-0-0    12-25-0-0-0
...        ...      ...        ...          ...            ...
83676        9      9-0      9-0-0      9-0-0-0      9-0-0-0-0
98180        2     2-86   2-86-173   2-86-173-0   2-86-173-0-0
30887       20    20-65  20-65-189  20-65-189-0  20-65-189-0-0
11886       20   20-465   20-465-0   20-465-0-0   20-465-0-0-0
12872        2    2-176    2-176-0    2-176-0-0    2-176-0-0-0

[151 rows x 5 columns]

In [77]:
def get_labels_name(x,genres_df):
    levels = 5
    full_name = []
    last_level = 0
    genre_root = ""
    for genre in x.split('-'):
        genre_df = genres_df[genres_df['genre_id'] == int(genre)]
        if genre_df.empty:
            genre_name = genre_root 
        else:
            genre_name = genre_df.title.values.tolist()[0]
            genre_root = genre_name
        
        full_name.append(genre_name)
    full_name = '>'.join(full_name)
        
    return full_name
    # return genres_df[genres_df['genre_id'] == int(x)].title.values.tolist()[0]

In [78]:
categories_df['level5_name'] = categories_df.labels_5.apply(lambda x: get_labels_name(x,genres_df))

In [79]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name
93290,15,15-0,15-0-0,15-0-0-0,15-0-0-0-0,Electronic>Electronic>Electronic>Electronic>El...
72512,12,12-25,12-25-109,12-25-109-0,12-25-109-0-0,Rock>Punk>Hardcore>Hardcore>Hardcore
62379,15,15-42,15-42-0,15-42-0-0,15-42-0-0-0,Electronic>Ambient Electronic>Ambient Electron...
90787,1235,1235-0,1235-0-0,1235-0-0-0,1235-0-0-0-0,Instrumental>Instrumental>Instrumental>Instrum...
94901,12,12-25,12-25-0,12-25-0-0,12-25-0-0-0,Rock>Punk>Punk>Punk>Punk
...,...,...,...,...,...,...
83676,9,9-0,9-0-0,9-0-0-0,9-0-0-0-0,Country>Country>Country>Country>Country
98180,2,2-86,2-86-173,2-86-173-0,2-86-173-0-0,International>Indian>N. Indian Traditional>N. ...
30887,20,20-65,20-65-189,20-65-189-0,20-65-189-0-0,Spoken>Radio>Talk Radio>Talk Radio>Talk Radio
11886,20,20-465,20-465-0,20-465-0-0,20-465-0-0-0,Spoken>Musical Theater>Musical Theater>Musical...
12872,2,2-176,2-176-0,2-176-0-0,2-176-0-0-0,International>Pacific>Pacific>Pacific>Pacific

In [80]:
def __create_labels__(categories_df):
    data = {
        "label1": {},
        "label2": {},
        "label3": {},
        "label4": {},
        "label5": {},
        "label1_inverse": [],
        "label2_inverse": [],
        "label3_inverse": [],
        "label4_inverse": [],
        "label5_inverse": [],
        "label1_name": {},
        "label2_name": {},
        "label3_name": {},
        "label4_name": {},
        "label5_name": {},
    }

    idx = 0
    
    for id_x, cat in enumerate(set(categories_df.labels_1.values.tolist())):
        data['label1'][cat] = idx
        data['label1_inverse'].append(cat)
        data['label1_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_2.values.tolist())):
        data['label2'][cat] = idx
        data['label2_inverse'].append(cat)
        data['label2_count'] = idx + 1
        idx+=1
        
    for id_x, cat in enumerate(set(categories_df.labels_3.values.tolist())):
        data['label3'][cat] = idx
        data['label3_inverse'].append(cat)
        data['label3_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_4.values.tolist())):
        data['label4'][cat] = idx
        data['label4_inverse'].append(cat)
        data['label4_count'] = idx + 1
        idx+=1
        
    for idx, cat in enumerate(set(categories_df.labels_5.values.tolist())):
        data['label5'][cat] = idx
        data['label5_inverse'].append(cat)
        data['label5_count'] = idx + 1
        idx+=1
        
    for cat5,cat1,cat2,cat3,cat4,name5 in categories_df.values:
        
        name1 = '>'.join(name5.split('>')[:1])
        name2 = '>'.join(name5.split('>')[:2])
        name3 = '>'.join(name5.split('>')[:3])
        name4 = '>'.join(name5.split('>')[:4])
        
        
        data['label1_name'][cat1] = name1
        data['label2_name'][cat2] = name2
        data['label3_name'][cat3] = name3
        data['label4_name'][cat4] = name4
        data['label5_name'][cat5] = name5
        
    return data

In [81]:
with open(categories_labels_path, 'w+') as f:
    f.write(json.dumps(__create_labels__(categories_df)))

In [82]:
labels  = __create_labels__(categories_df)

In [83]:
labels

{'label1': {'12': 0,
  '3': 1,
  '4': 2,
  '13': 3,
  '9': 4,
  '38': 5,
  '5': 6,
  '21': 7,
  '15': 8,
  '14': 9,
  '8': 10,
  '1235': 11,
  '10': 12,
  '20': 13,
  '17': 14,
  '2': 15},
 'label2': {'15-695': 16,
  '12-70': 17,
  '12-85': 18,
  '12-26': 19,
  '10-0': 20,
  '15-337': 21,
  '2-176': 22,
  '14-11': 23,
  '5-322': 24,
  '5-659': 25,
  '12-66': 26,
  '20-188': 27,
  '1235-18': 28,
  '38-1': 29,
  '20-65': 30,
  '17-103': 31,
  '15-468': 32,
  '2-130': 33,
  '2-0': 34,
  '2-102': 35,
  '5-442': 36,
  '12-314': 37,
  '13-170': 38,
  '15-286': 39,
  '15-296': 40,
  '13-810': 41,
  '38-250': 42,
  '20-428': 43,
  '12-58': 44,
  '15-495': 45,
  '2-79': 46,
  '20-465': 47,
  '21-539': 48,
  '3-567': 49,
  '5-443': 50,
  '20-0': 51,
  '12-88': 52,
  '12-25': 53,
  '12-27': 54,
  '15-0': 55,
  '12-359': 56,
  '15-236': 57,
  '15-182': 58,
  '15-184': 59,
  '12-45': 60,
  '1235-267': 61,
  '4-906': 62,
  '21-542': 63,
  '4-179': 64,
  '9-169': 65,
  '10-76': 66,
  '9-651': 67,
  '38-30': 68,
  '9-63': 69,
  '21-100': 70,
  '38-22': 71,
  '20-374': 72,
  '38-47': 73,
  '21-811': 74,
  '38-41': 75,
  '21-0': 76,
  '1235-0': 77,
  '15-181': 78,
  '2-77': 79,
  '17-94': 80,
  '17-33': 81,
  '3-0': 82,
  '4-74': 83,
  '15-297': 84,
  '17-49': 85,
  '15-183': 86,
  '38-514': 87,
  '38-456': 88,
  '38-186': 89,
  '10-362': 90,
  '2-232': 91,
  '20-138': 92,
  '20-378': 93,
  '8-0': 94,
  '12-440': 95,
  '38-0': 96,
  '2-46': 97,
  '2-118': 98,
  '21-580': 99,
  '9-0': 100,
  '38-32': 101,
  '38-224': 102,
  '38-6': 103,
  '5-0': 104,
  '12-36': 105,
  '17-180': 106,
  '2-177': 107,
  '14-19': 108,
  '2-171': 109,
  '4-37': 110,
  '21-693': 111,
  '2-86': 112,
  '9-137': 113,
  '1235-107': 114,
  '2-92': 115,
  '5-187': 116,
  '12-0': 117,
  '15-185': 118,
  '5-441': 119,
  '12-31': 120,
  '4-97': 121,
  '12-98': 122,
  '4-0': 123,
  '38-247': 124,
  '14-0': 125,
  '38-125': 126,
  '15-42': 127,
  '13-311': 128,
  '17-0': 129,
  '2-504': 130,
  '2-172': 131},
 'label3': {'38-250-0': 132,
  '38-186-0': 133,
  '15-297-0': 134,
  '38-514-0': 135,
  '12-85-0': 136,
  '15-181-0': 137,
  '15-296-0': 138,
  '12-88-0': 139,
  '5-322-0': 140,
  '2-177-0': 141,
  '2-130-524': 142,
  '21-100-0': 143,
  '21-693-0': 144,
  '38-1-0': 145,
  '38-0-0': 146,
  '15-181-401': 147,
  '15-182-400': 148,
  '3-567-0': 149,
  '12-98-0': 150,
  '17-49-0': 151,
  '20-138-0': 152,
  '20-65-166': 153,
  '1235-18-538': 154,
  '15-236-0': 155,
  '2-79-602': 156,
  '2-172-0': 157,
  '12-0-0': 158,
  '38-456-0': 159,
  '17-0-0': 160,
  '38-6-0': 161,
  '2-46-0': 162,
  '4-97-0': 163,
  '17-33-0': 164,
  '15-42-0': 165,
  '17-180-0': 166,
  '2-171-0': 167,
  '12-25-89': 168,
  '2-504-0': 169,
  '15-468-491': 170,
  '12-85-404': 171,
  '20-65-189': 172,
  '2-46-502': 173,
  '15-0-0': 174,
  '3-0-0': 175,
  '38-6-16': 176,
  '20-0-0': 177,
  '2-130-1156': 178,
  '4-0-0': 179,
  '2-77-0': 180,
  '21-539-0': 181,
  '10-0-0': 182,
  '5-659-0': 183,
  '2-232-0': 184,
  '12-31-439': 185,
  '20-65-0': 186,
  '2-86-173': 187,
  '9-0-0': 188,
  '4-74-0': 189,
  '1235-107-0': 190,
  '10-76-0': 191,
  '5-442-0': 192,
  '2-86-0': 193,
  '15-297-240': 194,
  '20-65-43': 195,
  '1235-18-0': 196,
  '14-11-0': 197,
  '1235-0-0': 198,
  '13-311-0': 199,
  '12-25-64': 200,
  '12-70-0': 201,
  '12-58-0': 202,
  '2-130-741': 203,
  '2-0-0': 204,
  '4-906-0': 205,
  '21-580-0': 206,
  '12-66-0': 207,
  '12-26-0': 208,
  '5-187-0': 209,
  '12-45-0': 210,
  '5-441-0': 211,
  '12-359-0': 212,
  '12-27-0': 213,
  '15-468-0': 214,
  '21-0-0': 215,
  '12-31-0': 216,
  '1235-267-0': 217,
  '38-247-0': 218,
  '2-130-619': 219,
  '15-182-0': 220,
  '8-0-0': 221,
  '2-92-0': 222,
  '13-170-0': 223,
  '9-651-0': 224,
  '12-25-111': 225,
  '13-810-0': 226,
  '14-19-0': 227,
  '17-103-0': 228,
  '14-0-0': 229,
  '20-374-0': 230,
  '2-46-1060': 231,
  '20-428-0': 232,
  '10-362-0': 233,
  '15-495-0': 234,
  '38-47-0': 235,
  '38-30-0': 236,
  '2-176-0': 237,
  '12-314-0': 238,
  '12-31-167': 239,
  '12-25-109': 240,
  '38-224-0': 241,
  '15-184-0': 242,
  '2-118-0': 243,
  '20-465-0': 244,
  '38-22-0': 245,
  '17-94-0': 246,
  '12-25-71': 247,
  '2-102-1032': 248,
  '2-102-0': 249,
  '2-92-214': 250,
  '9-137-0': 251,
  '12-440-0': 252,
  '2-130-0': 253,
  '20-188-0': 254,
  '12-26-113': 255,
  '12-36-0': 256,
  '15-183-0': 257,
  '2-79-0': 258,
  '38-41-0': 259,
  '38-125-0': 260,
  '2-92-81': 261,
  '15-695-0': 262,
  '15-337-0': 263,
  '38-6-360': 264,
  '21-811-0': 265,
  '5-0-0': 266,
  '20-378-0': 267,
  '4-37-0': 268,
  '38-32-0': 269,
  '15-286-0': 270,
  '9-169-0': 271,
  '15-185-0': 272,
  '12-31-101': 273,
  '4-179-0': 274,
  '12-45-53': 275,
  '21-542-0': 276,
  '5-443-0': 277,
  '9-63-0': 278,
  '12-25-0': 279},
 'label4': {'12-88-0-0': 280,
  '2-102-1032-0': 281,
  '9-137-0-0': 282,
  '20-374-0-0': 283,
  '15-0-0-0': 284,
  '38-250-0-0': 285,
  '2-77-0-0': 286,
  '12-66-0-0': 287,
  '12-70-0-0': 288,
  '13-311-0-0': 289,
  '20-428-0-0': 290,
  '12-31-439-0': 291,
  '20-188-0-0': 292,
  '14-19-0-0': 293,
  '17-94-0-0': 294,
  '2-92-0-0': 295,
  '38-22-0-0': 296,
  '15-337-0-0': 297,
  '12-26-113-0': 298,
  '14-0-0-0': 299,
  '2-86-173-0': 300,
  '15-468-0-0': 301,
  '12-314-0-0': 302,
  '12-26-0-0': 303,
  '38-125-0-0': 304,
  '38-456-0-0': 305,
  '38-41-0-0': 306,
  '21-693-0-0': 307,
  '38-6-0-0': 308,
  '2-92-81-0': 309,
  '10-0-0-0': 310,
  '2-92-214-0': 311,
  '21-580-0-0': 312,
  '12-36-0-0': 313,
  '38-247-0-0': 314,
  '8-0-0-0': 315,
  '2-102-0-0': 316,
  '3-0-0-0': 317,
  '1235-267-0-0': 318,
  '1235-18-538-0': 319,
  '15-183-0-0': 320,
  '9-169-0-0': 321,
  '21-811-0-0': 322,
  '17-103-0-0': 323,
  '1235-0-0-0': 324,
  '17-33-0-0': 325,
  '12-25-71-0': 326,
  '5-659-0-0': 327,
  '20-0-0-0': 328,
  '12-31-101-0': 329,
  '4-179-0-0': 330,
  '2-172-0-0': 331,
  '4-906-0-0': 332,
  '20-465-0-0': 333,
  '12-0-0-0': 334,
  '38-6-360-0': 335,
  '4-37-0-0': 336,
  '2-130-619-0': 337,
  '9-63-0-0': 338,
  '38-6-16-763': 339,
  '15-468-491-0': 340,
  '2-504-0-0': 341,
  '14-11-0-0': 342,
  '1235-18-0-0': 343,
  '2-177-0-0': 344,
  '4-97-0-0': 345,
  '38-47-0-0': 346,
  '2-130-741-0': 347,
  '12-45-0-0': 348,
  '12-25-89-0': 349,
  '20-138-0-0': 350,
  '10-76-0-0': 351,
  '2-130-0-0': 352,
  '2-46-0-0': 353,
  '15-181-0-0': 354,
  '2-176-0-0': 355,
  '12-25-109-361': 356,
  '20-65-189-0': 357,
  '15-42-0-0': 358,
  '5-322-0-0': 359,
  '12-359-0-0': 360,
  '2-0-0-0': 361,
  '5-0-0-0': 362,
  '13-810-0-0': 363,
  '15-236-0-0': 364,
  '15-297-0-0': 365,
  '12-25-109-0': 366,
  '2-46-1060-0': 367,
  '15-297-240-0': 368,
  '17-0-0-0': 369,
  '38-32-0-0': 370,
  '15-182-400-0': 371,
  '2-232-0-0': 372,
  '15-286-0-0': 373,
  '15-185-0-0': 374,
  '2-171-0-0': 375,
  '15-184-0-0': 376,
  '5-442-0-0': 377,
  '15-296-0-0': 378,
  '2-130-1156-0': 379,
  '15-495-0-0': 380,
  '4-0-0-0': 381,
  '20-378-0-0': 382,
  '38-30-0-0': 383,
  '21-100-0-0': 384,
  '1235-107-0-0': 385,
  '2-118-0-0': 386,
  '2-79-602-0': 387,
  '12-45-53-0': 388,
  '12-25-111-0': 389,
  '20-65-43-0': 390,
  '15-181-401-0': 391,
  '12-27-0-0': 392,
  '17-180-0-0': 393,
  '15-182-0-0': 394,
  '12-45-53-90': 395,
  '38-186-0-0': 396,
  '2-86-0-0': 397,
  '38-1-0-0': 398,
  '12-85-0-0': 399,
  '3-567-0-0': 400,
  '20-65-0-0': 401,
  '38-514-0-0': 402,
  '12-25-0-0': 403,
  '17-49-0-0': 404,
  '12-31-167-0': 405,
  '5-443-0-0': 406,
  '9-0-0-0': 407,
  '38-224-0-0': 408,
  '12-25-64-0': 409,
  '5-441-0-0': 410,
  '4-74-0-0': 411,
  '21-542-0-0': 412,
  '5-187-0-0': 413,
  '13-170-0-0': 414,
  '10-362-0-0': 415,
  '12-440-0-0': 416,
  '38-0-0-0': 417,
  '20-65-166-0': 418,
  '21-0-0-0': 419,
  '9-651-0-0': 420,
  '12-58-0-0': 421,
  '12-85-404-0': 422,
  '21-539-0-0': 423,
  '2-46-502-0': 424,
  '2-130-524-0': 425,
  '12-98-0-0': 426,
  '12-31-0-0': 427,
  '2-79-0-0': 428,
  '15-695-0-0': 429},
 'label5': {'12-58-0-0-0': 0,
  '21-539-0-0-0': 1,
  '38-0-0-0-0': 2,
  '12-31-167-0-0': 3,
  '12-25-0-0-0': 4,
  '10-362-0-0-0': 5,
  '12-25-71-0-0': 6,
  '4-97-0-0-0': 7,
  '1235-267-0-0-0': 8,
  '2-130-741-0-0': 9,
  '5-322-0-0-0': 10,
  '4-179-0-0-0': 11,
  '2-504-0-0-0': 12,
  '2-118-0-0-0': 13,
  '13-311-0-0-0': 14,
  '15-695-0-0-0': 15,
  '13-810-0-0-0': 16,
  '12-25-109-361-0': 17,
  '2-102-1032-0-0': 18,
  '15-183-0-0-0': 19,
  '17-103-0-0-0': 20,
  '2-86-0-0-0': 21,
  '4-74-0-0-0': 22,
  '20-374-0-0-0': 23,
  '5-659-0-0-0': 24,
  '17-49-0-0-0': 25,
  '15-182-0-0-0': 26,
  '15-182-400-0-0': 27,
  '21-100-0-0-0': 28,
  '38-456-0-0-0': 29,
  '2-46-1060-0-0': 30,
  '38-224-0-0-0': 31,
  '12-25-109-0-0': 32,
  '5-443-0-0-0': 33,
  '5-0-0-0-0': 34,
  '12-25-111-0-0': 35,
  '2-176-0-0-0': 36,
  '4-906-0-0-0': 37,
  '14-11-0-0-0': 38,
  '12-98-0-0-0': 39,
  '2-46-0-0-0': 40,
  '38-125-0-0-0': 41,
  '15-0-0-0-0': 42,
  '38-250-0-0-0': 43,
  '2-232-0-0-0': 44,
  '15-468-0-0-0': 45,
  '12-0-0-0-0': 46,
  '12-45-53-90-0': 47,
  '5-187-0-0-0': 48,
  '3-567-0-0-0': 49,
  '2-86-173-0-0': 50,
  '12-26-0-0-0': 51,
  '9-0-0-0-0': 52,
  '9-651-0-0-0': 53,
  '2-171-0-0-0': 54,
  '17-180-0-0-0': 55,
  '1235-18-0-0-0': 56,
  '10-76-0-0-0': 57,
  '38-22-0-0-0': 58,
  '20-378-0-0-0': 59,
  '15-495-0-0-0': 60,
  '2-102-0-0-0': 61,
  '12-45-53-0-0': 62,
  '8-0-0-0-0': 63,
  '12-25-89-0-0': 64,
  '38-6-360-0-0': 65,
  '15-297-240-0-0': 66,
  '38-41-0-0-0': 67,
  '38-47-0-0-0': 68,
  '5-442-0-0-0': 69,
  '21-811-0-0-0': 70,
  '21-0-0-0-0': 71,
  '38-6-16-763-1193': 72,
  '38-30-0-0-0': 73,
  '20-65-0-0-0': 74,
  '2-92-214-0-0': 75,
  '17-33-0-0-0': 76,
  '15-185-0-0-0': 77,
  '20-65-43-0-0': 78,
  '15-286-0-0-0': 79,
  '21-542-0-0-0': 80,
  '2-77-0-0-0': 81,
  '12-359-0-0-0': 82,
  '2-92-81-0-0': 83,
  '2-46-502-0-0': 84,
  '2-79-0-0-0': 85,
  '2-0-0-0-0': 86,
  '20-188-0-0-0': 87,
  '1235-107-0-0-0': 88,
  '21-580-0-0-0': 89,
  '12-31-101-0-0': 90,
  '21-693-0-0-0': 91,
  '12-88-0-0-0': 92,
  '12-440-0-0-0': 93,
  '38-186-0-0-0': 94,
  '38-6-0-0-0': 95,
  '20-65-189-0-0': 96,
  '12-45-0-0-0': 97,
  '3-0-0-0-0': 98,
  '2-130-524-0-0': 99,
  '38-514-0-0-0': 100,
  '15-337-0-0-0': 101,
  '12-25-64-0-0': 102,
  '15-181-401-0-0': 103,
  '2-172-0-0-0': 104,
  '15-236-0-0-0': 105,
  '15-297-0-0-0': 106,
  '9-169-0-0-0': 107,
  '9-63-0-0-0': 108,
  '5-441-0-0-0': 109,
  '12-27-0-0-0': 110,
  '38-247-0-0-0': 111,
  '12-31-0-0-0': 112,
  '12-85-404-0-0': 113,
  '12-66-0-0-0': 114,
  '2-79-602-0-0': 115,
  '38-32-0-0-0': 116,
  '12-26-113-0-0': 117,
  '20-65-166-0-0': 118,
  '12-70-0-0-0': 119,
  '2-130-619-0-0': 120,
  '1235-18-538-0-0': 121,
  '12-314-0-0-0': 122,
  '12-85-0-0-0': 123,
  '14-19-0-0-0': 124,
  '2-130-1156-0-0': 125,
  '15-181-0-0-0': 126,
  '20-0-0-0-0': 127,
  '17-0-0-0-0': 128,
  '14-0-0-0-0': 129,
  '1235-0-0-0-0': 130,
  '15-468-491-0-0': 131,
  '15-42-0-0-0': 132,
  '38-6-16-763-0': 133,
  '20-428-0-0-0': 134,
  '4-37-0-0-0': 135,
  '38-1-0-0-0': 136,
  '10-0-0-0-0': 137,
  '17-94-0-0-0': 138,
  '15-296-0-0-0': 139,
  '4-0-0-0-0': 140,
  '2-177-0-0-0': 141,
  '2-92-0-0-0': 142,
  '2-130-0-0-0': 143,
  '9-137-0-0-0': 144,
  '15-184-0-0-0': 145,
  '12-31-439-0-0': 146,
  '12-36-0-0-0': 147,
  '20-465-0-0-0': 148,
  '13-170-0-0-0': 149,
  '20-138-0-0-0': 150},
 'label1_inverse': ['12',
  '3',
  '4',
  '13',
  '9',
  '38',
  '5',
  '21',
  '15',
  '14',
  '8',
  '1235',
  '10',
  '20',
  '17',
  '2'],
 'label2_inverse': ['15-695',
  '12-70',
  '12-85',
  '12-26',
  '10-0',
  '15-337',
  '2-176',
  '14-11',
  '5-322',
  '5-659',
  '12-66',
  '20-188',
  '1235-18',
  '38-1',
  '20-65',
  '17-103',
  '15-468',
  '2-130',
  '2-0',
  '2-102',
  '5-442',
  '12-314',
  '13-170',
  '15-286',
  '15-296',
  '13-810',
  '38-250',
  '20-428',
  '12-58',
  '15-495',
  '2-79',
  '20-465',
  '21-539',
  '3-567',
  '5-443',
  '20-0',
  '12-88',
  '12-25',
  '12-27',
  '15-0',
  '12-359',
  '15-236',
  '15-182',
  '15-184',
  '12-45',
  '1235-267',
  '4-906',
  '21-542',
  '4-179',
  '9-169',
  '10-76',
  '9-651',
  '38-30',
  '9-63',
  '21-100',
  '38-22',
  '20-374',
  '38-47',
  '21-811',
  '38-41',
  '21-0',
  '1235-0',
  '15-181',
  '2-77',
  '17-94',
  '17-33',
  '3-0',
  '4-74',
  '15-297',
  '17-49',
  '15-183',
  '38-514',
  '38-456',
  '38-186',
  '10-362',
  '2-232',
  '20-138',
  '20-378',
  '8-0',
  '12-440',
  '38-0',
  '2-46',
  '2-118',
  '21-580',
  '9-0',
  '38-32',
  '38-224',
  '38-6',
  '5-0',
  '12-36',
  '17-180',
  '2-177',
  '14-19',
  '2-171',
  '4-37',
  '21-693',
  '2-86',
  '9-137',
  '1235-107',
  '2-92',
  '5-187',
  '12-0',
  '15-185',
  '5-441',
  '12-31',
  '4-97',
  '12-98',
  '4-0',
  '38-247',
  '14-0',
  '38-125',
  '15-42',
  '13-311',
  '17-0',
  '2-504',
  '2-172'],
 'label3_inverse': ['38-250-0',
  '38-186-0',
  '15-297-0',
  '38-514-0',
  '12-85-0',
  '15-181-0',
  '15-296-0',
  '12-88-0',
  '5-322-0',
  '2-177-0',
  '2-130-524',
  '21-100-0',
  '21-693-0',
  '38-1-0',
  '38-0-0',
  '15-181-401',
  '15-182-400',
  '3-567-0',
  '12-98-0',
  '17-49-0',
  '20-138-0',
  '20-65-166',
  '1235-18-538',
  '15-236-0',
  '2-79-602',
  '2-172-0',
  '12-0-0',
  '38-456-0',
  '17-0-0',
  '38-6-0',
  '2-46-0',
  '4-97-0',
  '17-33-0',
  '15-42-0',
  '17-180-0',
  '2-171-0',
  '12-25-89',
  '2-504-0',
  '15-468-491',
  '12-85-404',
  '20-65-189',
  '2-46-502',
  '15-0-0',
  '3-0-0',
  '38-6-16',
  '20-0-0',
  '2-130-1156',
  '4-0-0',
  '2-77-0',
  '21-539-0',
  '10-0-0',
  '5-659-0',
  '2-232-0',
  '12-31-439',
  '20-65-0',
  '2-86-173',
  '9-0-0',
  '4-74-0',
  '1235-107-0',
  '10-76-0',
  '5-442-0',
  '2-86-0',
  '15-297-240',
  '20-65-43',
  '1235-18-0',
  '14-11-0',
  '1235-0-0',
  '13-311-0',
  '12-25-64',
  '12-70-0',
  '12-58-0',
  '2-130-741',
  '2-0-0',
  '4-906-0',
  '21-580-0',
  '12-66-0',
  '12-26-0',
  '5-187-0',
  '12-45-0',
  '5-441-0',
  '12-359-0',
  '12-27-0',
  '15-468-0',
  '21-0-0',
  '12-31-0',
  '1235-267-0',
  '38-247-0',
  '2-130-619',
  '15-182-0',
  '8-0-0',
  '2-92-0',
  '13-170-0',
  '9-651-0',
  '12-25-111',
  '13-810-0',
  '14-19-0',
  '17-103-0',
  '14-0-0',
  '20-374-0',
  '2-46-1060',
  '20-428-0',
  '10-362-0',
  '15-495-0',
  '38-47-0',
  '38-30-0',
  '2-176-0',
  '12-314-0',
  '12-31-167',
  '12-25-109',
  '38-224-0',
  '15-184-0',
  '2-118-0',
  '20-465-0',
  '38-22-0',
  '17-94-0',
  '12-25-71',
  '2-102-1032',
  '2-102-0',
  '2-92-214',
  '9-137-0',
  '12-440-0',
  '2-130-0',
  '20-188-0',
  '12-26-113',
  '12-36-0',
  '15-183-0',
  '2-79-0',
  '38-41-0',
  '38-125-0',
  '2-92-81',
  '15-695-0',
  '15-337-0',
  '38-6-360',
  '21-811-0',
  '5-0-0',
  '20-378-0',
  '4-37-0',
  '38-32-0',
  '15-286-0',
  '9-169-0',
  '15-185-0',
  '12-31-101',
  '4-179-0',
  '12-45-53',
  '21-542-0',
  '5-443-0',
  '9-63-0',
  '12-25-0'],
 'label4_inverse': ['12-88-0-0',
  '2-102-1032-0',
  '9-137-0-0',
  '20-374-0-0',
  '15-0-0-0',
  '38-250-0-0',
  '2-77-0-0',
  '12-66-0-0',
  '12-70-0-0',
  '13-311-0-0',
  '20-428-0-0',
  '12-31-439-0',
  '20-188-0-0',
  '14-19-0-0',
  '17-94-0-0',
  '2-92-0-0',
  '38-22-0-0',
  '15-337-0-0',
  '12-26-113-0',
  '14-0-0-0',
  '2-86-173-0',
  '15-468-0-0',
  '12-314-0-0',
  '12-26-0-0',
  '38-125-0-0',
  '38-456-0-0',
  '38-41-0-0',
  '21-693-0-0',
  '38-6-0-0',
  '2-92-81-0',
  '10-0-0-0',
  '2-92-214-0',
  '21-580-0-0',
  '12-36-0-0',
  '38-247-0-0',
  '8-0-0-0',
  '2-102-0-0',
  '3-0-0-0',
  '1235-267-0-0',
  '1235-18-538-0',
  '15-183-0-0',
  '9-169-0-0',
  '21-811-0-0',
  '17-103-0-0',
  '1235-0-0-0',
  '17-33-0-0',
  '12-25-71-0',
  '5-659-0-0',
  '20-0-0-0',
  '12-31-101-0',
  '4-179-0-0',
  '2-172-0-0',
  '4-906-0-0',
  '20-465-0-0',
  '12-0-0-0',
  '38-6-360-0',
  '4-37-0-0',
  '2-130-619-0',
  '9-63-0-0',
  '38-6-16-763',
  '15-468-491-0',
  '2-504-0-0',
  '14-11-0-0',
  '1235-18-0-0',
  '2-177-0-0',
  '4-97-0-0',
  '38-47-0-0',
  '2-130-741-0',
  '12-45-0-0',
  '12-25-89-0',
  '20-138-0-0',
  '10-76-0-0',
  '2-130-0-0',
  '2-46-0-0',
  '15-181-0-0',
  '2-176-0-0',
  '12-25-109-361',
  '20-65-189-0',
  '15-42-0-0',
  '5-322-0-0',
  '12-359-0-0',
  '2-0-0-0',
  '5-0-0-0',
  '13-810-0-0',
  '15-236-0-0',
  '15-297-0-0',
  '12-25-109-0',
  '2-46-1060-0',
  '15-297-240-0',
  '17-0-0-0',
  '38-32-0-0',
  '15-182-400-0',
  '2-232-0-0',
  '15-286-0-0',
  '15-185-0-0',
  '2-171-0-0',
  '15-184-0-0',
  '5-442-0-0',
  '15-296-0-0',
  '2-130-1156-0',
  '15-495-0-0',
  '4-0-0-0',
  '20-378-0-0',
  '38-30-0-0',
  '21-100-0-0',
  '1235-107-0-0',
  '2-118-0-0',
  '2-79-602-0',
  '12-45-53-0',
  '12-25-111-0',
  '20-65-43-0',
  '15-181-401-0',
  '12-27-0-0',
  '17-180-0-0',
  '15-182-0-0',
  '12-45-53-90',
  '38-186-0-0',
  '2-86-0-0',
  '38-1-0-0',
  '12-85-0-0',
  '3-567-0-0',
  '20-65-0-0',
  '38-514-0-0',
  '12-25-0-0',
  '17-49-0-0',
  '12-31-167-0',
  '5-443-0-0',
  '9-0-0-0',
  '38-224-0-0',
  '12-25-64-0',
  '5-441-0-0',
  '4-74-0-0',
  '21-542-0-0',
  '5-187-0-0',
  '13-170-0-0',
  '10-362-0-0',
  '12-440-0-0',
  '38-0-0-0',
  '20-65-166-0',
  '21-0-0-0',
  '9-651-0-0',
  '12-58-0-0',
  '12-85-404-0',
  '21-539-0-0',
  '2-46-502-0',
  '2-130-524-0',
  '12-98-0-0',
  '12-31-0-0',
  '2-79-0-0',
  '15-695-0-0'],
 'label5_inverse': ['12-58-0-0-0',
  '21-539-0-0-0',
  '38-0-0-0-0',
  '12-31-167-0-0',
  '12-25-0-0-0',
  '10-362-0-0-0',
  '12-25-71-0-0',
  '4-97-0-0-0',
  '1235-267-0-0-0',
  '2-130-741-0-0',
  '5-322-0-0-0',
  '4-179-0-0-0',
  '2-504-0-0-0',
  '2-118-0-0-0',
  '13-311-0-0-0',
  '15-695-0-0-0',
  '13-810-0-0-0',
  '12-25-109-361-0',
  '2-102-1032-0-0',
  '15-183-0-0-0',
  '17-103-0-0-0',
  '2-86-0-0-0',
  '4-74-0-0-0',
  '20-374-0-0-0',
  '5-659-0-0-0',
  '17-49-0-0-0',
  '15-182-0-0-0',
  '15-182-400-0-0',
  '21-100-0-0-0',
  '38-456-0-0-0',
  '2-46-1060-0-0',
  '38-224-0-0-0',
  '12-25-109-0-0',
  '5-443-0-0-0',
  '5-0-0-0-0',
  '12-25-111-0-0',
  '2-176-0-0-0',
  '4-906-0-0-0',
  '14-11-0-0-0',
  '12-98-0-0-0',
  '2-46-0-0-0',
  '38-125-0-0-0',
  '15-0-0-0-0',
  '38-250-0-0-0',
  '2-232-0-0-0',
  '15-468-0-0-0',
  '12-0-0-0-0',
  '12-45-53-90-0',
  '5-187-0-0-0',
  '3-567-0-0-0',
  '2-86-173-0-0',
  '12-26-0-0-0',
  '9-0-0-0-0',
  '9-651-0-0-0',
  '2-171-0-0-0',
  '17-180-0-0-0',
  '1235-18-0-0-0',
  '10-76-0-0-0',
  '38-22-0-0-0',
  '20-378-0-0-0',
  '15-495-0-0-0',
  '2-102-0-0-0',
  '12-45-53-0-0',
  '8-0-0-0-0',
  '12-25-89-0-0',
  '38-6-360-0-0',
  '15-297-240-0-0',
  '38-41-0-0-0',
  '38-47-0-0-0',
  '5-442-0-0-0',
  '21-811-0-0-0',
  '21-0-0-0-0',
  '38-6-16-763-1193',
  '38-30-0-0-0',
  '20-65-0-0-0',
  '2-92-214-0-0',
  '17-33-0-0-0',
  '15-185-0-0-0',
  '20-65-43-0-0',
  '15-286-0-0-0',
  '21-542-0-0-0',
  '2-77-0-0-0',
  '12-359-0-0-0',
  '2-92-81-0-0',
  '2-46-502-0-0',
  '2-79-0-0-0',
  '2-0-0-0-0',
  '20-188-0-0-0',
  '1235-107-0-0-0',
  '21-580-0-0-0',
  '12-31-101-0-0',
  '21-693-0-0-0',
  '12-88-0-0-0',
  '12-440-0-0-0',
  '38-186-0-0-0',
  '38-6-0-0-0',
  '20-65-189-0-0',
  '12-45-0-0-0',
  '3-0-0-0-0',
  '2-130-524-0-0',
  '38-514-0-0-0',
  '15-337-0-0-0',
  '12-25-64-0-0',
  '15-181-401-0-0',
  '2-172-0-0-0',
  '15-236-0-0-0',
  '15-297-0-0-0',
  '9-169-0-0-0',
  '9-63-0-0-0',
  '5-441-0-0-0',
  '12-27-0-0-0',
  '38-247-0-0-0',
  '12-31-0-0-0',
  '12-85-404-0-0',
  '12-66-0-0-0',
  '2-79-602-0-0',
  '38-32-0-0-0',
  '12-26-113-0-0',
  '20-65-166-0-0',
  '12-70-0-0-0',
  '2-130-619-0-0',
  '1235-18-538-0-0',
  '12-314-0-0-0',
  '12-85-0-0-0',
  '14-19-0-0-0',
  '2-130-1156-0-0',
  '15-181-0-0-0',
  '20-0-0-0-0',
  '17-0-0-0-0',
  '14-0-0-0-0',
  '1235-0-0-0-0',
  '15-468-491-0-0',
  '15-42-0-0-0',
  '38-6-16-763-0',
  '20-428-0-0-0',
  '4-37-0-0-0',
  '38-1-0-0-0',
  '10-0-0-0-0',
  '17-94-0-0-0',
  '15-296-0-0-0',
  '4-0-0-0-0',
  '2-177-0-0-0',
  '2-92-0-0-0',
  '2-130-0-0-0',
  '9-137-0-0-0',
  '15-184-0-0-0',
  '12-31-439-0-0',
  '12-36-0-0-0',
  '20-465-0-0-0',
  '13-170-0-0-0',
  '20-138-0-0-0'],
 'label1_name': {'15-0': 'Electronic',
  '12-25': 'Rock',
  '15-42': 'Electronic',
  '1235-0': 'Instrumental',
  '10-76': 'Pop',
  '15-236': 'Electronic',
  '38-0': 'Experimental',
  '3-567': 'Blues',
  '15-495': 'Electronic',
  '12-70': 'Rock',
  '2-130': 'International',
  '15-183': 'Electronic',
  '15-184': 'Electronic',

In [84]:
categories_df['labels_1_'] = categories_df.labels_1.apply(lambda x: labels['label1'].get(x))
categories_df['labels_2_'] = categories_df.labels_2.apply(lambda x: labels['label2'].get(x))
categories_df['labels_3_'] = categories_df.labels_3.apply(lambda x: labels['label3'].get(x))
categories_df['labels_4_'] = categories_df.labels_4.apply(lambda x: labels['label4'].get(x))
categories_df['labels_5_'] = categories_df.labels_5.apply(lambda x: labels['label5'].get(x))

In [85]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name,labels_1_,labels_2_,labels_3_,labels_4_,labels_5_
93290,15,15-0,15-0-0,15-0-0-0,15-0-0-0-0,Electronic>Electronic>Electronic>Electronic>El...,8,55,174,284,42
72512,12,12-25,12-25-109,12-25-109-0,12-25-109-0-0,Rock>Punk>Hardcore>Hardcore>Hardcore,0,53,240,366,32
62379,15,15-42,15-42-0,15-42-0-0,15-42-0-0-0,Electronic>Ambient Electronic>Ambient Electron...,8,127,165,358,132
90787,1235,1235-0,1235-0-0,1235-0-0-0,1235-0-0-0-0,Instrumental>Instrumental>Instrumental>Instrum...,11,77,198,324,130
94901,12,12-25,12-25-0,12-25-0-0,12-25-0-0-0,Rock>Punk>Punk>Punk>Punk,0,53,279,403,4
...,...,...,...,...,...,...,...,...,...,...,...
83676,9,9-0,9-0-0,9-0-0-0,9-0-0-0-0,Country>Country>Country>Country>Country,4,100,188,407,52
98180,2,2-86,2-86-173,2-86-173-0,2-86-173-0-0,International>Indian>N. Indian Traditional>N. ...,15,112,187,300,50
30887,20,20-65,20-65-189,20-65-189-0,20-65-189-0-0,Spoken>Radio>Talk Radio>Talk Radio>Talk Radio,13,30,172,357,96
11886,20,20-465,20-465-0,20-465-0-0,20-465-0-0-0,Spoken>Musical Theater>Musical Theater>Musical...,13,47,244,333,148
12872,2,2-176,2-176-0,2-176-0-0,2-176-0-0-0,International>Pacific>Pacific>Pacific>Pacific,15,22,237,355,36

In [86]:
unique_labels_1 = categories_df['labels_1_'].unique().tolist()
unique_labels_2 = categories_df['labels_2_'].unique().tolist()
unique_labels_3 = categories_df['labels_3_'].unique().tolist()
unique_labels_4 = categories_df['labels_4_'].unique().tolist()
unique_labels_5 = categories_df['labels_5_'].unique().tolist()

In [87]:
unique_labels_1

[8, 0, 11, 12, 5, 1, 15, 13, 4, 9, 7, 14, 2, 6, 10, 3]

In [88]:
num_nodes_per_level = [len(unique_labels_1), len(unique_labels_2), len(unique_labels_3), len(unique_labels_4), len(unique_labels_5)]

In [89]:
# Cálculo de num_classes_per_node
num_classes_per_node = []

# num_classes_per_node = [
#     [5, 4, 6],  # Nível 1: 3 nós com 5, 4 e 6 classes
#     [3, 2, 4, 5],  # Nível 2: 4 nós com 3, 2, 4 e 5 classes
#     [4, 3, 5, 2, 6],  # Nível 3: 5 nós com 4, 3, 5, 2 e 6 classes
#     [2, 3, 4, 5, 3, 2],  # Nível 4: 6 nós com 2, 3, 4, 5, 3 e 2 classes
#     [5, 6, 3, 4, 2, 3, 4],  # Nível 5: 7 nós com 5, 6, 3, 4, 2, 3 e 4 classes
# ]
# num_classes_per_node.append(unique_labels_1)  # Nível 1

unique_lavel2_per_level1 = categories_df.groupby('labels_1_')['labels_2_'].nunique()
num_classes_per_node.append(unique_lavel2_per_level1.tolist())  # Nível 2

unique_lavel3_per_level2 = categories_df.groupby(['labels_1_', 'labels_2_'])['labels_3_'].nunique()
num_classes_per_node.append(unique_lavel3_per_level2.tolist())  # Nível 3

unique_lavel4_per_level3 = categories_df.groupby(['labels_1_', 'labels_2_', 'labels_3_'])['labels_4_'].nunique()
num_classes_per_node.append(unique_lavel4_per_level3.tolist())  # Nível 4

unique_lavel5_per_level4 = categories_df.groupby(['labels_1_', 'labels_2_', 'labels_3_', 'labels_4_'])['labels_5_'].nunique()
num_classes_per_node.append(unique_lavel5_per_level4.tolist())  # Nível 5

In [93]:

print("num_nodes_per_level:", num_classes_per_node[0])

num_nodes_per_level: [8, 0, 11, 12, 5, 1, 15, 13, 4, 9, 7, 14, 2, 6, 10, 3]

In [94]:
labels['label5']

{'12-58-0-0-0': 0,
 '21-539-0-0-0': 1,
 '38-0-0-0-0': 2,
 '12-31-167-0-0': 3,
 '12-25-0-0-0': 4,
 '10-362-0-0-0': 5,
 '12-25-71-0-0': 6,
 '4-97-0-0-0': 7,
 '1235-267-0-0-0': 8,
 '2-130-741-0-0': 9,
 '5-322-0-0-0': 10,
 '4-179-0-0-0': 11,
 '2-504-0-0-0': 12,
 '2-118-0-0-0': 13,
 '13-311-0-0-0': 14,
 '15-695-0-0-0': 15,
 '13-810-0-0-0': 16,
 '12-25-109-361-0': 17,
 '2-102-1032-0-0': 18,
 '15-183-0-0-0': 19,
 '17-103-0-0-0': 20,
 '2-86-0-0-0': 21,
 '4-74-0-0-0': 22,
 '20-374-0-0-0': 23,
 '5-659-0-0-0': 24,
 '17-49-0-0-0': 25,
 '15-182-0-0-0': 26,
 '15-182-400-0-0': 27,
 '21-100-0-0-0': 28,
 '38-456-0-0-0': 29,
 '2-46-1060-0-0': 30,
 '38-224-0-0-0': 31,
 '12-25-109-0-0': 32,
 '5-443-0-0-0': 33,
 '5-0-0-0-0': 34,
 '12-25-111-0-0': 35,
 '2-176-0-0-0': 36,
 '4-906-0-0-0': 37,
 '14-11-0-0-0': 38,
 '12-98-0-0-0': 39,
 '2-46-0-0-0': 40,
 '38-125-0-0-0': 41,
 '15-0-0-0-0': 42,
 '38-250-0-0-0': 43,
 '2-232-0-0-0': 44,
 '15-468-0-0-0': 45,
 '12-0-0-0-0': 46,
 '12-45-53-90-0': 47,
 '5-187-0-0-0': 48,
 '3-567-0-0-0': 49,
 '2-86-173-0-0': 50,
 '12-26-0-0-0': 51,
 '9-0-0-0-0': 52,
 '9-651-0-0-0': 53,
 '2-171-0-0-0': 54,
 '17-180-0-0-0': 55,
 '1235-18-0-0-0': 56,
 '10-76-0-0-0': 57,
 '38-22-0-0-0': 58,
 '20-378-0-0-0': 59,
 '15-495-0-0-0': 60,
 '2-102-0-0-0': 61,
 '12-45-53-0-0': 62,
 '8-0-0-0-0': 63,
 '12-25-89-0-0': 64,
 '38-6-360-0-0': 65,
 '15-297-240-0-0': 66,
 '38-41-0-0-0': 67,
 '38-47-0-0-0': 68,
 '5-442-0-0-0': 69,
 '21-811-0-0-0': 70,
 '21-0-0-0-0': 71,
 '38-6-16-763-1193': 72,
 '38-30-0-0-0': 73,
 '20-65-0-0-0': 74,
 '2-92-214-0-0': 75,
 '17-33-0-0-0': 76,
 '15-185-0-0-0': 77,
 '20-65-43-0-0': 78,
 '15-286-0-0-0': 79,
 '21-542-0-0-0': 80,
 '2-77-0-0-0': 81,
 '12-359-0-0-0': 82,
 '2-92-81-0-0': 83,
 '2-46-502-0-0': 84,
 '2-79-0-0-0': 85,
 '2-0-0-0-0': 86,
 '20-188-0-0-0': 87,
 '1235-107-0-0-0': 88,
 '21-580-0-0-0': 89,
 '12-31-101-0-0': 90,
 '21-693-0-0-0': 91,
 '12-88-0-0-0': 92,
 '12-440-0-0-0': 93,
 '38-186-0-0-0': 94,
 '38-6-0-0-0': 95,
 '20-65-189-0-0': 96,
 '12-45-0-0-0': 97,
 '3-0-0-0-0': 98,
 '2-130-524-0-0': 99,
 '38-514-0-0-0': 100,
 '15-337-0-0-0': 101,
 '12-25-64-0-0': 102,
 '15-181-401-0-0': 103,
 '2-172-0-0-0': 104,
 '15-236-0-0-0': 105,
 '15-297-0-0-0': 106,
 '9-169-0-0-0': 107,
 '9-63-0-0-0': 108,
 '5-441-0-0-0': 109,
 '12-27-0-0-0': 110,
 '38-247-0-0-0': 111,
 '12-31-0-0-0': 112,
 '12-85-404-0-0': 113,
 '12-66-0-0-0': 114,
 '2-79-602-0-0': 115,
 '38-32-0-0-0': 116,
 '12-26-113-0-0': 117,
 '20-65-166-0-0': 118,
 '12-70-0-0-0': 119,
 '2-130-619-0-0': 120,
 '1235-18-538-0-0': 121,
 '12-314-0-0-0': 122,
 '12-85-0-0-0': 123,
 '14-19-0-0-0': 124,
 '2-130-1156-0-0': 125,
 '15-181-0-0-0': 126,
 '20-0-0-0-0': 127,
 '17-0-0-0-0': 128,
 '14-0-0-0-0': 129,
 '1235-0-0-0-0': 130,
 '15-468-491-0-0': 131,
 '15-42-0-0-0': 132,
 '38-6-16-763-0': 133,
 '20-428-0-0-0': 134,
 '4-37-0-0-0': 135,
 '38-1-0-0-0': 136,
 '10-0-0-0-0': 137,
 '17-94-0-0-0': 138,
 '15-296-0-0-0': 139,
 '4-0-0-0-0': 140,
 '2-177-0-0-0': 141,
 '2-92-0-0-0': 142,
 '2-130-0-0-0': 143,
 '9-137-0-0-0': 144,
 '15-184-0-0-0': 145,
 '12-31-439-0-0': 146,
 '12-36-0-0-0': 147,
 '20-465-0-0-0': 148,
 '13-170-0-0-0': 149,
 '20-138-0-0-0': 150}

In [95]:
labels['label1_count']

16

In [96]:


def parse_tfr_element(element):
    #use the same structure as above; it's kinda an outline of the structure we now want to create
    data = {
        'emb' : tf.io.FixedLenFeature([], tf.string),
        'track_id' : tf.io.FixedLenFeature([], tf.int64),
    }
    
    content = tf.io.parse_single_example(element, data)

    track_id = content['track_id']
    emb = content['emb']
    

    #get our 'feature'-- our image -- and reshape it appropriately
    feature = tf.io.parse_tensor(emb, out_type=tf.float32)
    return (feature, track_id)


def get_dataset(filename):
    #create the dataset
    dataset = tf.data.TFRecordDataset(filename)

    #pass every single feature through our mapping function
    dataset = dataset.map(
        parse_tfr_element
    )

    return dataset

In [97]:
import numpy as np


def load_dataset(path,dataset=args.embeddings):
    tfrecords_path = os.path.join(path,'tfrecords',dataset)
    
    
    tfrecords_path = [os.path.join(tfrecords_path,path) for path in os.listdir(tfrecords_path)]
    dataset = get_dataset(tfrecords_path)
    
    df = pd.DataFrame(
        dataset.as_numpy_iterator(),
        columns=['feature', 'track_id']
    )
        
    df.dropna(inplace=True)
    
    
    try:
        df.feature = df.feature.apply(lambda x: x[0] if x.shape[0] != 0 else None)
    except:
        print(x)
    
    return df

In [98]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0        633
1235-0-0-0-0      620
1235-107-0-0-0    408
10-76-0-0-0       401
21-0-0-0-0        362
                 ...
20-374-0-0-0        2
2-86-173-0-0        1
20-65-189-0-0       1
20-465-0-0-0        1
2-176-0-0-0         1
Name: count, Length: 151, dtype: int64

In [99]:
def __split_data__(group, percentage=0.1):
    if len(group) == 1:
        return group, group

    shuffled = shuffle(group.values)
    finish_test = int(ceil(len(group) * percentage))

    first = pd.DataFrame(shuffled[:finish_test], columns=group.columns)
    second = pd.DataFrame(shuffled[finish_test:], columns=group.columns)

    return first, second

In [100]:
def select_dataset(tracks_df):
    
#     dataset_testset_path = os.path.join(tfrecord_path,'test')
#     dataset_validationset_path = os.path.join(tfrecord_path,'val')
#     dataset_trainset_path = os.path.join(tfrecord_path,'train')
    
    df = load_dataset(args.dataset_path,dataset=args.embeddings)
    
    df.dropna(inplace=True)
    
    tracks_df = tracks_df.merge(df, on='track_id')
    
    tracks_df.loc[:,'labels_1'] = tracks_df.labels_1.astype(str).progress_apply(lambda x: labels['label1'][x])
    tracks_df.loc[:,'labels_2'] = tracks_df.labels_2.astype(str).progress_apply(lambda x: labels['label2'][x])
    tracks_df.loc[:,'labels_3'] = tracks_df.labels_3.astype(str).progress_apply(lambda x: labels['label3'][x])
    tracks_df.loc[:,'labels_4'] = tracks_df.labels_4.astype(str).progress_apply(lambda x: labels['label4'][x])
    tracks_df.loc[:,'labels_5'] = tracks_df.labels_5.astype(str).progress_apply(lambda x: labels['label5'][x])
    
    tests = []
    trains = []
    validations = []
    groups = tracks_df.groupby("labels_5")
    
    
    count = 0
    items_count = 0
    total = len(groups)
    total_items = len(tracks_df)
    oversampling_size = 30  # int(group_sizes.mean() + group_sizes.std() * 2)
    print(f"oversampling_size: {oversampling_size}")

    for code, group in groups:
        test, train_to_split = __split_data__(group, 0.01)  # 10%
        train_to_split = train_to_split
        validation, train = __split_data__(train_to_split, 0.01)  # %1

        tests.append(test)
        validations.append(validation)

        ## this increase the numner of samples when classes has low quantity
        count_train = len(train)
        if count_train < oversampling_size:
            train = train.sample(oversampling_size, replace=True)

        trains.append(train)

        count += 1
        items_count += count_train
        
        
    df_test = pd.concat(tests, sort=False).sample(frac=1).reset_index(drop=True)
    # .to_csv(dataset_testset_path, index=False,quoting=csv.QUOTE_ALL)
    df_val = pd.concat(validations, sort=False).sample(frac=1).reset_index(drop=True)
    df_train = pd.concat(trains, sort=False).sample(frac=1).reset_index(drop=True)

    return df_train,df_test,df_val

In [101]:
df_train,df_test,df_val = select_dataset(tracks_df)

2023-07-10 17:23:55.374940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9432 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5
2023-07-10 17:23:55.909355: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [11]
	 [[{{node Placeholder/_0}}]]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

oversampling_size: 30

In [102]:
df_train

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5,feature
0,18555,"[4, 97]",2,121,163,345,7,"[0.35441682, 0.025803884, 0.06809089, -0.01293..."
1,48473,"[12, 25, 89]",0,53,168,349,64,"[-0.0014269551, 0.05689159, -0.014941454, 0.07..."
2,24267,[15],8,55,174,284,42,"[-0.02800559, 0.055536687, -0.04682082, 0.0071..."
3,58323,[38],5,96,146,417,2,"[0.049729038, 0.011279096, -0.035674047, -0.03..."
4,36402,"[15, 297]",8,84,134,365,106,"[-0.010291696, -0.02489998, -0.030127147, -0.0..."
...,...,...,...,...,...,...,...,...
11631,138841,"[17, 94]",14,80,246,294,138,"[0.013735543, -0.002130419, -0.016505003, -0.0..."
11632,53242,[38],5,96,146,417,2,"[-0.014517088, -0.0140476925, 0.14066367, 0.02..."
11633,132928,[1235],11,77,198,324,130,"[-0.039155632, -0.02099363, 0.02525571, 0.3229..."
11634,27207,[38],5,96,146,417,2,"[0.06749219, 0.051840514, -0.020605674, -0.016..."
11635,58510,"[10, 362]",12,90,233,415,5,"[0.055510204, -0.026901841, -0.06578795, -0.05..."

In [103]:
def _bytes_feature(value):
  ### Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))): # if value ist tensor
        value = value.numpy() # get value of tensor
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def _float_feature(value):
  ### Returns a floast_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64List_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def _int64_feature(value):
  ###  Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def serialize_array(array):
    array = tf.io.serialize_tensor(array)
    return array

In [104]:
def parse_single_music(data,labels):
    track_id, _, cat1, cat2, cat3, cat4, cat5, music = data
    
    
    label1 = np.array([cat1, labels['label1_count']], np.int64)
    label2 = np.array([cat2, labels['label2_count']], np.int64)
    label3 = np.array([cat3, labels['label3_count']], np.int64)
    label4 = np.array([cat4, labels['label4_count']], np.int64)
    label5 = np.array([cat5, labels['label5_count']], np.int64)
    
    
    
    #define the dictionary -- the structure -- of our single example
    data = {
        'label1': _int64List_feature(label1),
        'label2': _int64List_feature(label2),
        'label3': _int64List_feature(label3),
        'label4': _int64List_feature(label4),
        'label5': _int64List_feature(label5),
        # 'features' : _bytes_feature(serialize_array(music)),
        'features' : _float_feature(music),
        'track_id' : _int64_feature(track_id)
    }
    #create an Example, wrapping the single features
    out = tf.train.Example(features=tf.train.Features(feature=data))

    return out

In [105]:
def generate_tf_record(df,tf_path='val'):
    create_dir(tf_path)
    
    
    batch_size = 1024 * 50 # 50k records from each file batch
    count = 0
    total = math.ceil(len(df) / batch_size)

    for i in range(0, len(df), batch_size):
        batch_df = df[i:i+batch_size]
        
        tfrecords = [parse_single_music(data, labels) for data in batch_df.values]
        
        path = f"{tf_path}/{str(count).zfill(10)}.tfrecord"
        
        #with tf.python_io.TFRecordWriter(path) as writer:
        with tf.io.TFRecordWriter(path) as writer:
            for tfrecord in tfrecords:
                writer.write(tfrecord.SerializeToString())

        print(f"{count} {len(tfrecords)} {path}")
        count += 1
        print(f"{count}/{total} batchs / {count * batch_size} processed")

    print(f"{count}/{total} batchs / {len(df)} processed")
    
    return tf_path

In [106]:
tfrecord_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords'

In [107]:
val_path = generate_tf_record(df_val,tf_path=os.path.join(tfrecord_path,'val'))

0 208 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/val/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 208 processed

In [108]:
test_path = generate_tf_record(df_test,tf_path=os.path.join(tfrecord_path,'test'))

0 209 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/test/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 209 processed

In [109]:
train_path = generate_tf_record(df_train,tf_path=os.path.join(tfrecord_path,'train'))

0 11636 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/train/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 11636 processed

In [110]:
def create_metadata(metadata_path):

    with open(metadata_path, 'w+') as f:
        f.write(json.dumps({
            'sequence_size': args.sequence_size,
            'n_levels': labels_size,
            'num_nodes_per_level':num_nodes_per_level,
            'num_classes_per_node':num_classes_per_node,
            'labels_size': [labels['label1_count'],labels['label2_count'],
                           labels['label3_count'],labels['label4_count'],
                           labels['label5_count']],
            'val_path': val_path,
            'train_path': train_path,
            'test_path': test_path,
            'trainset_count': len(df_train),
            'validationset_count': len(df_val),
            'testset_count': len(df_test)
        }))

In [111]:
num_nodes_per_level

[[8, 0, 11, 12, 5, 1, 15, 13, 4, 9, 7, 14, 2, 6, 10, 3],
 [55,
  53,
  127,
  77,
  66,
  57,
  96,
  49,
  45,
  17,
  33,
  86,
  59,
  20,
  114,
  124,
  102,
  92,
  113,
  108,
  120,
  111,
  40,
  98,
  26,
  76,
  117,
  74,
  54,
  42,
  81,
  80,
  60,
  129,
  16,
  84,
  101,
  44,
  19,
  48,
  126,
  123,
  90,
  28,
  75,
  39,
  31,
  87,
  37,
  18,
  27,
  36,
  112,
  29,
  56,
  63,
  70,
  73,
  68,
  78,
  58,
  43,
  97,
  116,
  51,
  46,
  94,
  128,
  122,
  104,
  61,
  32,
  24,
  52,
  89,
  88,
  21,
  99,
  25,
  103,
  118,
  23,
  71,
  121,
  50,
  83,
  30,
  107,
  130,
  67,
  115,
  85,
  109,
  91,
  41,
  131,
  72,
  34,
  64,
  93,
  106,
  119,
  62,
  110,
  105,
  79,
  69,
  35,
  38,
  82,
  65,
  125,
  95,
  100,
  47,
  22],
 [174,
  240,
  165,
  198,
  279,
  191,
  155,
  146,
  149,
  234,
  201,
  219,
  257,
  242,
  182,
  190,
  218,
  241,
  152,
  251,
  227,
  216,
  144,
  138,
  243,
  207,
  215,
  158,
  265,
  213,
  132,
  164,
  246,
  275,
  160,
  262,
  134,
  269,
  202,
  255,
  181,
  260,
  179,
  233,
  154,
  259,
  270,
  228,
  135,
  238,
  196,
  136,
  254,
  247,
  192,
  193,
  145,
  212,
  276,
  143,
  235,
  236,
  137,
  220,
  148,
  232,
  162,
  239,
  209,
  177,
  156,
  221,
  199,
  150,
  266,
  217,
  214,
  140,
  168,
  139,
  133,
  159,
  263,
  206,
  183,
  264,
  272,
  225,
  273,
  208,
  194,
  197,
  258,
  245,
  163,
  185,
  170,
  277,
  189,
  153,
  141,
  169,
  176,
  210,
  203,
  186,
  195,
  224,
  261,
  173,
  151,
  167,
  147,
  184,
  171,
  226,
  157,
  230,
  204,
  274,
  267,
  166,
  211,
  205,
  222,
  253,
  268,
  256,
  200,
  180,
  278,
  249,
  142,
  248,
  223,
  175,
  250,
  271,
  229,
  178,
  252,
  231,
  161,
  188,
  187,
  172,
  244,
  237],
 [284,
  366,
  358,
  324,
  403,
  351,
  364,
  417,
  400,
  380,
  288,
  337,
  320,
  376,
  310,
  385,
  314,
  408,
  350,
  282,
  293,
  427,
  307,
  378,
  386,
  287,
  419,
  334,
  322,
  392,
  285,
  325,
  294,
  388,
  369,
  429,
  365,
  370,
  421,
  298,
  423,
  304,
  381,
  415,
  319,
  306,
  373,
  323,
  402,
  302,
  343,
  395,
  399,
  292,
  326,
  377,
  397,
  398,
  360,
  412,
  384,
  346,
  383,
  354,
  394,
  371,
  290,
  353,
  405,
  413,
  328,
  387,
  315,
  289,
  426,
  362,
  318,
  301,
  359,
  349,
  280,
  396,
  305,
  297,
  312,
  327,
  335,
  374,
  389,
  329,
  303,
  368,
  342,
  428,
  296,
  345,
  291,
  340,
  406,
  411,
  418,
  344,
  341,
  339,
  348,
  347,
  401,
  390,
  420,
  309,
  424,
  404,
  375,
  391,
  372,
  422,
  363,
  331,
  283,
  361,
  330,
  382,
  393,
  410,
  332,
  295,
  352,
  336,
  313,
  409,
  286,
  356,
  338,
  316,
  425,
  281,
  414,
  317,
  311,
  321,
  299,
  379,
  416,
  367,
  308,
  407,
  300,
  357,
  333,
  355],
 [42,
  32,
  132,
  130,
  4,
  57,
  105,
  2,
  49,
  60,
  119,
  120,
  19,
  145,
  137,
  88,
  111,
  31,
  150,
  144,
  124,
  112,
  91,
  139,
  13,
  114,
  71,
  46,
  70,
  110,
  43,
  76,
  138,
  62,
  128,
  15,
  106,
  116,
  0,
  117,
  1,
  41,
  140,
  5,
  121,
  67,
  79,
  20,
  100,
  122,
  56,
  47,
  123,
  87,
  6,
  69,
  21,
  136,
  82,
  80,
  28,
  68,
  73,
  126,
  26,
  27,
  134,
  40,
  3,
  48,
  127,
  115,
  63,
  14,
  39,
  34,
  8,
  45,
  10,
  64,
  92,
  94,
  29,
  101,
  89,
  24,
  65,
  77,
  35,
  90,
  51,
  66,
  38,
  85,
  58,
  7,
  146,
  131,
  33,
  22,
  118,
  141,
  12,
  133,
  97,
  9,
  74,
  78,
  53,
  83,
  84,
  25,
  54,
  103,
  44,
  113,
  72,
  16,
  104,
  23,
  86,
  11,
  59,
  55,
  109,
  37,
  142,
  143,
  135,
  147,
  102,
  81,
  17,
  108,
  61,
  99,
  18,
  149,
  98,
  75,
  107,
  129,
  125,
  93,
  30,
  95,
  52,
  50,
  96,
  148,
  36]]

In [112]:
create_metadata(metadata_path)

In [113]:
job_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample'

In [114]:
tracks_df.to_csv(os.path.join(job_path,"tracks.csv"),index=False)

In [115]:
with open(categories_labels_path, 'r') as f:
    labels = json.loads(f.read())

In [116]:
with open(metadata_path, 'r') as f:
    metadata = json.loads(f.read())

In [117]:
levels_size = {'level1_size': labels['label1_count']-1,
        'level2_size': labels['label2_count']-1,
        'level3_size': labels['label3_count']-1,
        'level4_size': labels['label4_count']-1,
        'level5_size': labels['label5_count']-1}

In [118]:
levels_size['level1_size']

15

In [124]:
metadata['num_nodes_per_level'][1]

[55,
 53,
 127,
 77,
 66,
 57,
 96,
 49,
 45,
 17,
 33,
 86,
 59,
 20,
 114,
 124,
 102,
 92,
 113,
 108,
 120,
 111,
 40,
 98,
 26,
 76,
 117,
 74,
 54,
 42,
 81,
 80,
 60,
 129,
 16,
 84,
 101,
 44,
 19,
 48,
 126,
 123,
 90,
 28,
 75,
 39,
 31,
 87,
 37,
 18,
 27,
 36,
 112,
 29,
 56,
 63,
 70,
 73,
 68,
 78,
 58,
 43,
 97,
 116,
 51,
 46,
 94,
 128,
 122,
 104,
 61,
 32,
 24,
 52,
 89,
 88,
 21,
 99,
 25,
 103,
 118,
 23,
 71,
 121,
 50,
 83,
 30,
 107,
 130,
 67,
 115,
 85,
 109,
 91,
 41,
 131,
 72,
 34,
 64,
 93,
 106,
 119,
 62,
 110,
 105,
 79,
 69,
 35,
 38,
 82,
 65,
 125,
 95,
 100,
 47,
 22]

In [127]:
metadata['num_classes_per_node'][1]

[16, 2, 6, 3, 5, 15, 7, 7, 15, 3, 1, 4, 3, 8, 6, 15]