In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
import json
import ast
import os
import csv
import math
from sklearn.utils import shuffle
from math import ceil
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm

In [3]:
tqdm.pandas()

In [4]:

args = pd.Series({
    "root_dir":"/mnt/disks/data/",
    "dataset_path":"/mnt/disks/data/fma/fma_large",
    "embeddings":"music_style",
    "sequence_size": 1280,
    "train_id": "hierarchical_local_sample",
    'sample_size': 0.1
})

In [5]:

base_path = "/mnt/disks/data/fma/trains"


job_path = os.path.join(base_path,args.train_id)


tfrecord_path = os.path.join(job_path,"tfrecords")

# In[16]:

base_path = os.path.join(args.root_dir,"fma")

# In[17]:

models_path = os.path.join(args.root_dir,"models")


metadata_path_fma = os.path.join(base_path,"fma_metadata")

# In[18]:

metadata_path = os.path.join(job_path,"metadata.json")


categories_labels_path = os.path.join(job_path,"labels.json")

In [6]:


def __load_json__(path):
    with open(path, 'r') as f:
        tmp = json.loads(f.read())

    return tmp

In [7]:

def create_dir(path):
    # checking if the directory demo_folder2 
    # exist or not.
    if not os.path.isdir(path):

        # if the demo_folder2 directory is 
        # not present then create it.
        os.makedirs(path)
    return True

In [8]:
import shutil
shutil.rmtree(job_path)

In [9]:
create_dir(job_path)

True

## Load genres file. Contains relationships beetwen genres

In [10]:
genres_df = pd.read_csv(os.path.join(metadata_path_fma,'genres.csv'))

In [11]:
genres_df

     genre_id  #tracks  parent          title  top_level
0           1     8693      38    Avant-Garde         38
1           2     5271       0  International          2
2           3     1752       0          Blues          3
3           4     4126       0           Jazz          4
4           5     4106       0      Classical          5
..        ...      ...     ...            ...        ...
158      1032       60     102        Turkish          2
159      1060       30      46          Tango          2
160      1156       26     130           Fado          2
161      1193       72     763      Christmas         38
162      1235    14938       0   Instrumental       1235

[163 rows x 5 columns]

In [12]:
genres_df[genres_df['genre_id'] == 495]

     genre_id  #tracks  parent      title  top_level
136       495     2061      15  Downtempo         15

In [13]:
# Cria um dicionário que associa o ID de cada música aos IDs de seus gêneros musicais
tracks_df = pd.read_csv(os.path.join(metadata_path_fma,'tracks_valid.csv'))

In [14]:
tracks_df = tracks_df.sample(frac=args.sample_size)

In [15]:
tracks_df.sample(20)

,track_id,track_title,valid_genre
70265,109329,Old Romantic,"['236', '542']"
67087,105166,svartedauden,"['38', '47', '107']"
40853,62151,Chasing - Tail,['53']
89598,134621,Entrepreneurs,"['26', '42']"
96108,143666,Needleneck,"['15', '32', '38', '41']"
682,934,More,['138']
15038,24565,Loco One,"['63', '314']"
43296,65352,Sleepytime Jazz,"['38', '76', '224']"
924,1198,"November 22nd 2003, 4:45 PM",['17']
68605,107220,The Knife and the Wolf,"['15', '38', '314']"
38608,59087,"London, 1846","['27', '66']"
37076,57090,Nick Beat,"['15', '811']"
9490,16034,John Carpenter,"['15', '183']"
16552,27340,I'm Just a Fine Young Man & I'm Doing So Well,"['25', '58']"
62583,95984,Summer (instrumental),"['10', '12', '1235']"
13715,22480,Celia,['76']
91157,136988,Заячий Король,"['27', '33', '38']"
54283,82360,Going After the Swan,"['1', '4', '38']"
67038,105092,Chained to This Dumpster,"['3', '25', '85']"
71076,110523,lucki ducks,"['1', '21', '74']"

In [16]:
tracks_df.valid_genre.values

array(["['10', '27', '103']", "['10', '27', '66']", "['103', '360']", ...,
       "['1', '30', '38', '41', '247']", "['10', '103']", "['18']"],
      dtype=object)

In [17]:
tracks_df.track_title

29057                            And I
22381          Don't Draw a Map for Me
68454        My one and only wonderful
9377     Scriabin, Fragilité Opus 51/1
47251             la musica y el baile
                     ...
48883                     Greensleeves
82440                              Teo
99969                A Prolonged Blast
44218                             Home
75187             Time Is Picking Away
Name: track_title, Length: 10419, dtype: object

In [18]:
## Get complete genre structure
def get_all_structure(estrutura,df_genres):
    ## Get structure from df_genres
    def get_all_structure_from_df(estrutura,df_genres,structure=[]):
        if estrutura == 0:
            return structure
        else:
            structure.append(int(estrutura))
            get_all_structure_from_df(df_genres[df_genres["genre_id"]==int(estrutura)].parent.values[0],df_genres,structure)
            return structure
    
    return get_all_structure_from_df(estrutura,df_genres,structure=[])

In [19]:
# tracks_df['valid_genre'] = tracks_df.track_genres.apply(lambda x: x.strip('][').split(', ') if x != '[]' else None)
tracks_df['valid_genre'] = tracks_df.valid_genre.apply(lambda x: ast.literal_eval(x))

In [20]:
tracks_df['last_genre_id'] = tracks_df.valid_genre.apply(lambda x:x[-1] if x != None else None)

In [21]:
tracks_df.sample(20)

,track_id,track_title,valid_genre,last_genre_id
102739,153186,Comadreamers I,"[47, 107, 1235]",1235
14089,23097,Ada,"[5, 15, 38, 46, 187]",187
6957,12473,Necessary Separation,"[58, 85]",85
21648,34626,Wedding In The Woods,"[1, 27, 76]",76
98502,146893,гипно...,"[1, 18, 38, 107, 250, 514, 659, 1235]",1235
21764,34773,Wild Horses,"[27, 76, 85]",85
90288,135766,Яна,"[15, 107, 337, 695]",695
2877,4874,ready ready,"[30, 65]",65
99636,148353,Hoodratzz mix '93,[695],695
56238,84932,The Haze,"[42, 107, 184]",184
51992,79354,06.23wwses,"[4, 32, 38, 42]",42
55980,84638,Karma Is a Bleach (Waiting for the World to End),"[15, 38]",38
92364,138417,21 (Original Mix),"[15, 107, 236]",236
22104,35293,One Mile From Heaven,"[33, 58, 76]",76
97127,145050,B3 - Une Fille comme les autres,"[12, 32]",32
96575,144465,Belle Isle (Instrumental),[103],103
12331,20375,Northern Lights,[18],18
89801,134882,Countenance,"[38, 107, 181]",181
5093,9879,keirneuringer,[38],38
59570,91106,The Task At Hand,"[15, 70]",70

In [22]:
tracks_df.dropna(inplace=True)

In [23]:
tracks_df

,track_id,track_title,valid_genre,last_genre_id
29057,44897,And I,"[10, 27, 103]",103
22381,35640,Don't Draw a Map for Me,"[10, 27, 66]",66
68454,107034,My one and only wonderful,"[103, 360]",360
9377,15913,"Scriabin, Fragilité Opus 51/1","[5, 187]",187
47251,70949,la musica y el baile,[495],495
...,...,...,...,...
48883,73170,Greensleeves,[17],17
82440,125237,Teo,"[30, 38, 456]",456
99969,148702,A Prolonged Blast,"[1, 30, 38, 41, 247]",247
44218,66417,Home,"[10, 103]",103
75187,115774,Time Is Picking Away,[18],18

In [24]:
tracks_df['full_genre_id'] = tracks_df.last_genre_id.progress_apply(lambda x: get_all_structure(x,genres_df)[::-1])

  0%|          | 0/10419 [00:00<?, ?it/s]

In [25]:
tracks_df.full_genre_id

29057       [17, 103]
22381        [12, 66]
68454    [38, 6, 360]
9377         [5, 187]
47251       [15, 495]
             ...
48883            [17]
82440       [38, 456]
99969       [38, 247]
44218       [17, 103]
75187      [1235, 18]
Name: full_genre_id, Length: 10419, dtype: object

In [26]:
tracks_df.columns

Index(['track_id', 'track_title', 'valid_genre', 'last_genre_id',
       'full_genre_id'],
      dtype='object')

In [27]:
tracks_df = tracks_df[['track_id','full_genre_id']]

In [28]:
tracks_df.full_genre_id.values

array([list([17, 103]), list([12, 66]), list([38, 6, 360]), ...,
       list([38, 247]), list([17, 103]), list([1235, 18])], dtype=object)

In [29]:
tracks_df.full_genre_id.info

<bound method Series.info of 29057       [17, 103]
22381        [12, 66]
68454    [38, 6, 360]
9377         [5, 187]
47251       [15, 495]
             ...
48883            [17]
82440       [38, 456]
99969       [38, 247]
44218       [17, 103]
75187      [1235, 18]
Name: full_genre_id, Length: 10419, dtype: object>

In [30]:
labels_size = tracks_df.full_genre_id.apply(lambda x: len(x))

In [31]:
labels_size = int(labels_size.max())

In [32]:
type(labels_size)

int

### Parse of label to structure

In [33]:
### Function for parse label to sctructure of hierarhical scheme

def parse_label(label,label_size=5):
    # label = label.split('-')
    # preencher com 0 no caso de haver menos de 5 níveis
    labels = np.zeros(label_size,dtype=int)
    for i, label in enumerate(label):
        if i == 5:
            break
        # Aqui você pode fazer a conversão do label em um índice inteiro usando um dicionário ou outro método
        # Neste exemplo, estou apenas usando a posição da label na lista como índice
        labels[i] = label
    return labels

In [34]:
parsed_labels = tracks_df.full_genre_id.apply(lambda x: parse_label(x))

In [35]:
parsed_labels

29057     [17, 103, 0, 0, 0]
22381      [12, 66, 0, 0, 0]
68454     [38, 6, 360, 0, 0]
9377       [5, 187, 0, 0, 0]
47251     [15, 495, 0, 0, 0]
                ...
48883       [17, 0, 0, 0, 0]
82440     [38, 456, 0, 0, 0]
99969     [38, 247, 0, 0, 0]
44218     [17, 103, 0, 0, 0]
75187    [1235, 18, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [36]:
tracks_df['full_genre_id']

29057       [17, 103]
22381        [12, 66]
68454    [38, 6, 360]
9377         [5, 187]
47251       [15, 495]
             ...
48883            [17]
82440       [38, 456]
99969       [38, 247]
44218       [17, 103]
75187      [1235, 18]
Name: full_genre_id, Length: 10419, dtype: object

In [37]:
parsed_labels

29057     [17, 103, 0, 0, 0]
22381      [12, 66, 0, 0, 0]
68454     [38, 6, 360, 0, 0]
9377       [5, 187, 0, 0, 0]
47251     [15, 495, 0, 0, 0]
                ...
48883       [17, 0, 0, 0, 0]
82440     [38, 456, 0, 0, 0]
99969     [38, 247, 0, 0, 0]
44218     [17, 103, 0, 0, 0]
75187    [1235, 18, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [38]:
def convert_label_to_string(x,level=2,string=False):
    
    if string:
        return '-'.join([str(value) for value in x[:level+1]])
    
    return x[level]

In [39]:
tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0,string=True))
tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1,string=True))
tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2,string=True))
tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3,string=True))
tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4,string=True))

  0%|          | 0/10419 [00:00<?, ?it/s]

/tmp/ipykernel_2002631/4201371094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0,string=True))

  0%|          | 0/10419 [00:00<?, ?it/s]

/tmp/ipykernel_2002631/4201371094.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1,string=True))

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

In [40]:
# tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0))
# tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1))
# tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2))
# tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3))
# tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4))

In [41]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(["38","1235"])]

In [42]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
29057,44897,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
22381,35640,"[12, 66]",12,12-66,12-66-0,12-66-0-0,12-66-0-0-0
68454,107034,"[38, 6, 360]",38,38-6,38-6-360,38-6-360-0,38-6-360-0-0
9377,15913,"[5, 187]",5,5-187,5-187-0,5-187-0-0,5-187-0-0-0
47251,70949,"[15, 495]",15,15-495,15-495-0,15-495-0-0,15-495-0-0-0
...,...,...,...,...,...,...,...
48883,73170,[17],17,17-0,17-0-0,17-0-0-0,17-0-0-0-0
82440,125237,"[38, 456]",38,38-456,38-456-0,38-456-0-0,38-456-0-0-0
99969,148702,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
44218,66417,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
75187,115774,"[1235, 18]",1235,1235-18,1235-18-0,1235-18-0-0,1235-18-0-0-0

In [43]:
tracks_df['labels_4'].value_counts()

labels_4
38-0-0-0        624
1235-0-0-0      588
10-76-0-0       405
1235-107-0-0    396
21-0-0-0        369
               ...
2-232-0-0         1
20-465-0-0        1
2-130-1156-0      1
2-117-0-0         1
2-176-0-0         1
Name: count, Length: 151, dtype: int64

In [44]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0        624
1235-0-0-0-0      588
10-76-0-0-0       405
1235-107-0-0-0    396
21-0-0-0-0        369
                 ...
2-232-0-0-0         1
2-86-174-0-0        1
2-130-1156-0-0      1
2-117-0-0-0         1
2-176-0-0-0         1
Name: count, Length: 152, dtype: int64

In [45]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(['3','14'])]

In [46]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
29057,44897,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
22381,35640,"[12, 66]",12,12-66,12-66-0,12-66-0-0,12-66-0-0-0
68454,107034,"[38, 6, 360]",38,38-6,38-6-360,38-6-360-0,38-6-360-0-0
9377,15913,"[5, 187]",5,5-187,5-187-0,5-187-0-0,5-187-0-0-0
47251,70949,"[15, 495]",15,15-495,15-495-0,15-495-0-0,15-495-0-0-0
...,...,...,...,...,...,...,...
48883,73170,[17],17,17-0,17-0-0,17-0-0-0,17-0-0-0-0
82440,125237,"[38, 456]",38,38-456,38-456-0,38-456-0-0,38-456-0-0-0
99969,148702,"[38, 247]",38,38-247,38-247-0,38-247-0-0,38-247-0-0-0
44218,66417,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
75187,115774,"[1235, 18]",1235,1235-18,1235-18-0,1235-18-0-0,1235-18-0-0-0

In [47]:
categories_df = pd.DataFrame({'level1':tracks_df.labels_1.unique()})

In [48]:
categories_df = tracks_df[['labels_1','labels_2','labels_3','labels_4','labels_5']].drop_duplicates()

In [49]:
categories_df

      labels_1 labels_2    labels_3      labels_4        labels_5
29057       17   17-103    17-103-0    17-103-0-0    17-103-0-0-0
22381       12    12-66     12-66-0     12-66-0-0     12-66-0-0-0
68454       38     38-6    38-6-360    38-6-360-0    38-6-360-0-0
9377         5    5-187     5-187-0     5-187-0-0     5-187-0-0-0
47251       15   15-495    15-495-0    15-495-0-0    15-495-0-0-0
...        ...      ...         ...           ...             ...
67893        2    2-130  2-130-1156  2-130-1156-0  2-130-1156-0-0
62469       21    21-83     21-83-0     21-83-0-0     21-83-0-0-0
78801       13   13-170    13-170-0    13-170-0-0    13-170-0-0-0
16869        2    2-117     2-117-0     2-117-0-0     2-117-0-0-0
12866        2    2-176     2-176-0     2-176-0-0     2-176-0-0-0

[152 rows x 5 columns]

In [50]:
# categories_df['level1'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:1]))
# categories_df['level2'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:2]))
# categories_df['level3'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:3]))
# categories_df['level4'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:4]))

In [51]:
categories_df

      labels_1 labels_2    labels_3      labels_4        labels_5
29057       17   17-103    17-103-0    17-103-0-0    17-103-0-0-0
22381       12    12-66     12-66-0     12-66-0-0     12-66-0-0-0
68454       38     38-6    38-6-360    38-6-360-0    38-6-360-0-0
9377         5    5-187     5-187-0     5-187-0-0     5-187-0-0-0
47251       15   15-495    15-495-0    15-495-0-0    15-495-0-0-0
...        ...      ...         ...           ...             ...
67893        2    2-130  2-130-1156  2-130-1156-0  2-130-1156-0-0
62469       21    21-83     21-83-0     21-83-0-0     21-83-0-0-0
78801       13   13-170    13-170-0    13-170-0-0    13-170-0-0-0
16869        2    2-117     2-117-0     2-117-0-0     2-117-0-0-0
12866        2    2-176     2-176-0     2-176-0-0     2-176-0-0-0

[152 rows x 5 columns]

In [52]:
def get_labels_name(x,genres_df):
    levels = 5
    full_name = []
    last_level = 0
    genre_root = ""
    for genre in x.split('-'):
        genre_df = genres_df[genres_df['genre_id'] == int(genre)]
        if genre_df.empty:
            genre_name = genre_root 
        else:
            genre_name = genre_df.title.values.tolist()[0]
            genre_root = genre_name
        
        full_name.append(genre_name)
    full_name = '>'.join(full_name)
        
    return full_name
    # return genres_df[genres_df['genre_id'] == int(x)].title.values.tolist()[0]

In [53]:
categories_df['level5_name'] = categories_df.labels_5.apply(lambda x: get_labels_name(x,genres_df))

In [54]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name
29057,17,17-103,17-103-0,17-103-0-0,17-103-0-0-0,Folk>Singer-Songwriter>Singer-Songwriter>Singe...
22381,12,12-66,12-66-0,12-66-0-0,12-66-0-0-0,Rock>Indie-Rock>Indie-Rock>Indie-Rock>Indie-Rock
68454,38,38-6,38-6-360,38-6-360-0,38-6-360-0-0,Experimental>Novelty>Kid-Friendly>Kid-Friendly...
9377,5,5-187,5-187-0,5-187-0-0,5-187-0-0-0,Classical>20th Century Classical>20th Century ...
47251,15,15-495,15-495-0,15-495-0-0,15-495-0-0-0,Electronic>Downtempo>Downtempo>Downtempo>Downt...
...,...,...,...,...,...,...
67893,2,2-130,2-130-1156,2-130-1156-0,2-130-1156-0-0,International>Europe>Fado>Fado>Fado
62469,21,21-83,21-83-0,21-83-0-0,21-83-0-0-0,Hip-Hop>Nerdcore>Nerdcore>Nerdcore>Nerdcore
78801,13,13-170,13-170-0,13-170-0-0,13-170-0-0-0,Easy Listening>Easy Listening: Vocal>Easy List...
16869,2,2-117,2-117-0,2-117-0-0,2-117-0-0-0,International>Polka>Polka>Polka>Polka
12866,2,2-176,2-176-0,2-176-0-0,2-176-0-0-0,International>Pacific>Pacific>Pacific>Pacific

In [55]:
def __create_labels__(categories_df):
    data = {
        "label1": {},
        "label2": {},
        "label3": {},
        "label4": {},
        "label5": {},
        "label1_inverse": [],
        "label2_inverse": [],
        "label3_inverse": [],
        "label4_inverse": [],
        "label5_inverse": [],
        "label1_name": {},
        "label2_name": {},
        "label3_name": {},
        "label4_name": {},
        "label5_name": {},
    }

    idx = 0
    
    for id_x, cat in enumerate(set(categories_df.labels_1.values.tolist())):
        data['label1'][cat] = idx
        data['label1_inverse'].append(cat)
        data['label1_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_2.values.tolist())):
        data['label2'][cat] = idx
        data['label2_inverse'].append(cat)
        data['label2_count'] = idx + 1
        idx+=1
        
    for id_x, cat in enumerate(set(categories_df.labels_3.values.tolist())):
        data['label3'][cat] = idx
        data['label3_inverse'].append(cat)
        data['label3_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_4.values.tolist())):
        data['label4'][cat] = idx
        data['label4_inverse'].append(cat)
        data['label4_count'] = idx + 1
        idx+=1
        
    for idx, cat in enumerate(set(categories_df.labels_5.values.tolist())):
        data['label5'][cat] = idx
        data['label5_inverse'].append(cat)
        data['label5_count'] = idx + 1
        idx+=1
        
    for cat5,cat1,cat2,cat3,cat4,name5 in categories_df.values:
        
        name1 = '>'.join(name5.split('>')[:1])
        name2 = '>'.join(name5.split('>')[:2])
        name3 = '>'.join(name5.split('>')[:3])
        name4 = '>'.join(name5.split('>')[:4])
        
        
        data['label1_name'][cat1] = name1
        data['label2_name'][cat2] = name2
        data['label3_name'][cat3] = name3
        data['label4_name'][cat4] = name4
        data['label5_name'][cat5] = name5
        
    return data

In [56]:
with open(categories_labels_path, 'w+') as f:
    f.write(json.dumps(__create_labels__(categories_df)))

In [57]:
labels  = __create_labels__(categories_df)

In [58]:
labels

{'label1': {'12': 0,
  '2': 1,
  '38': 2,
  '15': 3,
  '10': 4,
  '20': 5,
  '4': 6,
  '17': 7,
  '8': 8,
  '13': 9,
  '14': 10,
  '9': 11,
  '1235': 12,
  '3': 13,
  '21': 14,
  '5': 15},
 'label2': {'17-103': 16,
  '10-362': 17,
  '12-314': 18,
  '12-36': 19,
  '15-468': 20,
  '14-11': 21,
  '13-810': 22,
  '15-185': 23,
  '38-32': 24,
  '17-0': 25,
  '2-0': 26,
  '15-495': 27,
  '2-118': 28,
  '4-0': 29,
  '38-250': 30,
  '12-359': 31,
  '14-0': 32,
  '21-580': 33,
  '15-296': 34,
  '2-102': 35,
  '1235-0': 36,
  '15-236': 37,
  '2-176': 38,
  '20-374': 39,
  '13-311': 40,
  '38-0': 41,
  '5-0': 42,
  '17-180': 43,
  '5-441': 44,
  '38-125': 45,
  '12-440': 46,
  '17-49': 47,
  '20-65': 48,
  '21-0': 49,
  '5-322': 50,
  '13-170': 51,
  '2-177': 52,
  '2-86': 53,
  '2-46': 54,
  '15-183': 55,
  '2-172': 56,
  '15-695': 57,
  '15-181': 58,
  '21-539': 59,
  '12-25': 60,
  '12-27': 61,
  '20-188': 62,
  '20-138': 63,
  '4-906': 64,
  '38-514': 65,
  '3-0': 66,
  '12-0': 67,
  '38-41': 68,
  '5-659': 69,
  '2-77': 70,
  '20-0': 71,
  '38-186': 72,
  '2-117': 73,
  '15-286': 74,
  '12-58': 75,
  '20-465': 76,
  '38-456': 77,
  '12-31': 78,
  '15-297': 79,
  '5-442': 80,
  '2-504': 81,
  '5-187': 82,
  '3-567': 83,
  '12-85': 84,
  '9-137': 85,
  '2-232': 86,
  '38-224': 87,
  '9-0': 88,
  '9-169': 89,
  '12-70': 90,
  '38-22': 91,
  '20-378': 92,
  '9-651': 93,
  '5-443': 94,
  '12-26': 95,
  '12-45': 96,
  '8-0': 97,
  '15-337': 98,
  '4-74': 99,
  '21-693': 100,
  '17-94': 101,
  '38-6': 102,
  '15-42': 103,
  '21-100': 104,
  '15-184': 105,
  '38-247': 106,
  '2-130': 107,
  '4-37': 108,
  '21-811': 109,
  '14-19': 110,
  '38-47': 111,
  '9-63': 112,
  '12-88': 113,
  '12-66': 114,
  '12-98': 115,
  '2-79': 116,
  '10-0': 117,
  '20-428': 118,
  '21-542': 119,
  '2-92': 120,
  '21-83': 121,
  '1235-107': 122,
  '38-1': 123,
  '1235-18': 124,
  '2-171': 125,
  '10-76': 126,
  '1235-267': 127,
  '4-179': 128,
  '38-30': 129,
  '15-0': 130,
  '4-97': 131,
  '17-33': 132,
  '15-182': 133},
 'label3': {'38-47-0': 134,
  '15-337-0': 135,
  '38-6-0': 136,
  '12-31-101': 137,
  '9-651-0': 138,
  '38-514-0': 139,
  '12-27-0': 140,
  '12-31-439': 141,
  '12-25-111': 142,
  '12-26-113': 143,
  '17-94-0': 144,
  '17-180-0': 145,
  '9-169-0': 146,
  '4-906-0': 147,
  '2-177-0': 148,
  '20-0-0': 149,
  '15-42-0': 150,
  '1235-18-538': 151,
  '2-176-0': 152,
  '2-130-0': 153,
  '38-456-0': 154,
  '2-79-0': 155,
  '2-46-502': 156,
  '38-250-0': 157,
  '21-580-0': 158,
  '17-49-0': 159,
  '17-33-0': 160,
  '12-314-0': 161,
  '12-45-0': 162,
  '12-45-53': 163,
  '20-65-0': 164,
  '15-236-0': 165,
  '4-74-0': 166,
  '9-0-0': 167,
  '21-83-0': 168,
  '38-6-16': 169,
  '15-184-0': 170,
  '1235-107-0': 171,
  '12-31-167': 172,
  '21-693-0': 173,
  '8-0-0': 174,
  '12-36-0': 175,
  '2-130-524': 176,
  '2-118-0': 177,
  '38-30-0': 178,
  '38-0-0': 179,
  '20-465-0': 180,
  '2-130-741': 181,
  '13-810-0': 182,
  '5-441-0': 183,
  '20-428-0': 184,
  '2-46-0': 185,
  '12-31-0': 186,
  '38-1-0': 187,
  '2-130-619': 188,
  '12-85-404': 189,
  '15-182-0': 190,
  '12-0-0': 191,
  '38-125-0': 192,
  '2-86-0': 193,
  '5-0-0': 194,
  '15-185-0': 195,
  '10-0-0': 196,
  '15-495-0': 197,
  '10-76-0': 198,
  '12-85-0': 199,
  '2-102-0': 200,
  '38-22-0': 201,
  '5-322-0': 202,
  '12-25-0': 203,
  '21-539-0': 204,
  '1235-267-0': 205,
  '2-102-1032': 206,
  '4-0-0': 207,
  '12-58-0': 208,
  '10-362-0': 209,
  '4-179-0': 210,
  '20-374-0': 211,
  '2-86-174': 212,
  '2-79-602': 213,
  '15-183-0': 214,
  '2-172-0': 215,
  '3-0-0': 216,
  '17-0-0': 217,
  '4-97-0': 218,
  '15-0-0': 219,
  '2-130-1156': 220,
  '12-70-0': 221,
  '9-137-0': 222,
  '14-19-0': 223,
  '15-182-400': 224,
  '2-117-0': 225,
  '20-138-0': 226,
  '2-77-0': 227,
  '38-224-0': 228,
  '15-286-0': 229,
  '38-32-0': 230,
  '3-567-0': 231,
  '2-232-0': 232,
  '2-504-0': 233,
  '12-359-0': 234,
  '14-11-0': 235,
  '12-26-0': 236,
  '20-65-166': 237,
  '9-63-0': 238,
  '5-187-0': 239,
  '38-247-0': 240,
  '15-468-491': 241,
  '12-88-0': 242,
  '12-25-64': 243,
  '4-37-0': 244,
  '15-297-240': 245,
  '21-542-0': 246,
  '1235-0-0': 247,
  '5-442-0': 248,
  '2-46-1060': 249,
  '12-25-71': 250,
  '12-66-0': 251,
  '13-311-0': 252,
  '2-92-0': 253,
  '17-103-0': 254,
  '38-41-0': 255,
  '2-92-81': 256,
  '20-378-0': 257,
  '13-170-0': 258,
  '2-171-0': 259,
  '1235-18-0': 260,
  '20-188-0': 261,
  '14-0-0': 262,
  '5-659-0': 263,
  '15-296-0': 264,
  '12-25-109': 265,
  '12-25-89': 266,
  '38-6-360': 267,
  '12-98-0': 268,
  '15-695-0': 269,
  '12-440-0': 270,
  '20-65-43': 271,
  '5-443-0': 272,
  '2-0-0': 273,
  '21-811-0': 274,
  '15-181-0': 275,
  '21-0-0': 276,
  '15-468-0': 277,
  '21-100-0': 278,
  '2-92-214': 279,
  '38-186-0': 280,
  '15-297-0': 281,
  '15-181-401': 282},
 'label4': {'3-0-0-0': 283,
  '15-297-240-0': 284,
  '9-169-0-0': 285,
  '20-428-0-0': 286,
  '2-92-214-0': 287,
  '15-42-0-0': 288,
  '38-0-0-0': 289,
  '2-172-0-0': 290,
  '12-314-0-0': 291,
  '38-250-0-0': 292,
  '5-441-0-0': 293,
  '12-36-0-0': 294,
  '20-374-0-0': 295,
  '2-504-0-0': 296,
  '2-86-0-0': 297,
  '2-118-0-0': 298,
  '17-33-0-0': 299,
  '3-567-0-0': 300,
  '2-117-0-0': 301,
  '38-125-0-0': 302,
  '15-286-0-0': 303,
  '17-180-0-0': 304,
  '15-184-0-0': 305,
  '38-6-0-0': 306,
  '2-0-0-0': 307,
  '8-0-0-0': 308,
  '2-46-1060-0': 309,
  '13-311-0-0': 310,
  '14-0-0-0': 311,
  '15-185-0-0': 312,
  '12-58-0-0': 313,
  '12-26-113-0': 314,
  '5-443-0-0': 315,
  '38-6-16-763': 316,
  '9-63-0-0': 317,
  '12-25-109-0': 318,
  '20-0-0-0': 319,
  '2-232-0-0': 320,
  '15-236-0-0': 321,
  '2-130-1156-0': 322,
  '38-22-0-0': 323,
  '38-247-0-0': 324,
  '14-19-0-0': 325,
  '2-46-502-0': 326,
  '20-465-0-0': 327,
  '38-224-0-0': 328,
  '12-25-64-0': 329,
  '20-378-0-0': 330,
  '12-66-0-0': 331,
  '15-468-0-0': 332,
  '38-514-0-0': 333,
  '21-693-0-0': 334,
  '2-86-174-0': 335,
  '5-187-0-0': 336,
  '4-906-0-0': 337,
  '2-77-0-0': 338,
  '12-359-0-0': 339,
  '15-0-0-0': 340,
  '20-65-0-0': 341,
  '2-130-0-0': 342,
  '2-102-0-0': 343,
  '14-11-0-0': 344,
  '15-495-0-0': 345,
  '13-170-0-0': 346,
  '5-0-0-0': 347,
  '12-31-101-0': 348,
  '20-138-0-0': 349,
  '2-130-524-0': 350,
  '15-296-0-0': 351,
  '12-31-167-0': 352,
  '21-580-0-0': 353,
  '12-88-0-0': 354,
  '12-98-0-0': 355,
  '2-46-0-0': 356,
  '2-92-0-0': 357,
  '1235-0-0-0': 358,
  '21-100-0-0': 359,
  '12-70-0-0': 360,
  '38-41-0-0': 361,
  '2-130-619-0': 362,
  '4-37-0-0': 363,
  '15-468-491-0': 364,
  '15-182-0-0': 365,
  '10-0-0-0': 366,
  '1235-267-0-0': 367,
  '12-45-53-0': 368,
  '2-102-1032-0': 369,
  '2-177-0-0': 370,
  '2-79-0-0': 371,
  '13-810-0-0': 372,
  '5-659-0-0': 373,
  '17-0-0-0': 374,
  '21-542-0-0': 375,
  '12-25-111-0': 376,
  '9-137-0-0': 377,
  '15-182-400-0': 378,
  '20-188-0-0': 379,
  '5-442-0-0': 380,
  '15-181-0-0': 381,
  '1235-18-0-0': 382,
  '4-179-0-0': 383,
  '38-456-0-0': 384,
  '12-440-0-0': 385,
  '12-85-404-0': 386,
  '12-25-0-0': 387,
  '15-181-401-0': 388,
  '1235-18-538-0': 389,
  '12-27-0-0': 390,
  '9-0-0-0': 391,
  '20-65-166-0': 392,
  '12-25-89-0': 393,
  '15-297-0-0': 394,
  '21-539-0-0': 395,
  '2-130-741-0': 396,
  '38-47-0-0': 397,
  '2-79-602-0': 398,
  '12-26-0-0': 399,
  '15-695-0-0': 400,
  '2-171-0-0': 401,
  '1235-107-0-0': 402,
  '12-45-0-0': 403,
  '9-651-0-0': 404,
  '12-85-0-0': 405,
  '12-25-109-361': 406,
  '2-92-81-0': 407,
  '38-1-0-0': 408,
  '12-45-53-90': 409,
  '20-65-43-0': 410,
  '2-176-0-0': 411,
  '38-32-0-0': 412,
  '10-362-0-0': 413,
  '4-0-0-0': 414,
  '21-0-0-0': 415,
  '12-31-439-0': 416,
  '38-186-0-0': 417,
  '12-31-0-0': 418,
  '4-74-0-0': 419,
  '12-25-71-0': 420,
  '15-337-0-0': 421,
  '17-94-0-0': 422,
  '15-183-0-0': 423,
  '17-49-0-0': 424,
  '21-811-0-0': 425,
  '17-103-0-0': 426,
  '38-6-360-0': 427,
  '12-0-0-0': 428,
  '38-30-0-0': 429,
  '4-97-0-0': 430,
  '21-83-0-0': 431,
  '5-322-0-0': 432,
  '10-76-0-0': 433},
 'label5': {'2-77-0-0-0': 0,
  '15-182-0-0-0': 1,
  '14-0-0-0-0': 2,
  '2-0-0-0-0': 3,
  '12-45-53-0-0': 4,
  '12-314-0-0-0': 5,
  '14-11-0-0-0': 6,
  '9-137-0-0-0': 7,
  '2-171-0-0-0': 8,
  '2-102-0-0-0': 9,
  '4-97-0-0-0': 10,
  '38-247-0-0-0': 11,
  '12-26-113-0-0': 12,
  '5-187-0-0-0': 13,
  '12-25-109-361-0': 14,
  '17-94-0-0-0': 15,
  '2-176-0-0-0': 16,
  '4-179-0-0-0': 17,
  '20-65-43-0-0': 18,
  '38-30-0-0-0': 19,
  '21-693-0-0-0': 20,
  '12-45-53-90-0': 21,
  '5-441-0-0-0': 22,
  '38-41-0-0-0': 23,
  '15-181-401-0-0': 24,
  '2-79-0-0-0': 25,
  '20-378-0-0-0': 26,
  '15-468-491-0-0': 27,
  '9-651-0-0-0': 28,
  '15-297-0-0-0': 29,
  '17-33-0-0-0': 30,
  '17-180-0-0-0': 31,
  '20-374-0-0-0': 32,
  '2-46-502-0-0': 33,
  '15-0-0-0-0': 34,
  '3-0-0-0-0': 35,
  '20-65-0-0-0': 36,
  '12-27-0-0-0': 37,
  '15-183-0-0-0': 38,
  '15-181-0-0-0': 39,
  '12-70-0-0-0': 40,
  '14-19-0-0-0': 41,
  '15-184-0-0-0': 42,
  '17-0-0-0-0': 43,
  '38-47-0-0-0': 44,
  '5-442-0-0-0': 45,
  '4-37-0-0-0': 46,
  '17-103-0-0-0': 47,
  '38-6-360-0-0': 48,
  '21-83-0-0-0': 49,
  '15-468-0-0-0': 50,
  '12-26-0-0-0': 51,
  '13-170-0-0-0': 52,
  '15-296-0-0-0': 53,
  '2-177-0-0-0': 54,
  '2-102-1032-0-0': 55,
  '12-31-167-0-0': 56,
  '10-76-0-0-0': 57,
  '12-98-0-0-0': 58,
  '38-1-0-0-0': 59,
  '38-6-16-763-1193': 60,
  '38-6-0-0-0': 61,
  '2-86-0-0-0': 62,
  '21-580-0-0-0': 63,
  '15-337-0-0-0': 64,
  '4-0-0-0-0': 65,
  '2-92-214-0-0': 66,
  '12-25-109-0-0': 67,
  '38-0-0-0-0': 68,
  '12-25-111-0-0': 69,
  '20-428-0-0-0': 70,
  '12-440-0-0-0': 71,
  '38-6-16-763-0': 72,
  '2-79-602-0-0': 73,
  '2-92-81-0-0': 74,
  '15-495-0-0-0': 75,
  '2-46-0-0-0': 76,
  '21-0-0-0-0': 77,
  '3-567-0-0-0': 78,
  '2-86-174-0-0': 79,
  '12-85-404-0-0': 80,
  '38-125-0-0-0': 81,
  '12-25-89-0-0': 82,
  '1235-267-0-0-0': 83,
  '12-25-0-0-0': 84,
  '2-118-0-0-0': 85,
  '15-185-0-0-0': 86,
  '4-74-0-0-0': 87,
  '2-130-524-0-0': 88,
  '2-117-0-0-0': 89,
  '5-659-0-0-0': 90,
  '38-514-0-0-0': 91,
  '20-138-0-0-0': 92,
  '12-45-0-0-0': 93,
  '21-100-0-0-0': 94,
  '5-0-0-0-0': 95,
  '12-25-64-0-0': 96,
  '12-66-0-0-0': 97,
  '12-31-439-0-0': 98,
  '5-322-0-0-0': 99,
  '9-0-0-0-0': 100,
  '10-362-0-0-0': 101,
  '15-286-0-0-0': 102,
  '15-297-240-0-0': 103,
  '20-0-0-0-0': 104,
  '38-456-0-0-0': 105,
  '4-906-0-0-0': 106,
  '12-0-0-0-0': 107,
  '1235-18-538-0-0': 108,
  '12-36-0-0-0': 109,
  '12-359-0-0-0': 110,
  '13-810-0-0-0': 111,
  '2-130-0-0-0': 112,
  '2-92-0-0-0': 113,
  '21-539-0-0-0': 114,
  '15-182-400-0-0': 115,
  '20-188-0-0-0': 116,
  '15-236-0-0-0': 117,
  '8-0-0-0-0': 118,
  '2-172-0-0-0': 119,
  '12-31-0-0-0': 120,
  '2-504-0-0-0': 121,
  '20-465-0-0-0': 122,
  '38-32-0-0-0': 123,
  '20-65-166-0-0': 124,
  '12-88-0-0-0': 125,
  '12-25-71-0-0': 126,
  '2-130-619-0-0': 127,
  '2-130-741-0-0': 128,
  '38-22-0-0-0': 129,
  '10-0-0-0-0': 130,
  '5-443-0-0-0': 131,
  '9-63-0-0-0': 132,
  '1235-0-0-0-0': 133,
  '38-186-0-0-0': 134,
  '15-695-0-0-0': 135,
  '9-169-0-0-0': 136,
  '12-31-101-0-0': 137,
  '38-224-0-0-0': 138,
  '1235-18-0-0-0': 139,
  '2-232-0-0-0': 140,
  '12-85-0-0-0': 141,
  '13-311-0-0-0': 142,
  '2-130-1156-0-0': 143,
  '12-58-0-0-0': 144,
  '2-46-1060-0-0': 145,
  '21-542-0-0-0': 146,
  '15-42-0-0-0': 147,
  '17-49-0-0-0': 148,
  '1235-107-0-0-0': 149,
  '21-811-0-0-0': 150,
  '38-250-0-0-0': 151},
 'label1_inverse': ['12',
  '2',
  '38',
  '15',
  '10',
  '20',
  '4',
  '17',
  '8',
  '13',
  '14',
  '9',
  '1235',
  '3',
  '21',
  '5'],
 'label2_inverse': ['17-103',
  '10-362',
  '12-314',
  '12-36',
  '15-468',
  '14-11',
  '13-810',
  '15-185',
  '38-32',
  '17-0',
  '2-0',
  '15-495',
  '2-118',
  '4-0',
  '38-250',
  '12-359',
  '14-0',
  '21-580',
  '15-296',
  '2-102',
  '1235-0',
  '15-236',
  '2-176',
  '20-374',
  '13-311',
  '38-0',
  '5-0',
  '17-180',
  '5-441',
  '38-125',
  '12-440',
  '17-49',
  '20-65',
  '21-0',
  '5-322',
  '13-170',
  '2-177',
  '2-86',
  '2-46',
  '15-183',
  '2-172',
  '15-695',
  '15-181',
  '21-539',
  '12-25',
  '12-27',
  '20-188',
  '20-138',
  '4-906',
  '38-514',
  '3-0',
  '12-0',
  '38-41',
  '5-659',
  '2-77',
  '20-0',
  '38-186',
  '2-117',
  '15-286',
  '12-58',
  '20-465',
  '38-456',
  '12-31',
  '15-297',
  '5-442',
  '2-504',
  '5-187',
  '3-567',
  '12-85',
  '9-137',
  '2-232',
  '38-224',
  '9-0',
  '9-169',
  '12-70',
  '38-22',
  '20-378',
  '9-651',
  '5-443',
  '12-26',
  '12-45',
  '8-0',
  '15-337',
  '4-74',
  '21-693',
  '17-94',
  '38-6',
  '15-42',
  '21-100',
  '15-184',
  '38-247',
  '2-130',
  '4-37',
  '21-811',
  '14-19',
  '38-47',
  '9-63',
  '12-88',
  '12-66',
  '12-98',
  '2-79',
  '10-0',
  '20-428',
  '21-542',
  '2-92',
  '21-83',
  '1235-107',
  '38-1',
  '1235-18',
  '2-171',
  '10-76',
  '1235-267',
  '4-179',
  '38-30',
  '15-0',
  '4-97',
  '17-33',
  '15-182'],
 'label3_inverse': ['38-47-0',
  '15-337-0',
  '38-6-0',
  '12-31-101',
  '9-651-0',
  '38-514-0',
  '12-27-0',
  '12-31-439',
  '12-25-111',
  '12-26-113',
  '17-94-0',
  '17-180-0',
  '9-169-0',
  '4-906-0',
  '2-177-0',
  '20-0-0',
  '15-42-0',
  '1235-18-538',
  '2-176-0',
  '2-130-0',
  '38-456-0',
  '2-79-0',
  '2-46-502',
  '38-250-0',
  '21-580-0',
  '17-49-0',
  '17-33-0',
  '12-314-0',
  '12-45-0',
  '12-45-53',
  '20-65-0',
  '15-236-0',
  '4-74-0',
  '9-0-0',
  '21-83-0',
  '38-6-16',
  '15-184-0',
  '1235-107-0',
  '12-31-167',
  '21-693-0',
  '8-0-0',
  '12-36-0',
  '2-130-524',
  '2-118-0',
  '38-30-0',
  '38-0-0',
  '20-465-0',
  '2-130-741',
  '13-810-0',
  '5-441-0',
  '20-428-0',
  '2-46-0',
  '12-31-0',
  '38-1-0',
  '2-130-619',
  '12-85-404',
  '15-182-0',
  '12-0-0',
  '38-125-0',
  '2-86-0',
  '5-0-0',
  '15-185-0',
  '10-0-0',
  '15-495-0',
  '10-76-0',
  '12-85-0',
  '2-102-0',
  '38-22-0',
  '5-322-0',
  '12-25-0',
  '21-539-0',
  '1235-267-0',
  '2-102-1032',
  '4-0-0',
  '12-58-0',
  '10-362-0',
  '4-179-0',
  '20-374-0',
  '2-86-174',
  '2-79-602',
  '15-183-0',
  '2-172-0',
  '3-0-0',
  '17-0-0',
  '4-97-0',
  '15-0-0',
  '2-130-1156',
  '12-70-0',
  '9-137-0',
  '14-19-0',
  '15-182-400',
  '2-117-0',
  '20-138-0',
  '2-77-0',
  '38-224-0',
  '15-286-0',
  '38-32-0',
  '3-567-0',
  '2-232-0',
  '2-504-0',
  '12-359-0',
  '14-11-0',
  '12-26-0',
  '20-65-166',
  '9-63-0',
  '5-187-0',
  '38-247-0',
  '15-468-491',
  '12-88-0',
  '12-25-64',
  '4-37-0',
  '15-297-240',
  '21-542-0',
  '1235-0-0',
  '5-442-0',
  '2-46-1060',
  '12-25-71',
  '12-66-0',
  '13-311-0',
  '2-92-0',
  '17-103-0',
  '38-41-0',
  '2-92-81',
  '20-378-0',
  '13-170-0',
  '2-171-0',
  '1235-18-0',
  '20-188-0',
  '14-0-0',
  '5-659-0',
  '15-296-0',
  '12-25-109',
  '12-25-89',
  '38-6-360',
  '12-98-0',
  '15-695-0',
  '12-440-0',
  '20-65-43',
  '5-443-0',
  '2-0-0',
  '21-811-0',
  '15-181-0',
  '21-0-0',
  '15-468-0',
  '21-100-0',
  '2-92-214',
  '38-186-0',
  '15-297-0',
  '15-181-401'],
 'label4_inverse': ['3-0-0-0',
  '15-297-240-0',
  '9-169-0-0',
  '20-428-0-0',
  '2-92-214-0',
  '15-42-0-0',
  '38-0-0-0',
  '2-172-0-0',
  '12-314-0-0',
  '38-250-0-0',
  '5-441-0-0',
  '12-36-0-0',
  '20-374-0-0',
  '2-504-0-0',
  '2-86-0-0',
  '2-118-0-0',
  '17-33-0-0',
  '3-567-0-0',
  '2-117-0-0',
  '38-125-0-0',
  '15-286-0-0',
  '17-180-0-0',
  '15-184-0-0',
  '38-6-0-0',
  '2-0-0-0',
  '8-0-0-0',
  '2-46-1060-0',
  '13-311-0-0',
  '14-0-0-0',
  '15-185-0-0',
  '12-58-0-0',
  '12-26-113-0',
  '5-443-0-0',
  '38-6-16-763',
  '9-63-0-0',
  '12-25-109-0',
  '20-0-0-0',
  '2-232-0-0',
  '15-236-0-0',
  '2-130-1156-0',
  '38-22-0-0',
  '38-247-0-0',
  '14-19-0-0',
  '2-46-502-0',
  '20-465-0-0',
  '38-224-0-0',
  '12-25-64-0',
  '20-378-0-0',
  '12-66-0-0',
  '15-468-0-0',
  '38-514-0-0',
  '21-693-0-0',
  '2-86-174-0',
  '5-187-0-0',
  '4-906-0-0',
  '2-77-0-0',
  '12-359-0-0',
  '15-0-0-0',
  '20-65-0-0',
  '2-130-0-0',
  '2-102-0-0',
  '14-11-0-0',
  '15-495-0-0',
  '13-170-0-0',
  '5-0-0-0',
  '12-31-101-0',
  '20-138-0-0',
  '2-130-524-0',
  '15-296-0-0',
  '12-31-167-0',
  '21-580-0-0',
  '12-88-0-0',
  '12-98-0-0',
  '2-46-0-0',
  '2-92-0-0',
  '1235-0-0-0',
  '21-100-0-0',
  '12-70-0-0',
  '38-41-0-0',
  '2-130-619-0',
  '4-37-0-0',
  '15-468-491-0',
  '15-182-0-0',
  '10-0-0-0',
  '1235-267-0-0',
  '12-45-53-0',
  '2-102-1032-0',
  '2-177-0-0',
  '2-79-0-0',
  '13-810-0-0',
  '5-659-0-0',
  '17-0-0-0',
  '21-542-0-0',
  '12-25-111-0',
  '9-137-0-0',
  '15-182-400-0',
  '20-188-0-0',
  '5-442-0-0',
  '15-181-0-0',
  '1235-18-0-0',
  '4-179-0-0',
  '38-456-0-0',
  '12-440-0-0',
  '12-85-404-0',
  '12-25-0-0',
  '15-181-401-0',
  '1235-18-538-0',
  '12-27-0-0',
  '9-0-0-0',
  '20-65-166-0',
  '12-25-89-0',
  '15-297-0-0',
  '21-539-0-0',
  '2-130-741-0',
  '38-47-0-0',
  '2-79-602-0',
  '12-26-0-0',
  '15-695-0-0',
  '2-171-0-0',
  '1235-107-0-0',
  '12-45-0-0',
  '9-651-0-0',
  '12-85-0-0',
  '12-25-109-361',
  '2-92-81-0',
  '38-1-0-0',
  '12-45-53-90',
  '20-65-43-0',
  '2-176-0-0',
  '38-32-0-0',
  '10-362-0-0',
  '4-0-0-0',
  '21-0-0-0',
  '12-31-439-0',
  '38-186-0-0',
  '12-31-0-0',
  '4-74-0-0',
  '12-25-71-0',
  '15-337-0-0',
  '17-94-0-0',
  '15-183-0-0',
  '17-49-0-0',
  '21-811-0-0',
  '17-103-0-0',
  '38-6-360-0',
  '12-0-0-0',
  '38-30-0-0',
  '4-97-0-0',
  '21-83-0-0',
  '5-322-0-0',
  '10-76-0-0'],
 'label5_inverse': ['2-77-0-0-0',
  '15-182-0-0-0',
  '14-0-0-0-0',
  '2-0-0-0-0',
  '12-45-53-0-0',
  '12-314-0-0-0',
  '14-11-0-0-0',
  '9-137-0-0-0',
  '2-171-0-0-0',
  '2-102-0-0-0',
  '4-97-0-0-0',
  '38-247-0-0-0',
  '12-26-113-0-0',
  '5-187-0-0-0',
  '12-25-109-361-0',
  '17-94-0-0-0',
  '2-176-0-0-0',
  '4-179-0-0-0',
  '20-65-43-0-0',
  '38-30-0-0-0',
  '21-693-0-0-0',
  '12-45-53-90-0',
  '5-441-0-0-0',
  '38-41-0-0-0',
  '15-181-401-0-0',
  '2-79-0-0-0',
  '20-378-0-0-0',
  '15-468-491-0-0',
  '9-651-0-0-0',
  '15-297-0-0-0',
  '17-33-0-0-0',
  '17-180-0-0-0',
  '20-374-0-0-0',
  '2-46-502-0-0',
  '15-0-0-0-0',
  '3-0-0-0-0',
  '20-65-0-0-0',
  '12-27-0-0-0',
  '15-183-0-0-0',
  '15-181-0-0-0',
  '12-70-0-0-0',
  '14-19-0-0-0',
  '15-184-0-0-0',
  '17-0-0-0-0',
  '38-47-0-0-0',
  '5-442-0-0-0',
  '4-37-0-0-0',
  '17-103-0-0-0',
  '38-6-360-0-0',
  '21-83-0-0-0',
  '15-468-0-0-0',
  '12-26-0-0-0',
  '13-170-0-0-0',
  '15-296-0-0-0',
  '2-177-0-0-0',
  '2-102-1032-0-0',
  '12-31-167-0-0',
  '10-76-0-0-0',
  '12-98-0-0-0',
  '38-1-0-0-0',
  '38-6-16-763-1193',
  '38-6-0-0-0',
  '2-86-0-0-0',
  '21-580-0-0-0',
  '15-337-0-0-0',
  '4-0-0-0-0',
  '2-92-214-0-0',
  '12-25-109-0-0',
  '38-0-0-0-0',
  '12-25-111-0-0',
  '20-428-0-0-0',
  '12-440-0-0-0',
  '38-6-16-763-0',
  '2-79-602-0-0',
  '2-92-81-0-0',
  '15-495-0-0-0',
  '2-46-0-0-0',
  '21-0-0-0-0',
  '3-567-0-0-0',
  '2-86-174-0-0',
  '12-85-404-0-0',
  '38-125-0-0-0',
  '12-25-89-0-0',
  '1235-267-0-0-0',
  '12-25-0-0-0',
  '2-118-0-0-0',
  '15-185-0-0-0',
  '4-74-0-0-0',
  '2-130-524-0-0',
  '2-117-0-0-0',
  '5-659-0-0-0',
  '38-514-0-0-0',
  '20-138-0-0-0',
  '12-45-0-0-0',
  '21-100-0-0-0',
  '5-0-0-0-0',
  '12-25-64-0-0',
  '12-66-0-0-0',
  '12-31-439-0-0',
  '5-322-0-0-0',
  '9-0-0-0-0',
  '10-362-0-0-0',
  '15-286-0-0-0',
  '15-297-240-0-0',
  '20-0-0-0-0',
  '38-456-0-0-0',
  '4-906-0-0-0',
  '12-0-0-0-0',
  '1235-18-538-0-0',
  '12-36-0-0-0',
  '12-359-0-0-0',
  '13-810-0-0-0',
  '2-130-0-0-0',
  '2-92-0-0-0',
  '21-539-0-0-0',
  '15-182-400-0-0',
  '20-188-0-0-0',
  '15-236-0-0-0',
  '8-0-0-0-0',
  '2-172-0-0-0',
  '12-31-0-0-0',
  '2-504-0-0-0',
  '20-465-0-0-0',
  '38-32-0-0-0',
  '20-65-166-0-0',
  '12-88-0-0-0',
  '12-25-71-0-0',
  '2-130-619-0-0',
  '2-130-741-0-0',
  '38-22-0-0-0',
  '10-0-0-0-0',
  '5-443-0-0-0',
  '9-63-0-0-0',
  '1235-0-0-0-0',
  '38-186-0-0-0',
  '15-695-0-0-0',
  '9-169-0-0-0',
  '12-31-101-0-0',
  '38-224-0-0-0',
  '1235-18-0-0-0',
  '2-232-0-0-0',
  '12-85-0-0-0',
  '13-311-0-0-0',
  '2-130-1156-0-0',
  '12-58-0-0-0',
  '2-46-1060-0-0',
  '21-542-0-0-0',
  '15-42-0-0-0',
  '17-49-0-0-0',
  '1235-107-0-0-0',
  '21-811-0-0-0',
  '38-250-0-0-0'],
 'label1_name': {'17-103': 'Folk',
  '12-66': 'Rock',
  '38-6': 'Experimental',
  '5-187': 'Classical',
  '15-495': 'Electronic',
  '12-85': 'Rock',
  '38-247': 'Experimental',

In [59]:
categories_df['labels_1_'] = categories_df.labels_1.apply(lambda x: labels['label1'].get(x))
categories_df['labels_2_'] = categories_df.labels_2.apply(lambda x: labels['label2'].get(x))
categories_df['labels_3_'] = categories_df.labels_3.apply(lambda x: labels['label3'].get(x))
categories_df['labels_4_'] = categories_df.labels_4.apply(lambda x: labels['label4'].get(x))
categories_df['labels_5_'] = categories_df.labels_5.apply(lambda x: labels['label5'].get(x))

In [60]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name,labels_1_,labels_2_,labels_3_,labels_4_,labels_5_
29057,17,17-103,17-103-0,17-103-0-0,17-103-0-0-0,Folk>Singer-Songwriter>Singer-Songwriter>Singe...,7,16,254,426,47
22381,12,12-66,12-66-0,12-66-0-0,12-66-0-0-0,Rock>Indie-Rock>Indie-Rock>Indie-Rock>Indie-Rock,0,114,251,331,97
68454,38,38-6,38-6-360,38-6-360-0,38-6-360-0-0,Experimental>Novelty>Kid-Friendly>Kid-Friendly...,2,102,267,427,48
9377,5,5-187,5-187-0,5-187-0-0,5-187-0-0-0,Classical>20th Century Classical>20th Century ...,15,82,239,336,13
47251,15,15-495,15-495-0,15-495-0-0,15-495-0-0-0,Electronic>Downtempo>Downtempo>Downtempo>Downt...,3,27,197,345,75
...,...,...,...,...,...,...,...,...,...,...,...
67893,2,2-130,2-130-1156,2-130-1156-0,2-130-1156-0-0,International>Europe>Fado>Fado>Fado,1,107,220,322,143
62469,21,21-83,21-83-0,21-83-0-0,21-83-0-0-0,Hip-Hop>Nerdcore>Nerdcore>Nerdcore>Nerdcore,14,121,168,431,49
78801,13,13-170,13-170-0,13-170-0-0,13-170-0-0-0,Easy Listening>Easy Listening: Vocal>Easy List...,9,51,258,346,52
16869,2,2-117,2-117-0,2-117-0-0,2-117-0-0-0,International>Polka>Polka>Polka>Polka,1,73,225,301,89
12866,2,2-176,2-176-0,2-176-0-0,2-176-0-0-0,International>Pacific>Pacific>Pacific>Pacific,1,38,152,411,16

In [61]:
unique_labels_1 = categories_df['labels_1_'].unique().tolist()
unique_labels_2 = categories_df['labels_2_'].unique().tolist()
unique_labels_3 = categories_df['labels_3_'].unique().tolist()
unique_labels_4 = categories_df['labels_4_'].unique().tolist()
unique_labels_5 = categories_df['labels_5_'].unique().tolist()

In [62]:
unique_labels_1

[7, 0, 2, 15, 3, 12, 9, 14, 4, 13, 1, 5, 10, 6, 8, 11]

In [63]:
num_nodes_per_level = [len(unique_labels_1), len(unique_labels_2), len(unique_labels_3), len(unique_labels_4), len(unique_labels_5)]

In [64]:

# num_classes_per_node = [
#     [5, 4, 6],  # Nível 1: 3 nós com 5, 4 e 6 classes
#     [3, 2, 4, 5],  # Nível 2: 4 nós com 3, 2, 4 e 5 classes
#     [4, 3, 5, 2, 6],  # Nível 3: 5 nós com 4, 3, 5, 2 e 6 classes
#     [2, 3, 4, 5, 3, 2],  # Nível 4: 6 nós com 2, 3, 4, 5, 3 e 2 classes
#     [5, 6, 3, 4, 2, 3, 4],  # Nível 5: 7 nós com 5, 6, 3, 4, 2, 3 e 4 classes
#

In [65]:
# num_classes_per_node.append(unique_labels_1)  # Nível 1

In [66]:
# Cálculo de num_classes_per_node

In [67]:
level_1 = categories_df[['labels_1_','labels_2_']].groupby('labels_1_').count()['labels_2_'].values.tolist()

In [68]:
level_2 = categories_df[['labels_2_','labels_3_']].groupby('labels_2_').count()['labels_3_'].values.tolist()

In [69]:
level_3 = categories_df[['labels_3_','labels_4_']].groupby('labels_3_').count()['labels_4_'].values.tolist()

In [70]:
level_4 = categories_df[['labels_4_','labels_5_']].groupby('labels_4_').count()['labels_5_'].values.tolist()

In [165]:
level_5 = unique_labels_5

In [166]:
len(unique_labels_5)

152

In [167]:
num_classes_per_node = [level_1,level_2,level_3,level_4,level_5]

In [168]:
print("num_nodes_per_level:", num_nodes_per_level[0])

num_nodes_per_level: 16

In [169]:
labels['label5']

{'2-77-0-0-0': 0,
 '15-182-0-0-0': 1,
 '14-0-0-0-0': 2,
 '2-0-0-0-0': 3,
 '12-45-53-0-0': 4,
 '12-314-0-0-0': 5,
 '14-11-0-0-0': 6,
 '9-137-0-0-0': 7,
 '2-171-0-0-0': 8,
 '2-102-0-0-0': 9,
 '4-97-0-0-0': 10,
 '38-247-0-0-0': 11,
 '12-26-113-0-0': 12,
 '5-187-0-0-0': 13,
 '12-25-109-361-0': 14,
 '17-94-0-0-0': 15,
 '2-176-0-0-0': 16,
 '4-179-0-0-0': 17,
 '20-65-43-0-0': 18,
 '38-30-0-0-0': 19,
 '21-693-0-0-0': 20,
 '12-45-53-90-0': 21,
 '5-441-0-0-0': 22,
 '38-41-0-0-0': 23,
 '15-181-401-0-0': 24,
 '2-79-0-0-0': 25,
 '20-378-0-0-0': 26,
 '15-468-491-0-0': 27,
 '9-651-0-0-0': 28,
 '15-297-0-0-0': 29,
 '17-33-0-0-0': 30,
 '17-180-0-0-0': 31,
 '20-374-0-0-0': 32,
 '2-46-502-0-0': 33,
 '15-0-0-0-0': 34,
 '3-0-0-0-0': 35,
 '20-65-0-0-0': 36,
 '12-27-0-0-0': 37,
 '15-183-0-0-0': 38,
 '15-181-0-0-0': 39,
 '12-70-0-0-0': 40,
 '14-19-0-0-0': 41,
 '15-184-0-0-0': 42,
 '17-0-0-0-0': 43,
 '38-47-0-0-0': 44,
 '5-442-0-0-0': 45,
 '4-37-0-0-0': 46,
 '17-103-0-0-0': 47,
 '38-6-360-0-0': 48,
 '21-83-0-0-0': 49,
 '15-468-0-0-0': 50,
 '12-26-0-0-0': 51,
 '13-170-0-0-0': 52,
 '15-296-0-0-0': 53,
 '2-177-0-0-0': 54,
 '2-102-1032-0-0': 55,
 '12-31-167-0-0': 56,
 '10-76-0-0-0': 57,
 '12-98-0-0-0': 58,
 '38-1-0-0-0': 59,
 '38-6-16-763-1193': 60,
 '38-6-0-0-0': 61,
 '2-86-0-0-0': 62,
 '21-580-0-0-0': 63,
 '15-337-0-0-0': 64,
 '4-0-0-0-0': 65,
 '2-92-214-0-0': 66,
 '12-25-109-0-0': 67,
 '38-0-0-0-0': 68,
 '12-25-111-0-0': 69,
 '20-428-0-0-0': 70,
 '12-440-0-0-0': 71,
 '38-6-16-763-0': 72,
 '2-79-602-0-0': 73,
 '2-92-81-0-0': 74,
 '15-495-0-0-0': 75,
 '2-46-0-0-0': 76,
 '21-0-0-0-0': 77,
 '3-567-0-0-0': 78,
 '2-86-174-0-0': 79,
 '12-85-404-0-0': 80,
 '38-125-0-0-0': 81,
 '12-25-89-0-0': 82,
 '1235-267-0-0-0': 83,
 '12-25-0-0-0': 84,
 '2-118-0-0-0': 85,
 '15-185-0-0-0': 86,
 '4-74-0-0-0': 87,
 '2-130-524-0-0': 88,
 '2-117-0-0-0': 89,
 '5-659-0-0-0': 90,
 '38-514-0-0-0': 91,
 '20-138-0-0-0': 92,
 '12-45-0-0-0': 93,
 '21-100-0-0-0': 94,
 '5-0-0-0-0': 95,
 '12-25-64-0-0': 96,
 '12-66-0-0-0': 97,
 '12-31-439-0-0': 98,
 '5-322-0-0-0': 99,
 '9-0-0-0-0': 100,
 '10-362-0-0-0': 101,
 '15-286-0-0-0': 102,
 '15-297-240-0-0': 103,
 '20-0-0-0-0': 104,
 '38-456-0-0-0': 105,
 '4-906-0-0-0': 106,
 '12-0-0-0-0': 107,
 '1235-18-538-0-0': 108,
 '12-36-0-0-0': 109,
 '12-359-0-0-0': 110,
 '13-810-0-0-0': 111,
 '2-130-0-0-0': 112,
 '2-92-0-0-0': 113,
 '21-539-0-0-0': 114,
 '15-182-400-0-0': 115,
 '20-188-0-0-0': 116,
 '15-236-0-0-0': 117,
 '8-0-0-0-0': 118,
 '2-172-0-0-0': 119,
 '12-31-0-0-0': 120,
 '2-504-0-0-0': 121,
 '20-465-0-0-0': 122,
 '38-32-0-0-0': 123,
 '20-65-166-0-0': 124,
 '12-88-0-0-0': 125,
 '12-25-71-0-0': 126,
 '2-130-619-0-0': 127,
 '2-130-741-0-0': 128,
 '38-22-0-0-0': 129,
 '10-0-0-0-0': 130,
 '5-443-0-0-0': 131,
 '9-63-0-0-0': 132,
 '1235-0-0-0-0': 133,
 '38-186-0-0-0': 134,
 '15-695-0-0-0': 135,
 '9-169-0-0-0': 136,
 '12-31-101-0-0': 137,
 '38-224-0-0-0': 138,
 '1235-18-0-0-0': 139,
 '2-232-0-0-0': 140,
 '12-85-0-0-0': 141,
 '13-311-0-0-0': 142,
 '2-130-1156-0-0': 143,
 '12-58-0-0-0': 144,
 '2-46-1060-0-0': 145,
 '21-542-0-0-0': 146,
 '15-42-0-0-0': 147,
 '17-49-0-0-0': 148,
 '1235-107-0-0-0': 149,
 '21-811-0-0-0': 150,
 '38-250-0-0-0': 151}

In [170]:
labels['label1_count']

16

In [171]:


def parse_tfr_element(element):
    #use the same structure as above; it's kinda an outline of the structure we now want to create
    data = {
        'emb' : tf.io.FixedLenFeature([], tf.string),
        'track_id' : tf.io.FixedLenFeature([], tf.int64),
    }
    
    content = tf.io.parse_single_example(element, data)

    track_id = content['track_id']
    emb = content['emb']
    

    #get our 'feature'-- our image -- and reshape it appropriately
    feature = tf.io.parse_tensor(emb, out_type=tf.float32)
    return (feature, track_id)


def get_dataset(filename):
    #create the dataset
    dataset = tf.data.TFRecordDataset(filename)

    #pass every single feature through our mapping function
    dataset = dataset.map(
        parse_tfr_element
    )

    return dataset

In [172]:
import numpy as np


def load_dataset(path,dataset=args.embeddings):
    tfrecords_path = os.path.join(path,'tfrecords',dataset)
    
    
    tfrecords_path = [os.path.join(tfrecords_path,path) for path in os.listdir(tfrecords_path)]
    dataset = get_dataset(tfrecords_path)
    
    df = pd.DataFrame(
        dataset.as_numpy_iterator(),
        columns=['feature', 'track_id']
    )
        
    df.dropna(inplace=True)
    
    
    try:
        df.feature = df.feature.apply(lambda x: x[0] if x.shape[0] != 0 else None)
    except:
        print(x)
    
    return df

In [173]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0        624
1235-0-0-0-0      588
10-76-0-0-0       405
1235-107-0-0-0    396
21-0-0-0-0        369
                 ...
2-232-0-0-0         1
2-86-174-0-0        1
2-130-1156-0-0      1
2-117-0-0-0         1
2-176-0-0-0         1
Name: count, Length: 152, dtype: int64

In [174]:
def __split_data__(group, percentage=0.1):
    if len(group) == 1:
        return group, group

    shuffled = shuffle(group.values)
    finish_test = int(ceil(len(group) * percentage))

    first = pd.DataFrame(shuffled[:finish_test], columns=group.columns)
    second = pd.DataFrame(shuffled[finish_test:], columns=group.columns)

    return first, second

In [175]:
def select_dataset(tracks_df):
    
#     dataset_testset_path = os.path.join(tfrecord_path,'test')
#     dataset_validationset_path = os.path.join(tfrecord_path,'val')
#     dataset_trainset_path = os.path.join(tfrecord_path,'train')
    
    df = load_dataset(args.dataset_path,dataset=args.embeddings)
    
    df.dropna(inplace=True)
    
    tracks_df = tracks_df.merge(df, on='track_id')
    
    tracks_df.loc[:,'labels_1'] = tracks_df.labels_1.astype(str).progress_apply(lambda x: labels['label1'][x])
    tracks_df.loc[:,'labels_2'] = tracks_df.labels_2.astype(str).progress_apply(lambda x: labels['label2'][x])
    tracks_df.loc[:,'labels_3'] = tracks_df.labels_3.astype(str).progress_apply(lambda x: labels['label3'][x])
    tracks_df.loc[:,'labels_4'] = tracks_df.labels_4.astype(str).progress_apply(lambda x: labels['label4'][x])
    tracks_df.loc[:,'labels_5'] = tracks_df.labels_5.astype(str).progress_apply(lambda x: labels['label5'][x])
    
    tests = []
    trains = []
    validations = []
    groups = tracks_df.groupby("labels_5")
    
    
    count = 0
    items_count = 0
    total = len(groups)
    total_items = len(tracks_df)
    oversampling_size = 30  # int(group_sizes.mean() + group_sizes.std() * 2)
    print(f"oversampling_size: {oversampling_size}")

    for code, group in groups:
        test, train_to_split = __split_data__(group, 0.01)  # 10%
        train_to_split = train_to_split
        validation, train = __split_data__(train_to_split, 0.01)  # %1

        tests.append(test)
        validations.append(validation)

        ## this increase the numner of samples when classes has low quantity
        count_train = len(train)
        if count_train < oversampling_size:
            train = train.sample(oversampling_size, replace=True)

        trains.append(train)

        count += 1
        items_count += count_train
        
        
    df_test = pd.concat(tests, sort=False).sample(frac=1).reset_index(drop=True)
    # .to_csv(dataset_testset_path, index=False,quoting=csv.QUOTE_ALL)
    df_val = pd.concat(validations, sort=False).sample(frac=1).reset_index(drop=True)
    df_train = pd.concat(trains, sort=False).sample(frac=1).reset_index(drop=True)

    return df_train,df_test,df_val

In [176]:
df_train,df_test,df_val = select_dataset(tracks_df)

2023-07-17 12:53:32.697043: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [11]
	 [[{{node Placeholder/_0}}]]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

oversampling_size: 30

In [177]:
df_train

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5,feature
0,17856,"[12, 25, 89]",0,60,266,393,82,"[0.017008772, 0.065834396, -0.03507653, -0.052..."
1,84366,"[38, 47]",2,111,134,397,44,"[0.126246, 0.06133796, 0.14608513, -0.01312364..."
2,27334,[38],2,41,179,289,68,"[0.018960765, 0.02848827, -0.03721274, -0.0759..."
3,114199,"[12, 31]",0,78,186,418,120,"[-0.022568991, 0.2693565, 0.06729948, 0.254982..."
4,19952,[38],2,41,179,289,68,"[0.05234739, 0.025431642, -0.034939837, 0.0448..."
...,...,...,...,...,...,...,...,...
11631,135501,"[21, 580]",14,33,158,353,63,"[-0.0408477, 0.04249225, -0.012698402, 0.02693..."
11632,131119,"[12, 85]",0,84,199,405,141,"[-0.0031871896, 0.08408148, -0.0354984, -0.011..."
11633,153372,"[10, 76]",4,126,198,433,57,"[0.005718887, 0.18871093, -0.018126706, 0.2683..."
11634,27669,"[15, 236]",3,37,165,321,117,"[-0.015856326, 0.028849443, -0.028916618, -0.0..."
11635,64661,"[12, 66]",0,114,251,331,97,"[0.037647646, -0.027751694, -0.071443945, -0.0..."

In [178]:
def _bytes_feature(value):
  ### Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))): # if value ist tensor
        value = value.numpy() # get value of tensor
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def _float_feature(value):
  ### Returns a floast_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64List_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def _int64_feature(value):
  ###  Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def serialize_array(array):
    array = tf.io.serialize_tensor(array)
    return array

In [179]:
def parse_single_music(data,labels):
    track_id, _, cat1, cat2, cat3, cat4, cat5, music = data
    
    
    label1 = np.array([cat1, labels['label1_count']], np.int64)
    label2 = np.array([cat2, labels['label2_count']], np.int64)
    label3 = np.array([cat3, labels['label3_count']], np.int64)
    label4 = np.array([cat4, labels['label4_count']], np.int64)
    label5 = np.array([cat5, labels['label5_count']], np.int64)
    
    
    
    #define the dictionary -- the structure -- of our single example
    data = {
        'label1': _int64List_feature(label1),
        'label2': _int64List_feature(label2),
        'label3': _int64List_feature(label3),
        'label4': _int64List_feature(label4),
        'label5': _int64List_feature(label5),
        # 'features' : _bytes_feature(serialize_array(music)),
        'features' : _float_feature(music),
        'track_id' : _int64_feature(track_id)
    }
    #create an Example, wrapping the single features
    out = tf.train.Example(features=tf.train.Features(feature=data))

    return out

In [180]:
def generate_tf_record(df,tf_path='val'):
    create_dir(tf_path)
    
    
    batch_size = 1024 * 50 # 50k records from each file batch
    count = 0
    total = math.ceil(len(df) / batch_size)

    for i in range(0, len(df), batch_size):
        batch_df = df[i:i+batch_size]
        
        tfrecords = [parse_single_music(data, labels) for data in batch_df.values]
        
        path = f"{tf_path}/{str(count).zfill(10)}.tfrecord"
        
        #with tf.python_io.TFRecordWriter(path) as writer:
        with tf.io.TFRecordWriter(path) as writer:
            for tfrecord in tfrecords:
                writer.write(tfrecord.SerializeToString())

        print(f"{count} {len(tfrecords)} {path}")
        count += 1
        print(f"{count}/{total} batchs / {count * batch_size} processed")

    print(f"{count}/{total} batchs / {len(df)} processed")
    
    return tf_path

In [181]:
tfrecord_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords'

In [182]:
val_path = generate_tf_record(df_val,tf_path=os.path.join(tfrecord_path,'val'))

0 211 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/val/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 211 processed

In [183]:
test_path = generate_tf_record(df_test,tf_path=os.path.join(tfrecord_path,'test'))

0 212 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/test/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 212 processed

In [184]:
train_path = generate_tf_record(df_train,tf_path=os.path.join(tfrecord_path,'train'))

0 11636 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/train/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 11636 processed

In [185]:
def create_metadata(metadata_path):

    with open(metadata_path, 'w+') as f:
        f.write(json.dumps({
            'sequence_size': args.sequence_size,
            'n_levels': labels_size,
            'num_nodes_per_level':num_nodes_per_level,
            'num_classes_per_node':num_classes_per_node,
            'labels_size': [labels['label1_count'],labels['label2_count'],
                           labels['label3_count'],labels['label4_count'],
                           labels['label5_count']],
            'val_path': val_path,
            'train_path': train_path,
            'test_path': test_path,
            'trainset_count': len(df_train),
            'validationset_count': len(df_val),
            'testset_count': len(df_test)
        }))

In [186]:
num_nodes_per_level

[16, 118, 149, 151, 152]

In [187]:
create_metadata(metadata_path)

In [188]:
job_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample'

In [189]:
tracks_df.to_csv(os.path.join(job_path,"tracks.csv"),index=False)

In [190]:
with open(categories_labels_path, 'r') as f:
    labels = json.loads(f.read())

In [191]:
with open(metadata_path, 'r') as f:
    metadata = json.loads(f.read())

In [192]:
levels_size = {'level1_size': labels['label1_count']-1,
        'level2_size': labels['label2_count']-1,
        'level3_size': labels['label3_count']-1,
        'level4_size': labels['label4_count']-1,
        'level5_size': labels['label5_count']-1}

In [193]:
levels_size['level1_size']

15

In [194]:
len(metadata['num_nodes_per_level'])

5

In [195]:
len(metadata['num_classes_per_node'])

5