In [75]:
import pandas as pd
import numpy as np
import tensorflow as tf
import json
import ast
import os
import csv
import math
from sklearn.utils import shuffle
from math import ceil
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm

In [76]:
tqdm.pandas()

In [77]:

args = pd.Series({
    "root_dir":"/mnt/disks/data/",
    "dataset_path":"/mnt/disks/data/fma/fma_large",
    "embeddings":"music_style",
    "sequence_size": 1280,
    "train_id": "hierarchical_local_sample",
    'sample_size': 0.1
})

In [78]:

base_path = "/mnt/disks/data/fma/trains"


job_path = os.path.join(base_path,args.train_id)


tfrecord_path = os.path.join(job_path,"tfrecords")

# In[16]:

base_path = os.path.join(args.root_dir,"fma")

# In[17]:

models_path = os.path.join(args.root_dir,"models")


metadata_path_fma = os.path.join(base_path,"fma_metadata")

# In[18]:

metadata_path = os.path.join(job_path,"metadata.json")


categories_labels_path = os.path.join(job_path,"labels.json")

In [79]:


def __load_json__(path):
    with open(path, 'r') as f:
        tmp = json.loads(f.read())

    return tmp

In [80]:

def create_dir(path):
    # checking if the directory demo_folder2 
    # exist or not.
    if not os.path.isdir(path):

        # if the demo_folder2 directory is 
        # not present then create it.
        os.makedirs(path)
    return True

In [81]:
import shutil
shutil.rmtree(job_path)

In [82]:
create_dir(job_path)

True

## Load genres file. Contains relationships beetwen genres

In [83]:
genres_df = pd.read_csv(os.path.join(metadata_path_fma,'genres.csv'))

In [84]:
genres_df

     genre_id  #tracks  parent          title  top_level
0           1     8693      38    Avant-Garde         38
1           2     5271       0  International          2
2           3     1752       0          Blues          3
3           4     4126       0           Jazz          4
4           5     4106       0      Classical          5
..        ...      ...     ...            ...        ...
158      1032       60     102        Turkish          2
159      1060       30      46          Tango          2
160      1156       26     130           Fado          2
161      1193       72     763      Christmas         38
162      1235    14938       0   Instrumental       1235

[163 rows x 5 columns]

In [85]:
genres_df[genres_df['genre_id'] == 495]

     genre_id  #tracks  parent      title  top_level
136       495     2061      15  Downtempo         15

In [86]:
# Cria um dicionário que associa o ID de cada música aos IDs de seus gêneros musicais
tracks_df = pd.read_csv(os.path.join(metadata_path_fma,'tracks_valid.csv'))

In [87]:
tracks_df = tracks_df.sample(frac=args.sample_size)

In [88]:
tracks_df.sample(20)

,track_id,track_title,valid_genre
75504,116179,Secrets,"['18', '38', '42']"
98769,147207,Gavotte (BWV 995),"['5', '442', '1235']"
40450,61566,Perfect Love,['182']
103980,155034,Murder,['25']
38744,59242,The Golden Hello,"['42', '181', '359']"
97244,145217,Letargo Grisaceo,"['15', '32', '38']"
2858,4855,the russian man d-va northern russian voice,"['30', '65']"
97112,145035,Tainted cloth,"['182', '296']"
88638,133408,Evening Glow,"['15', '107', '1235']"
55434,83915,"Moonglow, Lamp Low","['10', '17', '103']"
36945,56925,This One's For The Shortys,"['15', '38', '468']"
53624,81649,Into The Unknown,"['42', '107', '184']"
80700,122940,Blazing Paths,"['1', '4', '5', '12', '32', '38', '183', '378']"
102869,153474,Izgrjala E Mesecinka,"['2', '118']"
98881,147345,Larvae,"['15', '18', '107']"
13532,22255,So Sick,"['10', '15', '27', '66', '362']"
69961,108958,Hidden,"['66', '88']"
27791,42956,GEEN B,"['32', '38']"
56902,85792,Relived/Replayed,"['25', '89', '109']"
19267,31237,"Bach, French Suite 4, BWV 815, 5 Menuet",['5']

In [89]:
tracks_df.valid_genre.values

array(["['4', '74']", "['11', '15', '181', '296']",
       "['3', '27', '33', '38', '49', '76', '94', '103']", ...,
       "['15', '181']", "['15', '47', '107']", "['25', '85']"],
      dtype=object)

In [90]:
tracks_df.track_title

30770                                 Number 1
20752                         Phase Transition
25089                             Lady's Magik
25006                                  Traffic
96266                                Manchukuo
                         ...
98320    She Left Me For A Yeti (Wanda's Gone)
44131                                On My Own
9447                       The Things They Say
91895               When The Snails Broke Free
5059                    Dont Put My Name On It
Name: track_title, Length: 10419, dtype: object

In [91]:
## Get complete genre structure
def get_all_structure(estrutura,df_genres):
    ## Get structure from df_genres
    def get_all_structure_from_df(estrutura,df_genres,structure=[]):
        if estrutura == 0:
            return structure
        else:
            structure.append(int(estrutura))
            get_all_structure_from_df(df_genres[df_genres["genre_id"]==int(estrutura)].parent.values[0],df_genres,structure)
            return structure
    
    return get_all_structure_from_df(estrutura,df_genres,structure=[])

In [92]:
# tracks_df['valid_genre'] = tracks_df.track_genres.apply(lambda x: x.strip('][').split(', ') if x != '[]' else None)
tracks_df['valid_genre'] = tracks_df.valid_genre.apply(lambda x: ast.literal_eval(x))

In [93]:
tracks_df['last_genre_id'] = tracks_df.valid_genre.apply(lambda x:x[-1] if x != None else None)

In [94]:
tracks_df.sample(20)

,track_id,track_title,valid_genre,last_genre_id
89466,134444,Goodbye Earth,"[18, 107, 1235]",1235
58012,87259,Silky Silk,"[13, 15, 236]",236
49731,74373,To Drive the Cold Winter Away,[763],763
23725,37490,Improv w/ Richard Pinhas pt1,[38],38
56704,85524,Post Hoc,[66],66
36381,56085,Pole Dancing at the Banshee Labyrinth,"[32, 38, 250]",250
25264,39730,Disciple of Discipline,"[20, 38, 186]",186
99930,148662,Collage for Line 6 DL4 Delay Pedal (2016),"[1, 30, 38, 41, 247]",247
46795,70239,Badlands,[15],15
63909,97910,Celestical,[15],15
69174,107912,The Dream,"[15, 42, 400]",400
14624,23883,Musical moth,"[240, 297]",297
18268,29723,Transcriptions,"[15, 38, 76]",76
3095,5152,That's Fine With Me,[66],66
40642,61812,FAVELAS UNLIMITED,"[98, 361]",361
31276,48389,Veris leta facies,"[5, 187, 443]",443
24729,38990,Kick 2 The Clap,"[11, 15, 19]",19
41699,63259,The Spyin Blues,[12],12
100801,149796,Madame Zozo,"[15, 70, 181]",181
63438,97260,fatalidade - improviso de música e letra ao vi...,"[15, 70]",70

In [95]:
tracks_df.dropna(inplace=True)

In [96]:
tracks_df

,track_id,track_title,valid_genre,last_genre_id
30770,47710,Number 1,"[4, 74]",74
20752,33247,Phase Transition,"[11, 15, 181, 296]",296
25089,39502,Lady's Magik,"[3, 27, 33, 38, 49, 76, 94, 103]",103
25006,39415,Traffic,"[38, 42]",42
96266,143842,Manchukuo,"[15, 32, 38, 41]",41
...,...,...,...,...
98320,146688,She Left Me For A Yeti (Wanda's Gone),[21],21
44131,66319,On My Own,"[10, 103]",103
9447,15988,The Things They Say,"[15, 181]",181
91895,137888,When The Snails Broke Free,"[15, 47, 107]",107
5059,9810,Dont Put My Name On It,"[25, 85]",85

In [97]:
tracks_df['full_genre_id'] = tracks_df.last_genre_id.progress_apply(lambda x: get_all_structure(x,genres_df)[::-1])

  0%|          | 0/10419 [00:00<?, ?it/s]

In [98]:
tracks_df.full_genre_id

30770        [4, 74]
20752      [15, 296]
25089      [17, 103]
25006       [15, 42]
96266       [38, 41]
            ...
98320           [21]
44131      [17, 103]
9447       [15, 181]
91895    [1235, 107]
5059        [12, 85]
Name: full_genre_id, Length: 10419, dtype: object

In [99]:
tracks_df.columns

Index(['track_id', 'track_title', 'valid_genre', 'last_genre_id',
       'full_genre_id'],
      dtype='object')

In [100]:
tracks_df = tracks_df[['track_id','full_genre_id']]

In [101]:
tracks_df.full_genre_id.values

array([list([4, 74]), list([15, 296]), list([17, 103]), ...,
       list([15, 181]), list([1235, 107]), list([12, 85])], dtype=object)

In [102]:
tracks_df.full_genre_id.info

<bound method Series.info of 30770        [4, 74]
20752      [15, 296]
25089      [17, 103]
25006       [15, 42]
96266       [38, 41]
            ...
98320           [21]
44131      [17, 103]
9447       [15, 181]
91895    [1235, 107]
5059        [12, 85]
Name: full_genre_id, Length: 10419, dtype: object>

In [103]:
labels_size = tracks_df.full_genre_id.apply(lambda x: len(x))

In [104]:
labels_size = int(labels_size.max())

In [105]:
type(labels_size)

int

### Parse of label to structure

In [106]:
### Function for parse label to sctructure of hierarhical scheme

def parse_label(label,label_size=5):
    # label = label.split('-')
    # preencher com 0 no caso de haver menos de 5 níveis
    labels = np.zeros(label_size,dtype=int)
    for i, label in enumerate(label):
        if i == 5:
            break
        # Aqui você pode fazer a conversão do label em um índice inteiro usando um dicionário ou outro método
        # Neste exemplo, estou apenas usando a posição da label na lista como índice
        labels[i] = label
    return labels

In [107]:
parsed_labels = tracks_df.full_genre_id.apply(lambda x: parse_label(x))

In [108]:
parsed_labels

30770        [4, 74, 0, 0, 0]
20752      [15, 296, 0, 0, 0]
25089      [17, 103, 0, 0, 0]
25006       [15, 42, 0, 0, 0]
96266       [38, 41, 0, 0, 0]
                 ...
98320        [21, 0, 0, 0, 0]
44131      [17, 103, 0, 0, 0]
9447       [15, 181, 0, 0, 0]
91895    [1235, 107, 0, 0, 0]
5059        [12, 85, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [109]:
tracks_df['full_genre_id']

30770        [4, 74]
20752      [15, 296]
25089      [17, 103]
25006       [15, 42]
96266       [38, 41]
            ...
98320           [21]
44131      [17, 103]
9447       [15, 181]
91895    [1235, 107]
5059        [12, 85]
Name: full_genre_id, Length: 10419, dtype: object

In [110]:
parsed_labels

30770        [4, 74, 0, 0, 0]
20752      [15, 296, 0, 0, 0]
25089      [17, 103, 0, 0, 0]
25006       [15, 42, 0, 0, 0]
96266       [38, 41, 0, 0, 0]
                 ...
98320        [21, 0, 0, 0, 0]
44131      [17, 103, 0, 0, 0]
9447       [15, 181, 0, 0, 0]
91895    [1235, 107, 0, 0, 0]
5059        [12, 85, 0, 0, 0]
Name: full_genre_id, Length: 10419, dtype: object

In [111]:
def convert_label_to_string(x,level=2,string=False):
    
    if string:
        return '-'.join([str(value) for value in x[:level+1]])
    
    return x[level]

In [127]:
tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0,string=True))
tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1,string=True))
tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2,string=True))
tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3,string=True))
tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4,string=True))

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

In [113]:
tracks_df['labels_1'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=0))
tracks_df['labels_2'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=1))
tracks_df['labels_3'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=2))
tracks_df['labels_4'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=3))
tracks_df['labels_5'] = parsed_labels.progress_apply(lambda x: convert_label_to_string(x,level=4))

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

  0%|          | 0/10419 [00:00<?, ?it/s]

In [114]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(["38","1235"])]

In [128]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
30770,47710,"[4, 74]",4,4-74,4-74-0,4-74-0-0,4-74-0-0-0
20752,33247,"[15, 296]",15,15-296,15-296-0,15-296-0-0,15-296-0-0-0
25089,39502,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
25006,39415,"[15, 42]",15,15-42,15-42-0,15-42-0-0,15-42-0-0-0
96266,143842,"[38, 41]",38,38-41,38-41-0,38-41-0-0,38-41-0-0-0
...,...,...,...,...,...,...,...
98320,146688,[21],21,21-0,21-0-0,21-0-0-0,21-0-0-0-0
44131,66319,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
9447,15988,"[15, 181]",15,15-181,15-181-0,15-181-0-0,15-181-0-0-0
91895,137888,"[1235, 107]",1235,1235-107,1235-107-0,1235-107-0-0,1235-107-0-0-0
5059,9810,"[12, 85]",12,12-85,12-85-0,12-85-0-0,12-85-0-0-0

In [129]:
tracks_df['labels_4'].value_counts()

labels_4
38-0-0-0        689
1235-0-0-0      615
1235-107-0-0    426
10-76-0-0       418
15-0-0-0        351
               ...
2-86-174-0        1
2-46-1060-0       1
38-6-0-0          1
20-374-0-0        1
2-86-173-0        1
Name: count, Length: 153, dtype: int64

In [130]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0        689
1235-0-0-0-0      615
1235-107-0-0-0    426
10-76-0-0-0       418
15-0-0-0-0        351
                 ...
2-86-174-0-0        1
38-6-0-0-0          1
20-0-0-0-0          1
20-374-0-0-0        1
2-86-173-0-0        1
Name: count, Length: 154, dtype: int64

In [131]:
# tracks_df = tracks_df[tracks_df['labels_1'].isin(['3','14'])]

In [132]:
tracks_df

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5
30770,47710,"[4, 74]",4,4-74,4-74-0,4-74-0-0,4-74-0-0-0
20752,33247,"[15, 296]",15,15-296,15-296-0,15-296-0-0,15-296-0-0-0
25089,39502,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
25006,39415,"[15, 42]",15,15-42,15-42-0,15-42-0-0,15-42-0-0-0
96266,143842,"[38, 41]",38,38-41,38-41-0,38-41-0-0,38-41-0-0-0
...,...,...,...,...,...,...,...
98320,146688,[21],21,21-0,21-0-0,21-0-0-0,21-0-0-0-0
44131,66319,"[17, 103]",17,17-103,17-103-0,17-103-0-0,17-103-0-0-0
9447,15988,"[15, 181]",15,15-181,15-181-0,15-181-0-0,15-181-0-0-0
91895,137888,"[1235, 107]",1235,1235-107,1235-107-0,1235-107-0-0,1235-107-0-0-0
5059,9810,"[12, 85]",12,12-85,12-85-0,12-85-0-0,12-85-0-0-0

In [133]:
categories_df = pd.DataFrame({'level1':tracks_df.labels_1.unique()})

In [195]:
categories_df = tracks_df[['labels_1','labels_2','labels_3','labels_4','labels_5']].drop_duplicates()

In [196]:
categories_df

      labels_1 labels_2  labels_3    labels_4      labels_5
30770        4     4-74    4-74-0    4-74-0-0    4-74-0-0-0
20752       15   15-296  15-296-0  15-296-0-0  15-296-0-0-0
25089       17   17-103  17-103-0  17-103-0-0  17-103-0-0-0
25006       15    15-42   15-42-0   15-42-0-0   15-42-0-0-0
96266       38    38-41   38-41-0   38-41-0-0   38-41-0-0-0
...        ...      ...       ...         ...           ...
62468       21    21-83   21-83-0   21-83-0-0   21-83-0-0-0
29871       38     38-6    38-6-0    38-6-0-0    38-6-0-0-0
78802       13   13-170  13-170-0  13-170-0-0  13-170-0-0-0
23040       20   20-374  20-374-0  20-374-0-0  20-374-0-0-0
98180        2     2-86  2-86-173  2-86-173-0  2-86-173-0-0

[154 rows x 5 columns]

In [197]:
# categories_df['level1'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:1]))
# categories_df['level2'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:2]))
# categories_df['level3'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:3]))
# categories_df['level4'] = categories_df.level5.progress_apply(lambda x: '-'.join(x.split('-')[:4]))

In [198]:
categories_df

      labels_1 labels_2  labels_3    labels_4      labels_5
30770        4     4-74    4-74-0    4-74-0-0    4-74-0-0-0
20752       15   15-296  15-296-0  15-296-0-0  15-296-0-0-0
25089       17   17-103  17-103-0  17-103-0-0  17-103-0-0-0
25006       15    15-42   15-42-0   15-42-0-0   15-42-0-0-0
96266       38    38-41   38-41-0   38-41-0-0   38-41-0-0-0
...        ...      ...       ...         ...           ...
62468       21    21-83   21-83-0   21-83-0-0   21-83-0-0-0
29871       38     38-6    38-6-0    38-6-0-0    38-6-0-0-0
78802       13   13-170  13-170-0  13-170-0-0  13-170-0-0-0
23040       20   20-374  20-374-0  20-374-0-0  20-374-0-0-0
98180        2     2-86  2-86-173  2-86-173-0  2-86-173-0-0

[154 rows x 5 columns]

In [199]:
def get_labels_name(x,genres_df):
    levels = 5
    full_name = []
    last_level = 0
    genre_root = ""
    for genre in x.split('-'):
        genre_df = genres_df[genres_df['genre_id'] == int(genre)]
        if genre_df.empty:
            genre_name = genre_root 
        else:
            genre_name = genre_df.title.values.tolist()[0]
            genre_root = genre_name
        
        full_name.append(genre_name)
    full_name = '>'.join(full_name)
        
    return full_name
    # return genres_df[genres_df['genre_id'] == int(x)].title.values.tolist()[0]

In [200]:
categories_df['level5_name'] = categories_df.labels_5.apply(lambda x: get_labels_name(x,genres_df))

In [201]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name
30770,4,4-74,4-74-0,4-74-0-0,4-74-0-0-0,Jazz>Free-Jazz>Free-Jazz>Free-Jazz>Free-Jazz
20752,15,15-296,15-296-0,15-296-0-0,15-296-0-0-0,Electronic>Dance>Dance>Dance>Dance
25089,17,17-103,17-103-0,17-103-0-0,17-103-0-0-0,Folk>Singer-Songwriter>Singer-Songwriter>Singe...
25006,15,15-42,15-42-0,15-42-0-0,15-42-0-0-0,Electronic>Ambient Electronic>Ambient Electron...
96266,38,38-41,38-41-0,38-41-0-0,38-41-0-0-0,Experimental>Electroacoustic>Electroacoustic>E...
...,...,...,...,...,...,...
62468,21,21-83,21-83-0,21-83-0-0,21-83-0-0-0,Hip-Hop>Nerdcore>Nerdcore>Nerdcore>Nerdcore
29871,38,38-6,38-6-0,38-6-0-0,38-6-0-0-0,Experimental>Novelty>Novelty>Novelty>Novelty
78802,13,13-170,13-170-0,13-170-0-0,13-170-0-0-0,Easy Listening>Easy Listening: Vocal>Easy List...
23040,20,20-374,20-374-0,20-374-0-0,20-374-0-0-0,Spoken>Banter>Banter>Banter>Banter
98180,2,2-86,2-86-173,2-86-173-0,2-86-173-0-0,International>Indian>N. Indian Traditional>N. ...

In [202]:
def __create_labels__(categories_df):
    data = {
        "label1": {},
        "label2": {},
        "label3": {},
        "label4": {},
        "label5": {},
        "label1_inverse": [],
        "label2_inverse": [],
        "label3_inverse": [],
        "label4_inverse": [],
        "label5_inverse": [],
        "label1_name": {},
        "label2_name": {},
        "label3_name": {},
        "label4_name": {},
        "label5_name": {},
    }

    idx = 0
    
    for id_x, cat in enumerate(set(categories_df.labels_1.values.tolist())):
        data['label1'][cat] = idx
        data['label1_inverse'].append(cat)
        data['label1_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_2.values.tolist())):
        data['label2'][cat] = idx
        data['label2_inverse'].append(cat)
        data['label2_count'] = idx + 1
        idx+=1
        
    for id_x, cat in enumerate(set(categories_df.labels_3.values.tolist())):
        data['label3'][cat] = idx
        data['label3_inverse'].append(cat)
        data['label3_count'] = idx + 1
        idx+=1

    for id_x, cat in enumerate(set(categories_df.labels_4.values.tolist())):
        data['label4'][cat] = idx
        data['label4_inverse'].append(cat)
        data['label4_count'] = idx + 1
        idx+=1
        
    for idx, cat in enumerate(set(categories_df.labels_5.values.tolist())):
        data['label5'][cat] = idx
        data['label5_inverse'].append(cat)
        data['label5_count'] = idx + 1
        idx+=1
        
    for cat5,cat1,cat2,cat3,cat4,name5 in categories_df.values:
        
        name1 = '>'.join(name5.split('>')[:1])
        name2 = '>'.join(name5.split('>')[:2])
        name3 = '>'.join(name5.split('>')[:3])
        name4 = '>'.join(name5.split('>')[:4])
        
        
        data['label1_name'][cat1] = name1
        data['label2_name'][cat2] = name2
        data['label3_name'][cat3] = name3
        data['label4_name'][cat4] = name4
        data['label5_name'][cat5] = name5
        
    return data

In [203]:
with open(categories_labels_path, 'w+') as f:
    f.write(json.dumps(__create_labels__(categories_df)))

In [143]:
labels  = __create_labels__(categories_df)

In [144]:
labels

{'label1': {'17': 0,
  '9': 1,
  '12': 2,
  '4': 3,
  '15': 4,
  '5': 5,
  '38': 6,
  '8': 7,
  '10': 8,
  '2': 9,
  '14': 10,
  '21': 11,
  '3': 12,
  '13': 13,
  '1235': 14,
  '20': 15},
 'label2': {'1235-267': 16,
  '21-580': 17,
  '15-236': 18,
  '5-442': 19,
  '12-58': 20,
  '8-0': 21,
  '17-33': 22,
  '13-170': 23,
  '17-94': 24,
  '4-74': 25,
  '12-70': 26,
  '20-428': 27,
  '15-42': 28,
  '2-0': 29,
  '14-19': 30,
  '15-695': 31,
  '2-77': 32,
  '13-810': 33,
  '38-47': 34,
  '20-378': 35,
  '2-102': 36,
  '38-125': 37,
  '12-98': 38,
  '4-179': 39,
  '15-337': 40,
  '2-232': 41,
  '15-0': 42,
  '9-63': 43,
  '2-46': 44,
  '13-0': 45,
  '15-495': 46,
  '2-130': 47,
  '21-0': 48,
  '10-0': 49,
  '38-1': 50,
  '38-247': 51,
  '10-76': 52,
  '12-27': 53,
  '21-811': 54,
  '15-185': 55,
  '38-32': 56,
  '38-6': 57,
  '5-441': 58,
  '2-176': 59,
  '3-0': 60,
  '21-693': 61,
  '5-322': 62,
  '4-37': 63,
  '12-66': 64,
  '20-65': 65,
  '15-181': 66,
  '2-172': 67,
  '20-188': 68,
  '3-567': 69,
  '12-36': 70,
  '38-30': 71,
  '15-182': 72,
  '1235-107': 73,
  '15-296': 74,
  '21-539': 75,
  '9-651': 76,
  '15-297': 77,
  '5-659': 78,
  '20-465': 79,
  '15-183': 80,
  '20-374': 81,
  '5-443': 82,
  '20-0': 83,
  '38-250': 84,
  '15-184': 85,
  '2-504': 86,
  '21-100': 87,
  '38-456': 88,
  '4-97': 89,
  '12-359': 90,
  '1235-18': 91,
  '38-514': 92,
  '12-88': 93,
  '17-103': 94,
  '13-311': 95,
  '12-31': 96,
  '12-25': 97,
  '38-186': 98,
  '14-0': 99,
  '1235-0': 100,
  '15-286': 101,
  '12-26': 102,
  '17-49': 103,
  '9-169': 104,
  '9-0': 105,
  '12-440': 106,
  '5-0': 107,
  '17-180': 108,
  '10-362': 109,
  '12-85': 110,
  '9-137': 111,
  '14-11': 112,
  '21-83': 113,
  '2-92': 114,
  '21-542': 115,
  '15-468': 116,
  '4-0': 117,
  '20-138': 118,
  '38-22': 119,
  '17-0': 120,
  '12-0': 121,
  '38-41': 122,
  '12-314': 123,
  '2-171': 124,
  '5-187': 125,
  '12-45': 126,
  '2-177': 127,
  '38-224': 128,
  '2-86': 129,
  '2-118': 130,
  '4-906': 131,
  '38-0': 132,
  '2-79': 133},
 'label3': {'12-27-0': 134,
  '2-176-0': 135,
  '12-66-0': 136,
  '38-6-0': 137,
  '4-97-0': 138,
  '20-65-43': 139,
  '5-442-0': 140,
  '15-695-0': 141,
  '12-25-64': 142,
  '4-74-0': 143,
  '12-26-113': 144,
  '2-77-0': 145,
  '1235-107-0': 146,
  '8-0-0': 147,
  '12-25-109': 148,
  '9-169-0': 149,
  '4-179-0': 150,
  '21-693-0': 151,
  '38-6-16': 152,
  '13-311-0': 153,
  '14-11-0': 154,
  '5-187-0': 155,
  '2-46-1060': 156,
  '12-85-0': 157,
  '38-514-0': 158,
  '2-86-0': 159,
  '1235-0-0': 160,
  '38-47-0': 161,
  '2-92-81': 162,
  '2-177-0': 163,
  '17-94-0': 164,
  '12-31-167': 165,
  '20-465-0': 166,
  '2-504-0': 167,
  '2-86-174': 168,
  '20-428-0': 169,
  '14-0-0': 170,
  '20-0-0': 171,
  '9-137-0': 172,
  '13-0-0': 173,
  '3-567-0': 174,
  '1235-18-538': 175,
  '5-443-0': 176,
  '9-651-0': 177,
  '2-130-741': 178,
  '2-102-0': 179,
  '9-63-0': 180,
  '17-33-0': 181,
  '17-103-0': 182,
  '2-130-0': 183,
  '2-130-524': 184,
  '38-0-0': 185,
  '20-188-0': 186,
  '20-138-0': 187,
  '12-70-0': 188,
  '1235-267-0': 189,
  '21-811-0': 190,
  '12-25-71': 191,
  '12-85-404': 192,
  '2-86-173': 193,
  '15-181-401': 194,
  '20-374-0': 195,
  '21-542-0': 196,
  '10-0-0': 197,
  '17-49-0': 198,
  '21-539-0': 199,
  '5-322-0': 200,
  '2-171-0': 201,
  '15-0-0': 202,
  '12-45-53': 203,
  '38-250-0': 204,
  '15-236-0': 205,
  '2-172-0': 206,
  '38-125-0': 207,
  '10-76-0': 208,
  '38-224-0': 209,
  '17-180-0': 210,
  '4-906-0': 211,
  '2-46-0': 212,
  '2-79-602': 213,
  '17-0-0': 214,
  '12-88-0': 215,
  '20-65-166': 216,
  '5-441-0': 217,
  '15-286-0': 218,
  '12-31-439': 219,
  '15-468-491': 220,
  '2-130-1156': 221,
  '9-651-493': 222,
  '38-186-0': 223,
  '38-6-360': 224,
  '15-468-0': 225,
  '15-182-0': 226,
  '21-0-0': 227,
  '12-25-111': 228,
  '2-92-214': 229,
  '13-170-0': 230,
  '4-0-0': 231,
  '2-92-0': 232,
  '2-0-0': 233,
  '2-130-619': 234,
  '12-31-101': 235,
  '12-314-0': 236,
  '20-65-0': 237,
  '21-83-0': 238,
  '15-337-0': 239,
  '2-118-0': 240,
  '10-362-0': 241,
  '12-25-0': 242,
  '38-456-0': 243,
  '38-41-0': 244,
  '15-296-0': 245,
  '12-98-0': 246,
  '15-183-0': 247,
  '2-46-502': 248,
  '13-810-0': 249,
  '2-232-0': 250,
  '21-100-0': 251,
  '38-32-0': 252,
  '38-30-0': 253,
  '15-185-0': 254,
  '15-297-0': 255,
  '38-247-0': 256,
  '2-79-0': 257,
  '9-0-0': 258,
  '12-26-0': 259,
  '12-31-0': 260,
  '21-580-0': 261,
  '38-22-0': 262,
  '12-58-0': 263,
  '12-45-0': 264,
  '1235-18-0': 265,
  '5-659-0': 266,
  '20-378-0': 267,
  '15-495-0': 268,
  '12-0-0': 269,
  '15-184-0': 270,
  '12-359-0': 271,
  '15-182-400': 272,
  '5-0-0': 273,
  '12-25-89': 274,
  '2-102-1032': 275,
  '15-297-240': 276,
  '14-19-0': 277,
  '38-1-0': 278,
  '12-36-0': 279,
  '15-42-0': 280,
  '3-0-0': 281,
  '12-440-0': 282,
  '15-181-0': 283,
  '4-37-0': 284},
 'label4': {'21-83-0-0': 285,
  '38-224-0-0': 286,
  '12-0-0-0': 287,
  '2-130-524-0': 288,
  '2-118-0-0': 289,
  '2-92-214-0': 290,
  '2-102-1032-0': 291,
  '2-176-0-0': 292,
  '15-185-0-0': 293,
  '12-31-167-0': 294,
  '38-247-0-0': 295,
  '2-46-0-0': 296,
  '21-542-0-0': 297,
  '38-0-0-0': 298,
  '14-19-0-0': 299,
  '20-428-0-0': 300,
  '38-32-0-0': 301,
  '4-906-0-0': 302,
  '15-468-491-0': 303,
  '21-580-0-0': 304,
  '12-31-0-0': 305,
  '1235-18-0-0': 306,
  '2-130-1156-0': 307,
  '38-186-0-0': 308,
  '12-88-0-0': 309,
  '12-25-71-0': 310,
  '15-236-0-0': 311,
  '15-468-0-0': 312,
  '9-651-493-0': 313,
  '20-0-0-0': 314,
  '17-94-0-0': 315,
  '20-378-0-0': 316,
  '5-441-0-0': 317,
  '12-45-53-90': 318,
  '12-36-0-0': 319,
  '1235-18-538-0': 320,
  '38-22-0-0': 321,
  '38-250-0-0': 322,
  '4-179-0-0': 323,
  '38-125-0-0': 324,
  '9-0-0-0': 325,
  '12-26-113-0': 326,
  '21-811-0-0': 327,
  '12-31-439-0': 328,
  '2-86-174-0': 329,
  '17-0-0-0': 330,
  '2-46-1060-0': 331,
  '38-1-0-0': 332,
  '21-0-0-0': 333,
  '20-65-166-0': 334,
  '14-11-0-0': 335,
  '17-49-0-0': 336,
  '2-46-502-0': 337,
  '12-70-0-0': 338,
  '2-77-0-0': 339,
  '15-296-0-0': 340,
  '12-25-111-0': 341,
  '20-188-0-0': 342,
  '21-693-0-0': 343,
  '17-33-0-0': 344,
  '5-442-0-0': 345,
  '20-374-0-0': 346,
  '15-181-0-0': 347,
  '15-0-0-0': 348,
  '15-297-240-0': 349,
  '5-0-0-0': 350,
  '5-443-0-0': 351,
  '12-25-109-361': 352,
  '12-45-53-0': 353,
  '9-169-0-0': 354,
  '21-539-0-0': 355,
  '2-172-0-0': 356,
  '12-25-109-0': 357,
  '38-47-0-0': 358,
  '12-85-404-0': 359,
  '15-184-0-0': 360,
  '10-0-0-0': 361,
  '13-311-0-0': 362,
  '3-567-0-0': 363,
  '15-495-0-0': 364,
  '20-138-0-0': 365,
  '38-30-0-0': 366,
  '9-63-0-0': 367,
  '15-183-0-0': 368,
  '12-45-0-0': 369,
  '12-98-0-0': 370,
  '2-177-0-0': 371,
  '15-337-0-0': 372,
  '15-182-0-0': 373,
  '1235-267-0-0': 374,
  '1235-107-0-0': 375,
  '2-130-741-0': 376,
  '10-76-0-0': 377,
  '12-314-0-0': 378,
  '14-0-0-0': 379,
  '12-58-0-0': 380,
  '12-26-0-0': 381,
  '2-86-173-0': 382,
  '17-180-0-0': 383,
  '38-6-360-0': 384,
  '12-25-89-0': 385,
  '8-0-0-0': 386,
  '13-810-0-0': 387,
  '2-232-0-0': 388,
  '2-86-0-0': 389,
  '2-130-0-0': 390,
  '12-440-0-0': 391,
  '15-181-401-0': 392,
  '15-182-400-0': 393,
  '20-65-0-0': 394,
  '12-27-0-0': 395,
  '9-137-0-0': 396,
  '38-6-0-0': 397,
  '2-79-602-0': 398,
  '4-37-0-0': 399,
  '13-0-0-0': 400,
  '12-66-0-0': 401,
  '2-0-0-0': 402,
  '4-74-0-0': 403,
  '15-286-0-0': 404,
  '15-297-0-0': 405,
  '1235-0-0-0': 406,
  '15-695-0-0': 407,
  '5-322-0-0': 408,
  '12-85-0-0': 409,
  '15-42-0-0': 410,
  '21-100-0-0': 411,
  '2-102-0-0': 412,
  '10-362-0-0': 413,
  '17-103-0-0': 414,
  '9-651-0-0': 415,
  '38-456-0-0': 416,
  '2-130-619-0': 417,
  '12-31-101-0': 418,
  '12-359-0-0': 419,
  '38-514-0-0': 420,
  '38-6-16-763': 421,
  '12-25-64-0': 422,
  '20-465-0-0': 423,
  '4-97-0-0': 424,
  '38-41-0-0': 425,
  '13-170-0-0': 426,
  '12-25-0-0': 427,
  '5-659-0-0': 428,
  '4-0-0-0': 429,
  '2-79-0-0': 430,
  '2-92-81-0': 431,
  '2-171-0-0': 432,
  '2-504-0-0': 433,
  '3-0-0-0': 434,
  '5-187-0-0': 435,
  '2-92-0-0': 436,
  '20-65-43-0': 437},
 'label5': {'38-6-16-763-1193': 0,
  '4-97-0-0-0': 1,
  '20-65-0-0-0': 2,
  '38-125-0-0-0': 3,
  '12-26-0-0-0': 4,
  '21-542-0-0-0': 5,
  '9-651-0-0-0': 6,
  '20-428-0-0-0': 7,
  '15-182-400-0-0': 8,
  '20-138-0-0-0': 9,
  '12-58-0-0-0': 10,
  '17-94-0-0-0': 11,
  '2-130-0-0-0': 12,
  '4-0-0-0-0': 13,
  '12-31-167-0-0': 14,
  '12-25-109-0-0': 15,
  '38-456-0-0-0': 16,
  '38-247-0-0-0': 17,
  '20-378-0-0-0': 18,
  '2-172-0-0-0': 19,
  '15-0-0-0-0': 20,
  '15-42-0-0-0': 21,
  '2-130-524-0-0': 22,
  '12-25-71-0-0': 23,
  '15-468-491-0-0': 24,
  '15-184-0-0-0': 25,
  '4-179-0-0-0': 26,
  '12-31-101-0-0': 27,
  '10-76-0-0-0': 28,
  '12-25-89-0-0': 29,
  '20-374-0-0-0': 30,
  '5-441-0-0-0': 31,
  '2-79-0-0-0': 32,
  '9-651-493-0-0': 33,
  '12-0-0-0-0': 34,
  '38-6-360-0-0': 35,
  '2-0-0-0-0': 36,
  '15-296-0-0-0': 37,
  '12-85-404-0-0': 38,
  '15-236-0-0-0': 39,
  '5-443-0-0-0': 40,
  '12-66-0-0-0': 41,
  '13-0-0-0-0': 42,
  '12-85-0-0-0': 43,
  '4-906-0-0-0': 44,
  '12-31-439-0-0': 45,
  '2-86-174-0-0': 46,
  '2-504-0-0-0': 47,
  '38-22-0-0-0': 48,
  '12-26-113-0-0': 49,
  '15-297-240-0-0': 50,
  '13-810-0-0-0': 51,
  '15-337-0-0-0': 52,
  '21-0-0-0-0': 53,
  '15-181-401-0-0': 54,
  '12-36-0-0-0': 55,
  '12-314-0-0-0': 56,
  '15-185-0-0-0': 57,
  '12-70-0-0-0': 58,
  '13-311-0-0-0': 59,
  '5-442-0-0-0': 60,
  '38-30-0-0-0': 61,
  '12-25-109-361-0': 62,
  '21-693-0-0-0': 63,
  '2-46-1060-0-0': 64,
  '21-580-0-0-0': 65,
  '9-137-0-0-0': 66,
  '12-98-0-0-0': 67,
  '1235-107-0-0-0': 68,
  '2-118-0-0-0': 69,
  '14-0-0-0-0': 70,
  '20-65-43-0-0': 71,
  '12-359-0-0-0': 72,
  '1235-18-0-0-0': 73,
  '21-83-0-0-0': 74,
  '15-297-0-0-0': 75,
  '17-0-0-0-0': 76,
  '9-63-0-0-0': 77,
  '21-811-0-0-0': 78,
  '12-45-53-0-0': 79,
  '12-45-0-0-0': 80,
  '2-77-0-0-0': 81,
  '8-0-0-0-0': 82,
  '21-100-0-0-0': 83,
  '17-103-0-0-0': 84,
  '12-25-64-0-0': 85,
  '20-0-0-0-0': 86,
  '1235-267-0-0-0': 87,
  '3-567-0-0-0': 88,
  '2-171-0-0-0': 89,
  '38-1-0-0-0': 90,
  '2-46-0-0-0': 91,
  '14-19-0-0-0': 92,
  '38-47-0-0-0': 93,
  '17-33-0-0-0': 94,
  '5-0-0-0-0': 95,
  '2-92-214-0-0': 96,
  '15-181-0-0-0': 97,
  '21-539-0-0-0': 98,
  '15-468-0-0-0': 99,
  '2-176-0-0-0': 100,
  '15-495-0-0-0': 101,
  '15-695-0-0-0': 102,
  '2-46-502-0-0': 103,
  '13-170-0-0-0': 104,
  '9-169-0-0-0': 105,
  '20-65-166-0-0': 106,
  '15-182-0-0-0': 107,
  '12-25-111-0-0': 108,
  '2-102-0-0-0': 109,
  '5-322-0-0-0': 110,
  '12-25-0-0-0': 111,
  '5-659-0-0-0': 112,
  '38-186-0-0-0': 113,
  '2-130-619-0-0': 114,
  '38-6-16-763-0': 115,
  '3-0-0-0-0': 116,
  '4-37-0-0-0': 117,
  '12-45-53-90-0': 118,
  '15-286-0-0-0': 119,
  '1235-18-538-0-0': 120,
  '1235-0-0-0-0': 121,
  '2-177-0-0-0': 122,
  '12-31-0-0-0': 123,
  '2-102-1032-0-0': 124,
  '20-465-0-0-0': 125,
  '10-0-0-0-0': 126,
  '2-92-81-0-0': 127,
  '20-188-0-0-0': 128,
  '2-232-0-0-0': 129,
  '38-0-0-0-0': 130,
  '38-224-0-0-0': 131,
  '15-183-0-0-0': 132,
  '14-11-0-0-0': 133,
  '2-86-0-0-0': 134,
  '9-0-0-0-0': 135,
  '2-79-602-0-0': 136,
  '10-362-0-0-0': 137,
  '38-250-0-0-0': 138,
  '38-514-0-0-0': 139,
  '38-41-0-0-0': 140,
  '38-32-0-0-0': 141,
  '2-92-0-0-0': 142,
  '12-27-0-0-0': 143,
  '17-49-0-0-0': 144,
  '38-6-0-0-0': 145,
  '4-74-0-0-0': 146,
  '12-440-0-0-0': 147,
  '2-86-173-0-0': 148,
  '2-130-741-0-0': 149,
  '2-130-1156-0-0': 150,
  '12-88-0-0-0': 151,
  '5-187-0-0-0': 152,
  '17-180-0-0-0': 153},
 'label1_inverse': ['17',
  '9',
  '12',
  '4',
  '15',
  '5',
  '38',
  '8',
  '10',
  '2',
  '14',
  '21',
  '3',
  '13',
  '1235',
  '20'],
 'label2_inverse': ['1235-267',
  '21-580',
  '15-236',
  '5-442',
  '12-58',
  '8-0',
  '17-33',
  '13-170',
  '17-94',
  '4-74',
  '12-70',
  '20-428',
  '15-42',
  '2-0',
  '14-19',
  '15-695',
  '2-77',
  '13-810',
  '38-47',
  '20-378',
  '2-102',
  '38-125',
  '12-98',
  '4-179',
  '15-337',
  '2-232',
  '15-0',
  '9-63',
  '2-46',
  '13-0',
  '15-495',
  '2-130',
  '21-0',
  '10-0',
  '38-1',
  '38-247',
  '10-76',
  '12-27',
  '21-811',
  '15-185',
  '38-32',
  '38-6',
  '5-441',
  '2-176',
  '3-0',
  '21-693',
  '5-322',
  '4-37',
  '12-66',
  '20-65',
  '15-181',
  '2-172',
  '20-188',
  '3-567',
  '12-36',
  '38-30',
  '15-182',
  '1235-107',
  '15-296',
  '21-539',
  '9-651',
  '15-297',
  '5-659',
  '20-465',
  '15-183',
  '20-374',
  '5-443',
  '20-0',
  '38-250',
  '15-184',
  '2-504',
  '21-100',
  '38-456',
  '4-97',
  '12-359',
  '1235-18',
  '38-514',
  '12-88',
  '17-103',
  '13-311',
  '12-31',
  '12-25',
  '38-186',
  '14-0',
  '1235-0',
  '15-286',
  '12-26',
  '17-49',
  '9-169',
  '9-0',
  '12-440',
  '5-0',
  '17-180',
  '10-362',
  '12-85',
  '9-137',
  '14-11',
  '21-83',
  '2-92',
  '21-542',
  '15-468',
  '4-0',
  '20-138',
  '38-22',
  '17-0',
  '12-0',
  '38-41',
  '12-314',
  '2-171',
  '5-187',
  '12-45',
  '2-177',
  '38-224',
  '2-86',
  '2-118',
  '4-906',
  '38-0',
  '2-79'],
 'label3_inverse': ['12-27-0',
  '2-176-0',
  '12-66-0',
  '38-6-0',
  '4-97-0',
  '20-65-43',
  '5-442-0',
  '15-695-0',
  '12-25-64',
  '4-74-0',
  '12-26-113',
  '2-77-0',
  '1235-107-0',
  '8-0-0',
  '12-25-109',
  '9-169-0',
  '4-179-0',
  '21-693-0',
  '38-6-16',
  '13-311-0',
  '14-11-0',
  '5-187-0',
  '2-46-1060',
  '12-85-0',
  '38-514-0',
  '2-86-0',
  '1235-0-0',
  '38-47-0',
  '2-92-81',
  '2-177-0',
  '17-94-0',
  '12-31-167',
  '20-465-0',
  '2-504-0',
  '2-86-174',
  '20-428-0',
  '14-0-0',
  '20-0-0',
  '9-137-0',
  '13-0-0',
  '3-567-0',
  '1235-18-538',
  '5-443-0',
  '9-651-0',
  '2-130-741',
  '2-102-0',
  '9-63-0',
  '17-33-0',
  '17-103-0',
  '2-130-0',
  '2-130-524',
  '38-0-0',
  '20-188-0',
  '20-138-0',
  '12-70-0',
  '1235-267-0',
  '21-811-0',
  '12-25-71',
  '12-85-404',
  '2-86-173',
  '15-181-401',
  '20-374-0',
  '21-542-0',
  '10-0-0',
  '17-49-0',
  '21-539-0',
  '5-322-0',
  '2-171-0',
  '15-0-0',
  '12-45-53',
  '38-250-0',
  '15-236-0',
  '2-172-0',
  '38-125-0',
  '10-76-0',
  '38-224-0',
  '17-180-0',
  '4-906-0',
  '2-46-0',
  '2-79-602',
  '17-0-0',
  '12-88-0',
  '20-65-166',
  '5-441-0',
  '15-286-0',
  '12-31-439',
  '15-468-491',
  '2-130-1156',
  '9-651-493',
  '38-186-0',
  '38-6-360',
  '15-468-0',
  '15-182-0',
  '21-0-0',
  '12-25-111',
  '2-92-214',
  '13-170-0',
  '4-0-0',
  '2-92-0',
  '2-0-0',
  '2-130-619',
  '12-31-101',
  '12-314-0',
  '20-65-0',
  '21-83-0',
  '15-337-0',
  '2-118-0',
  '10-362-0',
  '12-25-0',
  '38-456-0',
  '38-41-0',
  '15-296-0',
  '12-98-0',
  '15-183-0',
  '2-46-502',
  '13-810-0',
  '2-232-0',
  '21-100-0',
  '38-32-0',
  '38-30-0',
  '15-185-0',
  '15-297-0',
  '38-247-0',
  '2-79-0',
  '9-0-0',
  '12-26-0',
  '12-31-0',
  '21-580-0',
  '38-22-0',
  '12-58-0',
  '12-45-0',
  '1235-18-0',
  '5-659-0',
  '20-378-0',
  '15-495-0',
  '12-0-0',
  '15-184-0',
  '12-359-0',
  '15-182-400',
  '5-0-0',
  '12-25-89',
  '2-102-1032',
  '15-297-240',
  '14-19-0',
  '38-1-0',
  '12-36-0',
  '15-42-0',
  '3-0-0',
  '12-440-0',
  '15-181-0',
  '4-37-0'],
 'label4_inverse': ['21-83-0-0',
  '38-224-0-0',
  '12-0-0-0',
  '2-130-524-0',
  '2-118-0-0',
  '2-92-214-0',
  '2-102-1032-0',
  '2-176-0-0',
  '15-185-0-0',
  '12-31-167-0',
  '38-247-0-0',
  '2-46-0-0',
  '21-542-0-0',
  '38-0-0-0',
  '14-19-0-0',
  '20-428-0-0',
  '38-32-0-0',
  '4-906-0-0',
  '15-468-491-0',
  '21-580-0-0',
  '12-31-0-0',
  '1235-18-0-0',
  '2-130-1156-0',
  '38-186-0-0',
  '12-88-0-0',
  '12-25-71-0',
  '15-236-0-0',
  '15-468-0-0',
  '9-651-493-0',
  '20-0-0-0',
  '17-94-0-0',
  '20-378-0-0',
  '5-441-0-0',
  '12-45-53-90',
  '12-36-0-0',
  '1235-18-538-0',
  '38-22-0-0',
  '38-250-0-0',
  '4-179-0-0',
  '38-125-0-0',
  '9-0-0-0',
  '12-26-113-0',
  '21-811-0-0',
  '12-31-439-0',
  '2-86-174-0',
  '17-0-0-0',
  '2-46-1060-0',
  '38-1-0-0',
  '21-0-0-0',
  '20-65-166-0',
  '14-11-0-0',
  '17-49-0-0',
  '2-46-502-0',
  '12-70-0-0',
  '2-77-0-0',
  '15-296-0-0',
  '12-25-111-0',
  '20-188-0-0',
  '21-693-0-0',
  '17-33-0-0',
  '5-442-0-0',
  '20-374-0-0',
  '15-181-0-0',
  '15-0-0-0',
  '15-297-240-0',
  '5-0-0-0',
  '5-443-0-0',
  '12-25-109-361',
  '12-45-53-0',
  '9-169-0-0',
  '21-539-0-0',
  '2-172-0-0',
  '12-25-109-0',
  '38-47-0-0',
  '12-85-404-0',
  '15-184-0-0',
  '10-0-0-0',
  '13-311-0-0',
  '3-567-0-0',
  '15-495-0-0',
  '20-138-0-0',
  '38-30-0-0',
  '9-63-0-0',
  '15-183-0-0',
  '12-45-0-0',
  '12-98-0-0',
  '2-177-0-0',
  '15-337-0-0',
  '15-182-0-0',
  '1235-267-0-0',
  '1235-107-0-0',
  '2-130-741-0',
  '10-76-0-0',
  '12-314-0-0',
  '14-0-0-0',
  '12-58-0-0',
  '12-26-0-0',
  '2-86-173-0',
  '17-180-0-0',
  '38-6-360-0',
  '12-25-89-0',
  '8-0-0-0',
  '13-810-0-0',
  '2-232-0-0',
  '2-86-0-0',
  '2-130-0-0',
  '12-440-0-0',
  '15-181-401-0',
  '15-182-400-0',
  '20-65-0-0',
  '12-27-0-0',
  '9-137-0-0',
  '38-6-0-0',
  '2-79-602-0',
  '4-37-0-0',
  '13-0-0-0',
  '12-66-0-0',
  '2-0-0-0',
  '4-74-0-0',
  '15-286-0-0',
  '15-297-0-0',
  '1235-0-0-0',
  '15-695-0-0',
  '5-322-0-0',
  '12-85-0-0',
  '15-42-0-0',
  '21-100-0-0',
  '2-102-0-0',
  '10-362-0-0',
  '17-103-0-0',
  '9-651-0-0',
  '38-456-0-0',
  '2-130-619-0',
  '12-31-101-0',
  '12-359-0-0',
  '38-514-0-0',
  '38-6-16-763',
  '12-25-64-0',
  '20-465-0-0',
  '4-97-0-0',
  '38-41-0-0',
  '13-170-0-0',
  '12-25-0-0',
  '5-659-0-0',
  '4-0-0-0',
  '2-79-0-0',
  '2-92-81-0',
  '2-171-0-0',
  '2-504-0-0',
  '3-0-0-0',
  '5-187-0-0',
  '2-92-0-0',
  '20-65-43-0'],
 'label5_inverse': ['38-6-16-763-1193',
  '4-97-0-0-0',
  '20-65-0-0-0',
  '38-125-0-0-0',
  '12-26-0-0-0',
  '21-542-0-0-0',
  '9-651-0-0-0',
  '20-428-0-0-0',
  '15-182-400-0-0',
  '20-138-0-0-0',
  '12-58-0-0-0',
  '17-94-0-0-0',
  '2-130-0-0-0',
  '4-0-0-0-0',
  '12-31-167-0-0',
  '12-25-109-0-0',
  '38-456-0-0-0',
  '38-247-0-0-0',
  '20-378-0-0-0',
  '2-172-0-0-0',
  '15-0-0-0-0',
  '15-42-0-0-0',
  '2-130-524-0-0',
  '12-25-71-0-0',
  '15-468-491-0-0',
  '15-184-0-0-0',
  '4-179-0-0-0',
  '12-31-101-0-0',
  '10-76-0-0-0',
  '12-25-89-0-0',
  '20-374-0-0-0',
  '5-441-0-0-0',
  '2-79-0-0-0',
  '9-651-493-0-0',
  '12-0-0-0-0',
  '38-6-360-0-0',
  '2-0-0-0-0',
  '15-296-0-0-0',
  '12-85-404-0-0',
  '15-236-0-0-0',
  '5-443-0-0-0',
  '12-66-0-0-0',
  '13-0-0-0-0',
  '12-85-0-0-0',
  '4-906-0-0-0',
  '12-31-439-0-0',
  '2-86-174-0-0',
  '2-504-0-0-0',
  '38-22-0-0-0',
  '12-26-113-0-0',
  '15-297-240-0-0',
  '13-810-0-0-0',
  '15-337-0-0-0',
  '21-0-0-0-0',
  '15-181-401-0-0',
  '12-36-0-0-0',
  '12-314-0-0-0',
  '15-185-0-0-0',
  '12-70-0-0-0',
  '13-311-0-0-0',
  '5-442-0-0-0',
  '38-30-0-0-0',
  '12-25-109-361-0',
  '21-693-0-0-0',
  '2-46-1060-0-0',
  '21-580-0-0-0',
  '9-137-0-0-0',
  '12-98-0-0-0',
  '1235-107-0-0-0',
  '2-118-0-0-0',
  '14-0-0-0-0',
  '20-65-43-0-0',
  '12-359-0-0-0',
  '1235-18-0-0-0',
  '21-83-0-0-0',
  '15-297-0-0-0',
  '17-0-0-0-0',
  '9-63-0-0-0',
  '21-811-0-0-0',
  '12-45-53-0-0',
  '12-45-0-0-0',
  '2-77-0-0-0',
  '8-0-0-0-0',
  '21-100-0-0-0',
  '17-103-0-0-0',
  '12-25-64-0-0',
  '20-0-0-0-0',
  '1235-267-0-0-0',
  '3-567-0-0-0',
  '2-171-0-0-0',
  '38-1-0-0-0',
  '2-46-0-0-0',
  '14-19-0-0-0',
  '38-47-0-0-0',
  '17-33-0-0-0',
  '5-0-0-0-0',
  '2-92-214-0-0',
  '15-181-0-0-0',
  '21-539-0-0-0',
  '15-468-0-0-0',
  '2-176-0-0-0',
  '15-495-0-0-0',
  '15-695-0-0-0',
  '2-46-502-0-0',
  '13-170-0-0-0',
  '9-169-0-0-0',
  '20-65-166-0-0',
  '15-182-0-0-0',
  '12-25-111-0-0',
  '2-102-0-0-0',
  '5-322-0-0-0',
  '12-25-0-0-0',
  '5-659-0-0-0',
  '38-186-0-0-0',
  '2-130-619-0-0',
  '38-6-16-763-0',
  '3-0-0-0-0',
  '4-37-0-0-0',
  '12-45-53-90-0',
  '15-286-0-0-0',
  '1235-18-538-0-0',
  '1235-0-0-0-0',
  '2-177-0-0-0',
  '12-31-0-0-0',
  '2-102-1032-0-0',
  '20-465-0-0-0',
  '10-0-0-0-0',
  '2-92-81-0-0',
  '20-188-0-0-0',
  '2-232-0-0-0',
  '38-0-0-0-0',
  '38-224-0-0-0',
  '15-183-0-0-0',
  '14-11-0-0-0',
  '2-86-0-0-0',
  '9-0-0-0-0',
  '2-79-602-0-0',
  '10-362-0-0-0',
  '38-250-0-0-0',
  '38-514-0-0-0',
  '38-41-0-0-0',
  '38-32-0-0-0',
  '2-92-0-0-0',
  '12-27-0-0-0',
  '17-49-0-0-0',
  '38-6-0-0-0',
  '4-74-0-0-0',
  '12-440-0-0-0',
  '2-86-173-0-0',
  '2-130-741-0-0',
  '2-130-1156-0-0',
  '12-88-0-0-0',

In [145]:
categories_df['labels_1_'] = categories_df.labels_1.apply(lambda x: labels['label1'].get(x))
categories_df['labels_2_'] = categories_df.labels_2.apply(lambda x: labels['label2'].get(x))
categories_df['labels_3_'] = categories_df.labels_3.apply(lambda x: labels['label3'].get(x))
categories_df['labels_4_'] = categories_df.labels_4.apply(lambda x: labels['label4'].get(x))
categories_df['labels_5_'] = categories_df.labels_5.apply(lambda x: labels['label5'].get(x))

In [146]:
categories_df

,labels_1,labels_2,labels_3,labels_4,labels_5,level5_name,labels_1_,labels_2_,labels_3_,labels_4_,labels_5_
30770,4,4-74,4-74-0,4-74-0-0,4-74-0-0-0,Jazz>Free-Jazz>Free-Jazz>Free-Jazz>Free-Jazz,3,25,143,403,146
20752,15,15-296,15-296-0,15-296-0-0,15-296-0-0-0,Electronic>Dance>Dance>Dance>Dance,4,74,245,340,37
25089,17,17-103,17-103-0,17-103-0-0,17-103-0-0-0,Folk>Singer-Songwriter>Singer-Songwriter>Singe...,0,94,182,414,84
25006,15,15-42,15-42-0,15-42-0-0,15-42-0-0-0,Electronic>Ambient Electronic>Ambient Electron...,4,28,280,410,21
96266,38,38-41,38-41-0,38-41-0-0,38-41-0-0-0,Experimental>Electroacoustic>Electroacoustic>E...,6,122,244,425,140
...,...,...,...,...,...,...,...,...,...,...,...
62468,21,21-83,21-83-0,21-83-0-0,21-83-0-0-0,Hip-Hop>Nerdcore>Nerdcore>Nerdcore>Nerdcore,11,113,238,285,74
29871,38,38-6,38-6-0,38-6-0-0,38-6-0-0-0,Experimental>Novelty>Novelty>Novelty>Novelty,6,57,137,397,145
78802,13,13-170,13-170-0,13-170-0-0,13-170-0-0-0,Easy Listening>Easy Listening: Vocal>Easy List...,13,23,230,426,104
23040,20,20-374,20-374-0,20-374-0-0,20-374-0-0-0,Spoken>Banter>Banter>Banter>Banter,15,81,195,346,30
98180,2,2-86,2-86-173,2-86-173-0,2-86-173-0-0,International>Indian>N. Indian Traditional>N. ...,9,129,193,382,148

In [147]:
unique_labels_1 = categories_df['labels_1_'].unique().tolist()
unique_labels_2 = categories_df['labels_2_'].unique().tolist()
unique_labels_3 = categories_df['labels_3_'].unique().tolist()
unique_labels_4 = categories_df['labels_4_'].unique().tolist()
unique_labels_5 = categories_df['labels_5_'].unique().tolist()

In [148]:
unique_labels_1

[3, 4, 0, 6, 1, 10, 2, 9, 14, 15, 13, 8, 11, 5, 7, 12]

In [149]:
num_nodes_per_level = [unique_labels_1, unique_labels_2, unique_labels_3, unique_labels_4, unique_labels_5]

In [159]:
# Cálculo de num_classes_per_node
num_classes_per_node = []
num_classes_per_node.append(unique_labels_1)  # Nível 1

unique_lavel2_per_level1 = categories_df.groupby('labels_1_')['labels_2_'].nunique()
num_classes_per_node.append(unique_lavel2_per_level1.tolist())  # Nível 2

In [160]:
unique_lavel3_per_level2 = categories_df.groupby(['labels_1_', 'labels_2_'])['labels_3_'].nunique()
num_classes_per_node.append(unique_lavel3_per_level2.tolist())  # Nível 3

In [161]:
unique_lavel4_per_level3 = categories_df.groupby(['labels_1_', 'labels_2_', 'labels_3_'])['labels_4_'].nunique()
num_classes_per_node.append(unique_lavel4_per_level3.tolist())  # Nível 4

In [162]:

unique_lavel5_per_level4 = categories_df.groupby(['labels_1_', 'labels_2_', 'labels_3_', 'labels_4_'])['labels_5_'].nunique()
num_classes_per_node.append(unique_lavel5_per_level4.tolist())  # Nível 5

In [163]:

print("num_nodes_per_level:", num_classes_per_node[0])

num_nodes_per_level: [3, 4, 0, 6, 1, 10, 2, 9, 14, 15, 13, 8, 11, 5, 7, 12]

In [164]:
labels['label5']

{'38-6-16-763-1193': 0,
 '4-97-0-0-0': 1,
 '20-65-0-0-0': 2,
 '38-125-0-0-0': 3,
 '12-26-0-0-0': 4,
 '21-542-0-0-0': 5,
 '9-651-0-0-0': 6,
 '20-428-0-0-0': 7,
 '15-182-400-0-0': 8,
 '20-138-0-0-0': 9,
 '12-58-0-0-0': 10,
 '17-94-0-0-0': 11,
 '2-130-0-0-0': 12,
 '4-0-0-0-0': 13,
 '12-31-167-0-0': 14,
 '12-25-109-0-0': 15,
 '38-456-0-0-0': 16,
 '38-247-0-0-0': 17,
 '20-378-0-0-0': 18,
 '2-172-0-0-0': 19,
 '15-0-0-0-0': 20,
 '15-42-0-0-0': 21,
 '2-130-524-0-0': 22,
 '12-25-71-0-0': 23,
 '15-468-491-0-0': 24,
 '15-184-0-0-0': 25,
 '4-179-0-0-0': 26,
 '12-31-101-0-0': 27,
 '10-76-0-0-0': 28,
 '12-25-89-0-0': 29,
 '20-374-0-0-0': 30,
 '5-441-0-0-0': 31,
 '2-79-0-0-0': 32,
 '9-651-493-0-0': 33,
 '12-0-0-0-0': 34,
 '38-6-360-0-0': 35,
 '2-0-0-0-0': 36,
 '15-296-0-0-0': 37,
 '12-85-404-0-0': 38,
 '15-236-0-0-0': 39,
 '5-443-0-0-0': 40,
 '12-66-0-0-0': 41,
 '13-0-0-0-0': 42,
 '12-85-0-0-0': 43,
 '4-906-0-0-0': 44,
 '12-31-439-0-0': 45,
 '2-86-174-0-0': 46,
 '2-504-0-0-0': 47,
 '38-22-0-0-0': 48,
 '12-26-113-0-0': 49,
 '15-297-240-0-0': 50,
 '13-810-0-0-0': 51,
 '15-337-0-0-0': 52,
 '21-0-0-0-0': 53,
 '15-181-401-0-0': 54,
 '12-36-0-0-0': 55,
 '12-314-0-0-0': 56,
 '15-185-0-0-0': 57,
 '12-70-0-0-0': 58,
 '13-311-0-0-0': 59,
 '5-442-0-0-0': 60,
 '38-30-0-0-0': 61,
 '12-25-109-361-0': 62,
 '21-693-0-0-0': 63,
 '2-46-1060-0-0': 64,
 '21-580-0-0-0': 65,
 '9-137-0-0-0': 66,
 '12-98-0-0-0': 67,
 '1235-107-0-0-0': 68,
 '2-118-0-0-0': 69,
 '14-0-0-0-0': 70,
 '20-65-43-0-0': 71,
 '12-359-0-0-0': 72,
 '1235-18-0-0-0': 73,
 '21-83-0-0-0': 74,
 '15-297-0-0-0': 75,
 '17-0-0-0-0': 76,
 '9-63-0-0-0': 77,
 '21-811-0-0-0': 78,
 '12-45-53-0-0': 79,
 '12-45-0-0-0': 80,
 '2-77-0-0-0': 81,
 '8-0-0-0-0': 82,
 '21-100-0-0-0': 83,
 '17-103-0-0-0': 84,
 '12-25-64-0-0': 85,
 '20-0-0-0-0': 86,
 '1235-267-0-0-0': 87,
 '3-567-0-0-0': 88,
 '2-171-0-0-0': 89,
 '38-1-0-0-0': 90,
 '2-46-0-0-0': 91,
 '14-19-0-0-0': 92,
 '38-47-0-0-0': 93,
 '17-33-0-0-0': 94,
 '5-0-0-0-0': 95,
 '2-92-214-0-0': 96,
 '15-181-0-0-0': 97,
 '21-539-0-0-0': 98,
 '15-468-0-0-0': 99,
 '2-176-0-0-0': 100,
 '15-495-0-0-0': 101,
 '15-695-0-0-0': 102,
 '2-46-502-0-0': 103,
 '13-170-0-0-0': 104,
 '9-169-0-0-0': 105,
 '20-65-166-0-0': 106,
 '15-182-0-0-0': 107,
 '12-25-111-0-0': 108,
 '2-102-0-0-0': 109,
 '5-322-0-0-0': 110,
 '12-25-0-0-0': 111,
 '5-659-0-0-0': 112,
 '38-186-0-0-0': 113,
 '2-130-619-0-0': 114,
 '38-6-16-763-0': 115,
 '3-0-0-0-0': 116,
 '4-37-0-0-0': 117,
 '12-45-53-90-0': 118,
 '15-286-0-0-0': 119,
 '1235-18-538-0-0': 120,
 '1235-0-0-0-0': 121,
 '2-177-0-0-0': 122,
 '12-31-0-0-0': 123,
 '2-102-1032-0-0': 124,
 '20-465-0-0-0': 125,
 '10-0-0-0-0': 126,
 '2-92-81-0-0': 127,
 '20-188-0-0-0': 128,
 '2-232-0-0-0': 129,
 '38-0-0-0-0': 130,
 '38-224-0-0-0': 131,
 '15-183-0-0-0': 132,
 '14-11-0-0-0': 133,
 '2-86-0-0-0': 134,
 '9-0-0-0-0': 135,
 '2-79-602-0-0': 136,
 '10-362-0-0-0': 137,
 '38-250-0-0-0': 138,
 '38-514-0-0-0': 139,
 '38-41-0-0-0': 140,
 '38-32-0-0-0': 141,
 '2-92-0-0-0': 142,
 '12-27-0-0-0': 143,
 '17-49-0-0-0': 144,
 '38-6-0-0-0': 145,
 '4-74-0-0-0': 146,
 '12-440-0-0-0': 147,
 '2-86-173-0-0': 148,
 '2-130-741-0-0': 149,
 '2-130-1156-0-0': 150,
 '12-88-0-0-0': 151,
 '5-187-0-0-0': 152,
 '17-180-0-0-0': 153}

In [165]:
labels['label1_count']

16

In [166]:


def parse_tfr_element(element):
    #use the same structure as above; it's kinda an outline of the structure we now want to create
    data = {
        'emb' : tf.io.FixedLenFeature([], tf.string),
        'track_id' : tf.io.FixedLenFeature([], tf.int64),
    }
    
    content = tf.io.parse_single_example(element, data)

    track_id = content['track_id']
    emb = content['emb']
    

    #get our 'feature'-- our image -- and reshape it appropriately
    feature = tf.io.parse_tensor(emb, out_type=tf.float32)
    return (feature, track_id)


def get_dataset(filename):
    #create the dataset
    dataset = tf.data.TFRecordDataset(filename)

    #pass every single feature through our mapping function
    dataset = dataset.map(
        parse_tfr_element
    )

    return dataset

In [167]:
import numpy as np


def load_dataset(path,dataset=args.embeddings):
    tfrecords_path = os.path.join(path,'tfrecords',dataset)
    
    
    tfrecords_path = [os.path.join(tfrecords_path,path) for path in os.listdir(tfrecords_path)]
    dataset = get_dataset(tfrecords_path)
    
    df = pd.DataFrame(
        dataset.as_numpy_iterator(),
        columns=['feature', 'track_id']
    )
        
    df.dropna(inplace=True)
    
    
    try:
        df.feature = df.feature.apply(lambda x: x[0] if x.shape[0] != 0 else None)
    except:
        print(x)
    
    return df

In [168]:
tracks_df['labels_5'].value_counts()

labels_5
38-0-0-0-0        689
1235-0-0-0-0      615
1235-107-0-0-0    426
10-76-0-0-0       418
15-0-0-0-0        351
                 ...
2-86-174-0-0        1
38-6-0-0-0          1
20-0-0-0-0          1
20-374-0-0-0        1
2-86-173-0-0        1
Name: count, Length: 154, dtype: int64

In [169]:
def __split_data__(group, percentage=0.1):
    if len(group) == 1:
        return group, group

    shuffled = shuffle(group.values)
    finish_test = int(ceil(len(group) * percentage))

    first = pd.DataFrame(shuffled[:finish_test], columns=group.columns)
    second = pd.DataFrame(shuffled[finish_test:], columns=group.columns)

    return first, second

In [170]:
def select_dataset(tracks_df):
    
#     dataset_testset_path = os.path.join(tfrecord_path,'test')
#     dataset_validationset_path = os.path.join(tfrecord_path,'val')
#     dataset_trainset_path = os.path.join(tfrecord_path,'train')
    
    df = load_dataset(args.dataset_path,dataset=args.embeddings)
    
    df.dropna(inplace=True)
    
    tracks_df = tracks_df.merge(df, on='track_id')
    
    tracks_df.loc[:,'labels_1'] = tracks_df.labels_1.astype(str).progress_apply(lambda x: labels['label1'][x])
    tracks_df.loc[:,'labels_2'] = tracks_df.labels_2.astype(str).progress_apply(lambda x: labels['label2'][x])
    tracks_df.loc[:,'labels_3'] = tracks_df.labels_3.astype(str).progress_apply(lambda x: labels['label3'][x])
    tracks_df.loc[:,'labels_4'] = tracks_df.labels_4.astype(str).progress_apply(lambda x: labels['label4'][x])
    tracks_df.loc[:,'labels_5'] = tracks_df.labels_5.astype(str).progress_apply(lambda x: labels['label5'][x])
    
    tests = []
    trains = []
    validations = []
    groups = tracks_df.groupby("labels_5")
    
    
    count = 0
    items_count = 0
    total = len(groups)
    total_items = len(tracks_df)
    oversampling_size = 30  # int(group_sizes.mean() + group_sizes.std() * 2)
    print(f"oversampling_size: {oversampling_size}")

    for code, group in groups:
        test, train_to_split = __split_data__(group, 0.01)  # 10%
        train_to_split = train_to_split
        validation, train = __split_data__(train_to_split, 0.01)  # %1

        tests.append(test)
        validations.append(validation)

        ## this increase the numner of samples when classes has low quantity
        count_train = len(train)
        if count_train < oversampling_size:
            train = train.sample(oversampling_size, replace=True)

        trains.append(train)

        count += 1
        items_count += count_train
        
        
    df_test = pd.concat(tests, sort=False).sample(frac=1).reset_index(drop=True)
    # .to_csv(dataset_testset_path, index=False,quoting=csv.QUOTE_ALL)
    df_val = pd.concat(validations, sort=False).sample(frac=1).reset_index(drop=True)
    df_train = pd.concat(trains, sort=False).sample(frac=1).reset_index(drop=True)

    return df_train,df_test,df_val

In [171]:
df_train,df_test,df_val = select_dataset(tracks_df)

2023-07-10 10:55:33.641298: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [11]
	 [[{{node Placeholder/_0}}]]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

  0%|          | 0/10418 [00:00<?, ?it/s]

oversampling_size: 30

In [172]:
df_train

,track_id,full_genre_id,labels_1,labels_2,labels_3,labels_4,labels_5,feature
0,70767,"[5, 322]",5,62,200,408,110,"[0.3922772, -0.0066737137, -0.00035289922, -0...."
1,133395,[12],2,121,269,287,34,"[0.04035734, 0.08205969, -0.053230215, -0.0412..."
2,75896,"[5, 322]",5,62,200,408,110,"[0.03941387, -0.034183312, 0.019382149, -0.029..."
3,8674,"[10, 76]",8,52,208,377,28,"[0.06538965, 0.021337012, 0.027512172, 0.20818..."
4,133716,[1235],14,100,160,406,121,"[-0.027412027, 0.013083249, 0.0140009625, -0.0..."
...,...,...,...,...,...,...,...,...
11716,154142,"[38, 41]",6,122,244,425,140,"[0.008524965, 0.00071506697, -0.040768158, -0...."
11717,24640,"[15, 297]",4,77,255,405,75,"[-0.009763758, -0.029230157, -0.008527319, -0...."
11718,11254,[38],6,132,185,298,130,"[0.17769118, 0.011544357, 0.107087426, 0.09629..."
11719,66751,"[12, 58]",2,20,263,380,10,"[0.02525566, 0.00011809667, -0.060789883, 0.02..."
11720,57771,"[17, 94]",0,24,164,315,11,"[-0.013568342, 0.03541571, -0.016415328, 0.049..."

In [173]:
def _bytes_feature(value):
  ### Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))): # if value ist tensor
        value = value.numpy() # get value of tensor
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def _float_feature(value):
  ### Returns a floast_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64List_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def _int64_feature(value):
  ###  Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def serialize_array(array):
    array = tf.io.serialize_tensor(array)
    return array

In [174]:
def parse_single_music(data,labels):
    track_id, _, cat1, cat2, cat3, cat4, cat5, music = data
    
    
    label1 = np.array([cat1, labels['label1_count']], np.int64)
    label2 = np.array([cat2, labels['label2_count']], np.int64)
    label3 = np.array([cat3, labels['label3_count']], np.int64)
    label4 = np.array([cat4, labels['label4_count']], np.int64)
    label5 = np.array([cat5, labels['label5_count']], np.int64)
    
    
    
    #define the dictionary -- the structure -- of our single example
    data = {
        'label1': _int64List_feature(label1),
        'label2': _int64List_feature(label2),
        'label3': _int64List_feature(label3),
        'label4': _int64List_feature(label4),
        'label5': _int64List_feature(label5),
        # 'features' : _bytes_feature(serialize_array(music)),
        'features' : _float_feature(music),
        'track_id' : _int64_feature(track_id)
    }
    #create an Example, wrapping the single features
    out = tf.train.Example(features=tf.train.Features(feature=data))

    return out

In [175]:
def generate_tf_record(df,tf_path='val'):
    create_dir(tf_path)
    
    
    batch_size = 1024 * 50 # 50k records from each file batch
    count = 0
    total = math.ceil(len(df) / batch_size)

    for i in range(0, len(df), batch_size):
        batch_df = df[i:i+batch_size]
        
        tfrecords = [parse_single_music(data, labels) for data in batch_df.values]
        
        path = f"{tf_path}/{str(count).zfill(10)}.tfrecord"
        
        #with tf.python_io.TFRecordWriter(path) as writer:
        with tf.io.TFRecordWriter(path) as writer:
            for tfrecord in tfrecords:
                writer.write(tfrecord.SerializeToString())

        print(f"{count} {len(tfrecords)} {path}")
        count += 1
        print(f"{count}/{total} batchs / {count * batch_size} processed")

    print(f"{count}/{total} batchs / {len(df)} processed")
    
    return tf_path

In [176]:
tfrecord_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords'

In [177]:
val_path = generate_tf_record(df_val,tf_path=os.path.join(tfrecord_path,'val'))

0 215 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/val/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 215 processed

In [178]:
test_path = generate_tf_record(df_test,tf_path=os.path.join(tfrecord_path,'test'))

0 216 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/test/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 216 processed

In [179]:
train_path = generate_tf_record(df_train,tf_path=os.path.join(tfrecord_path,'train'))

0 11721 /mnt/disks/data/fma/trains/hierarchical_local_sample/tfrecords/train/0000000000.tfrecord
1/1 batchs / 51200 processed
1/1 batchs / 11721 processed

In [180]:
def create_metadata(metadata_path):

    with open(metadata_path, 'w+') as f:
        f.write(json.dumps({
            'sequence_size': args.sequence_size,
            'n_levels': labels_size,
            'num_nodes_per_level':num_nodes_per_level,
            'num_classes_per_node':num_classes_per_node,
            'labels_size': [labels['label1_count'],labels['label2_count'],
                           labels['label3_count'],labels['label4_count'],
                           labels['label5_count']],
            'val_path': val_path,
            'train_path': train_path,
            'test_path': test_path,
            'trainset_count': len(df_train),
            'validationset_count': len(df_val),
            'testset_count': len(df_test)
        }))

In [186]:
num_nodes_per_level

[[3, 4, 0, 6, 1, 10, 2, 9, 14, 15, 13, 8, 11, 5, 7, 12],
 [25,
  74,
  94,
  28,
  122,
  132,
  111,
  34,
  77,
  99,
  97,
  37,
  29,
  102,
  80,
  100,
  20,
  118,
  64,
  110,
  33,
  18,
  73,
  109,
  53,
  61,
  66,
  93,
  54,
  120,
  46,
  38,
  48,
  121,
  65,
  62,
  133,
  84,
  87,
  49,
  85,
  106,
  52,
  47,
  51,
  42,
  123,
  16,
  126,
  43,
  116,
  96,
  92,
  72,
  21,
  95,
  26,
  88,
  119,
  68,
  124,
  69,
  90,
  101,
  115,
  19,
  91,
  76,
  57,
  128,
  78,
  40,
  103,
  70,
  56,
  17,
  22,
  31,
  89,
  107,
  131,
  44,
  130,
  58,
  117,
  125,
  112,
  104,
  24,
  75,
  35,
  114,
  71,
  50,
  108,
  98,
  30,
  83,
  127,
  60,
  27,
  82,
  55,
  32,
  86,
  67,
  63,
  36,
  129,
  105,
  79,
  59,
  45,
  39,
  41,
  113,
  23,
  81],
 [143,
  245,
  182,
  280,
  244,
  185,
  172,
  161,
  255,
  170,
  242,
  207,
  233,
  144,
  247,
  160,
  263,
  187,
  136,
  157,
  249,
  205,
  146,
  241,
  134,
  151,
  283,
  215,
  190,
  259,
  214,
  268,
  246,
  227,
  148,
  269,
  139,
  200,
  257,
  204,
  251,
  197,
  274,
  270,
  282,
  208,
  183,
  256,
  202,
  236,
  189,
  203,
  180,
  225,
  264,
  235,
  158,
  226,
  228,
  147,
  153,
  188,
  243,
  262,
  186,
  201,
  174,
  271,
  191,
  218,
  196,
  140,
  265,
  177,
  224,
  276,
  209,
  266,
  239,
  198,
  279,
  142,
  252,
  237,
  175,
  234,
  261,
  181,
  141,
  138,
  273,
  222,
  211,
  248,
  240,
  217,
  194,
  272,
  231,
  155,
  154,
  260,
  149,
  164,
  199,
  212,
  267,
  232,
  219,
  253,
  278,
  192,
  210,
  152,
  216,
  213,
  223,
  277,
  171,
  163,
  281,
  169,
  162,
  176,
  254,
  145,
  167,
  184,
  206,
  178,
  229,
  284,
  220,
  275,
  179,
  168,
  258,
  159,
  166,
  135,
  173,
  165,
  150,
  156,
  250,
  221,
  238,
  137,
  230,
  195,
  193],
 [403,
  340,
  414,
  410,
  425,
  298,
  396,
  358,
  405,
  379,
  427,
  324,
  402,
  326,
  368,
  406,
  380,
  365,
  401,
  409,
  387,
  311,
  375,
  413,
  395,
  343,
  347,
  309,
  327,
  381,
  330,
  364,
  370,
  333,
  357,
  287,
  437,
  408,
  430,
  322,
  411,
  361,
  385,
  360,
  391,
  377,
  390,
  295,
  348,
  378,
  374,
  353,
  367,
  312,
  369,
  418,
  420,
  373,
  318,
  341,
  386,
  362,
  338,
  416,
  321,
  342,
  432,
  363,
  419,
  310,
  404,
  297,
  345,
  306,
  415,
  384,
  349,
  286,
  428,
  372,
  336,
  319,
  422,
  301,
  394,
  320,
  417,
  304,
  344,
  407,
  424,
  350,
  313,
  302,
  337,
  289,
  317,
  392,
  393,
  429,
  435,
  335,
  305,
  354,
  315,
  355,
  296,
  316,
  436,
  328,
  366,
  332,
  359,
  383,
  421,
  334,
  398,
  308,
  299,
  314,
  371,
  434,
  300,
  431,
  351,
  293,
  339,
  433,
  288,
  356,
  376,
  290,
  399,
  303,
  291,
  412,
  329,
  352,
  325,
  389,
  423,
  292,
  400,
  294,
  323,
  331,
  388,
  307,
  285,
  397,
  426,
  346,
  382],
 [146,
  37,
  84,
  21,
  140,
  130,
  66,
  93,
  75,
  70,
  111,
  3,
  36,
  49,
  132,
  121,
  10,
  9,
  41,
  43,
  51,
  39,
  68,
  137,
  143,
  63,
  97,
  151,
  78,
  4,
  76,
  101,
  67,
  53,
  15,
  34,
  71,
  110,
  32,
  138,
  83,
  126,
  29,
  25,
  147,
  28,
  12,
  17,
  20,
  56,
  87,
  79,
  77,
  99,
  80,
  27,
  139,
  107,
  118,
  108,
  82,
  59,
  58,
  16,
  48,
  128,
  89,
  88,
  72,
  23,
  119,
  5,
  60,
  73,
  6,
  35,
  50,
  131,
  112,
  52,
  144,
  55,
  85,
  141,
  2,
  120,
  114,
  65,
  94,
  102,
  1,
  95,
  33,
  44,
  103,
  69,
  31,
  54,
  8,
  13,
  152,
  133,
  123,
  105,
  11,
  98,
  91,
  18,
  142,
  45,
  61,
  90,
  38,
  153,
  115,
  106,
  136,
  113,
  92,
  86,
  122,
  116,
  7,
  127,
  40,
  0,
  57,
  81,
  47,
  22,
  19,
  149,
  96,
  117,
  24,
  124,
  109,
  46,
  62,
  135,
  134,
  125,
  100,
  42,
  14,
  26,
  64,
  129,
  150,
  74,
  145,
  104,
  30,
  148]]

In [187]:
create_metadata(metadata_path)

In [188]:
job_path

'/mnt/disks/data/fma/trains/hierarchical_local_sample'

In [189]:
tracks_df.to_csv(os.path.join(job_path,"tracks.csv"),index=False)

In [190]:
with open(categories_labels_path, 'r') as f:
    labels = json.loads(f.read())

FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: '/mnt/disks/data/fma/trains/hierarchical_local_sample/labels.json'

In [ ]:
levels_size = {'level1_size': labels['label1_count']-1,
        'level2_size': labels['label2_count']-1,
        'level3_size': labels['label3_count']-1,
        'level4_size': labels['label4_count']-1,
        'level5_size': labels['label5_count']-1}

In [ ]:
levels_size['level1_size']